use std::fmt::Display;

pub enum Command {
    AccessLevel,
    AccessLevelAnnounceLogin,
    AccessLevelAutokickImmunity,
    AccessLevelChat,
    AccessLevelChatTimeout,
    AccessLevelHideOf,
    AccessLevelHideTo,
    AccessLevelIps,
    AccessLevelListAdmins,
    AccessLevelListAdminsSeeEveryone,
    AccessLevelNver,
    AccessLevelPlay,
    AccessLevelPlaySliders,
    AccessLevelPlaySliding,
    AccessLevelRtfm,
    AccessLevelShout,
    AccessLevelShuffleUp,
    AccessLevelSpyMsg,
    AccessLevelSpyTeam,
    AccessLevelVoteCommand,
    AccessLevelVoteCommandExecute,
    AccessLevelVoteInclude,
    AccessLevelVoteIncludeExecute,
    AccessLevelVoteKick,
    AccessLevelVoteSilence,
    AccessLevelVoteSuspend,
    AddHelpTopic,
    AddMasterServer,
    Admins,
    AdminListColorsBestBlue,
    AdminListColorsBestGreen,
    AdminListColorsBestRed,
    AdminListColorsWorstBlue,
    AdminListColorsWorstGreen,
    AdminListColorsWorstRed,
    AdminListMinAccessLevel,
    AiIq,
    AliveLocx,
    AliveLocy,
    AliveSize,
    AllowCam1_0,
    AllowCam1_1,
    AllowCam1_2,
    AllowCam1_3,
    AllowCam1_4,
    AllowCam1_5,
    AllowCam1_6,
    AllowCam2_0,
    AllowCam2_1,
    AllowCam2_2,
    AllowCam2_3,
    AllowCam2_4,
    AllowCam2_5,
    AllowCam2_6,
    AllowCam3_0,
    AllowCam3_1,
    AllowCam3_2,
    AllowCam3_3,
    AllowCam3_4,
    AllowCam3_5,
    AllowCam3_6,
    AllowCam4_0,
    AllowCam4_1,
    AllowCam4_2,
    AllowCam4_3,
    AllowCam4_4,
    AllowCam4_5,
    AllowCam4_6,
    AllowControlDuringChat,
    AllowEnemiesSameClient,
    AllowEnemiesSameIp,
    AllowImposters,
    AllowImpostors,
    AllowRenamePlayer,
    AllowTeamChange,
    AllowTeamChangePlayer,
    AllowTeamNameColor,
    AllowTeamNamePlayer,
    AllowVoting,
    AllowVotingSpectator,
    AlphaBlend,
    AntiSpoof,
    ArenaAxes,
    ArenaAxesOverride,
    ArmagetronLastScreenmode,
    ArmagetronLastWindowsize,
    ArmagetronScreenmode,
    ArmagetronVsync,
    ArmagetronVsyncLast,
    ArmagetronWindowsize,
    AuthorityBlacklist,
    AuthorityLevel,
    AuthorityWhitelist,
    AutoAis,
    AutoIncam1,
    AutoIncam2,
    AutoIncam3,
    AutoIncam4,
    AutoIq,
    AutoLogin1,
    AutoLogin2,
    AutoLogin3,
    AutoLogin4,
    AutoTeam,
    AutoTeamSpecSpam,
    AxesIndicator,
    BackwardCompatibility,
    Ban,
    BanIp,
    BanList,
    BanUser,
    BanUserList,
    BigBrother,
    Bookmark0Address,
    Bookmark0Name,
    Bookmark0Port,
    Bookmark10Address,
    Bookmark10Name,
    Bookmark10Port,
    Bookmark1Address,
    Bookmark1Name,
    Bookmark1Port,
    Bookmark2Address,
    Bookmark2Name,
    Bookmark2Port,
    Bookmark3Address,
    Bookmark3Name,
    Bookmark3Port,
    Bookmark4Address,
    Bookmark4Name,
    Bookmark4Port,
    Bookmark5Address,
    Bookmark5Name,
    Bookmark5Port,
    Bookmark6Address,
    Bookmark6Name,
    Bookmark6Port,
    Bookmark7Address,
    Bookmark7Name,
    Bookmark7Port,
    Bookmark8Address,
    Bookmark8Name,
    Bookmark8Port,
    Bookmark9Address,
    Bookmark9Name,
    Bookmark9Port,
    BookmarkMaster0Address,
    BookmarkMaster0Name,
    BookmarkMaster0Port,
    BookmarkMaster10Address,
    BookmarkMaster10Name,
    BookmarkMaster10Port,
    BookmarkMaster1Address,
    BookmarkMaster1Name,
    BookmarkMaster1Port,
    BookmarkMaster2Address,
    BookmarkMaster2Name,
    BookmarkMaster2Port,
    BookmarkMaster3Address,
    BookmarkMaster3Name,
    BookmarkMaster3Port,
    BookmarkMaster4Address,
    BookmarkMaster4Name,
    BookmarkMaster4Port,
    BookmarkMaster5Address,
    BookmarkMaster5Name,
    BookmarkMaster5Port,
    BookmarkMaster6Address,
    BookmarkMaster6Name,
    BookmarkMaster6Port,
    BookmarkMaster7Address,
    BookmarkMaster7Name,
    BookmarkMaster7Port,
    BookmarkMaster8Address,
    BookmarkMaster8Name,
    BookmarkMaster8Port,
    BookmarkMaster9Address,
    BookmarkMaster9Name,
    BookmarkMaster9Port,
    BrakeGaugeLocx,
    BrakeGaugeLocy,
    BrakeGaugeSize,
    BugColorOverflow,
    BugRip,
    BugTransparency,
    BugTransparencyDemand,
    BugTunnel,
    Camcenter1,
    Camcenter2,
    Camcenter3,
    Camcenter4,
    CameraCustomBack,
    CameraCustomBackFromspeed,
    CameraCustomPitch,
    CameraCustomRise,
    CameraCustomRiseFromspeed,
    CameraCustomTurnSpeed,
    CameraCustomTurnSpeed180,
    CameraCustomZoom,
    CameraFollowStartX,
    CameraFollowStartY,
    CameraFollowStartZ,
    CameraForbidCustom,
    CameraForbidCustomGlance,
    CameraForbidFollow,
    CameraForbidFree,
    CameraForbidIn,
    CameraForbidServerCustom,
    CameraForbidSmart,
    CameraFreeStartX,
    CameraFreeStartY,
    CameraFreeStartZ,
    CameraGlanceBack,
    CameraGlanceBackFromspeed,
    CameraGlancePitch,
    CameraGlanceRise,
    CameraGlanceRiseFromspeed,
    CameraInTurnSpeed,
    CameraOverrideCustomGlance,
    CameraOverrideCustomGlanceServerCustom,
    CameraServerCustomBack,
    CameraServerCustomBackFromspeed,
    CameraServerCustomPitch,
    CameraServerCustomRise,
    CameraServerCustomRiseFromspeed,
    CameraServerCustomTurnSpeed,
    CameraServerCustomTurnSpeed180,
    CameraServerGlanceBack,
    CameraServerGlanceBackFromspeed,
    CameraServerGlancePitch,
    CameraServerGlanceRise,
    CameraServerGlanceRiseFromspeed,
    CameraSmartStartX,
    CameraSmartStartY,
    CameraSmartStartZ,
    CameraVisibilityClipSpeed,
    CameraVisibilityExtension,
    CameraVisibilityLowerWall,
    CameraVisibilityLowerWallSmart,
    CameraVisibilityRecoverySpeed,
    CameraVisibilitySideskew,
    CameraVisibilityWallDistance,
    Camwobble1,
    Camwobble2,
    Camwobble3,
    Camwobble4,
    Casacl,
    CenterMessage,
    ChatbotAlwaysActive,
    ChatbotDecay,
    ChatbotDelay,
    ChatbotMinTimestep,
    ChatbotNewWallBlindness,
    ChatbotRange,
    ChatterRemoveTime,
    ChatLog,
    ChatTooltip,
    CheckErrors,
    ClientPort,
    CmLocy,
    Colordepth,
    ColorB1,
    ColorB2,
    ColorB3,
    ColorB4,
    ColorG1,
    ColorG2,
    ColorG3,
    ColorG4,
    ColorR1,
    ColorR2,
    ColorR3,
    ColorR4,
    ColorStrings,
    ConnectionFloodSensitivity,
    ConnectionLimit,
    ConsoleColumns,
    ConsoleIndent,
    ConsoleLadderLog,
    ConsoleLog,
    ConsoleMessage,
    ConsoleRows,
    ConsoleRowsMax,
    CustomScreenAspect,
    CustomScreenHeight,
    CustomScreenWidth,
    CustomServerName,
    CycleAccel,
    CycleAccelEnemy,
    CycleAccelEnemyOverride,
    CycleAccelOffset,
    CycleAccelRim,
    CycleAccelRimOverride,
    CycleAccelSelf,
    CycleAccelSelfOverride,
    CycleAccelSlingshot,
    CycleAccelSlingshotOverride,
    CycleAccelTeam,
    CycleAccelTeamOverride,
    CycleAccelTunnel,
    CycleAccelTunnelOverride,
    CycleAvoidOldclientBadSync,
    CycleBlinkFrequency,
    CycleBoostfactorEnemy,
    CycleBoostfactorEnemyOverride,
    CycleBoostfactorRim,
    CycleBoostfactorRimOverride,
    CycleBoostfactorSelf,
    CycleBoostfactorSelfOverride,
    CycleBoostfactorTeam,
    CycleBoostfactorTeamOverride,
    CycleBoostEnemy,
    CycleBoostEnemyOverride,
    CycleBoostRim,
    CycleBoostRimOverride,
    CycleBoostSelf,
    CycleBoostSelfOverride,
    CycleBoostTeam,
    CycleBoostTeamOverride,
    CycleBrake,
    CycleBrakeDeplete,
    CycleBrakeDepleteOverride,
    CycleBrakeRefill,
    CycleBrakeRefillOverride,
    CycleBrakeTooltip,
    CycleDelay,
    CycleDelayDoublebindBonus,
    CycleDelayDoublebindBonusOverride,
    CycleDelayTimebased,
    CycleDelayTimebasedOverride,
    CycleDistWallShrink,
    CycleDistWallShrinkOffset,
    CycleFairAntilag,
    CycleFirstSpawnProtection,
    CycleInvulnerableTime,
    CycleMaxRefcount,
    CyclePacketlossTolerance,
    CyclePingRubber,
    CycleRubber,
    CycleRubberDelay,
    CycleRubberDelayBonus,
    CycleRubberDelayBonusOverride,
    CycleRubberDelayOverride,
    CycleRubberLegacy,
    CycleRubberMalusTurnOverride,
    CycleRubberMinadjust,
    CycleRubberMinadjustOverride,
    CycleRubberMindistance,
    CycleRubberMindistanceGap,
    CycleRubberMindistanceGapBackdoor,
    CycleRubberMindistanceGapBackdoorOverride,
    CycleRubberMindistanceGapOverride,
    CycleRubberMindistanceGapSide,
    CycleRubberMindistanceLegacy,
    CycleRubberMindistanceOverride,
    CycleRubberMindistancePreparation,
    CycleRubberMindistancePreparationOverride,
    CycleRubberMindistanceRatio,
    CycleRubberMindistanceRatioOverride,
    CycleRubberMindistanceReservoir,
    CycleRubberMindistanceReservoirOverride,
    CycleRubberMindistanceUnprepared,
    CycleRubberMindistanceUnpreparedOverride,
    CycleRubberSpeed,
    CycleRubberSpeedOverride,
    CycleRubberTime,
    CycleRubberTimebased,
    CycleRubberTimebasedOverride,
    CycleRubberTimeOverride,
    CycleRubberWallShrink,
    CycleRubberWallShrinkOverride,
    CycleSmoothMinSpeed,
    CycleSmoothThreshold,
    CycleSmoothTime,
    CycleSoundSpeed,
    CycleSpeed,
    CycleSpeedDecayAbove,
    CycleSpeedDecayAboveOverride,
    CycleSpeedDecayBelow,
    CycleSpeedDecayBelowOverride,
    CycleSpeedMax,
    CycleSpeedMaxOverride,
    CycleSpeedMin,
    CycleSpeedMinOverride,
    CycleStartSpeed,
    CycleSyncFf,
    CycleSyncFfSteps,
    CycleSyncIntervalEnemy,
    CycleSyncIntervalSelf,
    CycleTimeTolerance,
    CycleTimeToleranceOverride,
    CycleTurnLeftTooltip,
    CycleTurnMemory,
    CycleTurnRightTooltip,
    CycleTurnSpeedFactor,
    CycleTurnSpeedFactorOverride,
    CycleWallNear,
    CycleWallTime,
    CycleWidth,
    CycleWidthOverride,
    CycleWidthRubberMax,
    CycleWidthRubberMaxOverride,
    CycleWidthRubberMin,
    CycleWidthRubberMinOverride,
    CycleWidthSide,
    CycleWidthSideOverride,
    DeclareRoundWinner,
    DedicatedIdle,
    DefaultKickReason,
    DefaultKickToPort,
    DefaultKickToReason,
    DefaultKickToServer,
    DefaultShoutPlayer,
    DefaultShoutSpectator,
    DisallowRenamePlayer,
    DisallowTeamChangePlayer,
    Dither,
    DoublebindTime,
    DoublebindTimeOverride,
    EnableChat,
    EnableFriends,
    EnemyChatbotPenalty,
    EnemyCurrenttimeInfluence,
    EnemyDeadPenalty,
    EnemySuicideTimeout,
    EnemyTeammatePenalty,
    ExpectAckOnClientPlayback,
    Explosion,
    ExplosionRadius,
    ExtraRoundTime,
    FadeoutNameDelay,
    FailedAttempts,
    FastestLocx,
    FastestLocy,
    FastestSize,
    FastForwardMaxstep,
    FastForwardMaxstepReal,
    FastForwardMaxstepRel,
    FavNumPerTeamPlayer1,
    FavNumPerTeamPlayer2,
    FavNumPerTeamPlayer3,
    FavNumPerTeamPlayer4,
    FilterColorNames,
    FilterColorServerNames,
    FilterColorStrings,
    FilterColorTeam,
    FilterDarkColorNames,
    FilterDarkColorServerNames,
    FilterDarkColorStrings,
    FilterDarkColorTeam,
    FilterNameEnds,
    FilterNameMiddle,
    FinishType,
    FirstUse,
    FloorBlue,
    FloorDetail,
    FloorGreen,
    FloorMirror,
    FloorMirrorInt,
    FloorRed,
    FontSmallThresholdHeight,
    FontSmallThresholdWidth,
    ForceTurtleMode,
    FortressCollapseSpeed,
    FortressConquestDecayRate,
    FortressConquestRate,
    FortressConquestTimeout,
    FortressDefendRate,
    FortressHeldScore,
    Friend1,
    Friend10,
    Friend2,
    Friend3,
    Friend4,
    Friend5,
    Friend6,
    Friend7,
    Friend8,
    Friend9,
    Fullscreen,
    FullscreenMessage,
    GameTimeout,
    GameType,
    GlanceBackTooltip,
    GlanceLeftTooltip,
    GlanceRightTooltip,
    GlobalId,
    GlExtensions,
    GlRenderer,
    GlVendor,
    GlVersion,
    GridSize,
    GridSizeMoviepack,
    HashMethodBlacklist,
    HelpIntroductoryBlurb,
    HideIdentity1,
    HideIdentity2,
    HideIdentity3,
    HideIdentity4,
    HighRim,
    HistorySizeChat,
    HistorySizeConsole,
    HudCacheThreshold,
    HudMaxWidth,
    IdleKickTime,
    IdleRemoveTime,
    Include,
    InfinityPlane,
    IngameMenuTooltip,
    InstantChatString1_1,
    InstantChatString1_10,
    InstantChatString1_11,
    InstantChatString1_12,
    InstantChatString1_13,
    InstantChatString1_14,
    InstantChatString1_15,
    InstantChatString1_16,
    InstantChatString1_17,
    InstantChatString1_18,
    InstantChatString1_19,
    InstantChatString1_2,
    InstantChatString1_20,
    InstantChatString1_21,
    InstantChatString1_22,
    InstantChatString1_23,
    InstantChatString1_24,
    InstantChatString1_25,
    InstantChatString1_3,
    InstantChatString1_4,
    InstantChatString1_5,
    InstantChatString1_6,
    InstantChatString1_7,
    InstantChatString1_8,
    InstantChatString1_9,
    InstantChatString2_1,
    InstantChatString2_10,
    InstantChatString2_11,
    InstantChatString2_12,
    InstantChatString2_13,
    InstantChatString2_14,
    InstantChatString2_15,
    InstantChatString2_16,
    InstantChatString2_17,
    InstantChatString2_18,
    InstantChatString2_19,
    InstantChatString2_2,
    InstantChatString2_20,
    InstantChatString2_21,
    InstantChatString2_22,
    InstantChatString2_23,
    InstantChatString2_24,
    InstantChatString2_25,
    InstantChatString2_3,
    InstantChatString2_4,
    InstantChatString2_5,
    InstantChatString2_6,
    InstantChatString2_7,
    InstantChatString2_8,
    InstantChatString2_9,
    InstantChatString3_1,
    InstantChatString3_10,
    InstantChatString3_11,
    InstantChatString3_12,
    InstantChatString3_13,
    InstantChatString3_14,
    InstantChatString3_15,
    InstantChatString3_16,
    InstantChatString3_17,
    InstantChatString3_18,
    InstantChatString3_19,
    InstantChatString3_2,
    InstantChatString3_20,
    InstantChatString3_21,
    InstantChatString3_22,
    InstantChatString3_23,
    InstantChatString3_24,
    InstantChatString3_25,
    InstantChatString3_3,
    InstantChatString3_4,
    InstantChatString3_5,
    InstantChatString3_6,
    InstantChatString3_7,
    InstantChatString3_8,
    InstantChatString3_9,
    InstantChatString4_1,
    InstantChatString4_10,
    InstantChatString4_11,
    InstantChatString4_12,
    InstantChatString4_13,
    InstantChatString4_14,
    InstantChatString4_15,
    InstantChatString4_16,
    InstantChatString4_17,
    InstantChatString4_18,
    InstantChatString4_19,
    InstantChatString4_2,
    InstantChatString4_20,
    InstantChatString4_21,
    InstantChatString4_22,
    InstantChatString4_23,
    InstantChatString4_24,
    InstantChatString4_25,
    InstantChatString4_3,
    InstantChatString4_4,
    InstantChatString4_5,
    InstantChatString4_6,
    InstantChatString4_7,
    InstantChatString4_8,
    InstantChatString4_9,
    KeepPlayerSlot,
    KeepWindowActive,
    Keyboard,
    Kick,
    KickTo,
    Kill,
    LadderlogDecorateTimestamp,
    LadderlogGameTimeInterval,
    LadderlogWriteAll,
    LadderlogWriteAuthorityBlurb,
    LadderlogWriteBasezoneConquered,
    LadderlogWriteBasezoneConquerer,
    LadderlogWriteChat,
    LadderlogWriteDeathFrag,
    LadderlogWriteDeathSuicide,
    LadderlogWriteDeathTeamkill,
    LadderlogWriteEncoding,
    LadderlogWriteGameEnd,
    LadderlogWriteGameTime,
    LadderlogWriteMatchWinner,
    LadderlogWriteNewMatch,
    LadderlogWriteNewRound,
    LadderlogWriteNumHumans,
    LadderlogWriteOnlinePlayer,
    LadderlogWritePlayerEntered,
    LadderlogWritePlayerLeft,
    LadderlogWritePlayerRenamed,
    LadderlogWritePositions,
    LadderlogWriteRoundScore,
    LadderlogWriteRoundScoreTeam,
    LadderlogWriteRoundWinner,
    LadderlogWriteSacrifice,
    LadderlogWriteTeamCreated,
    LadderlogWriteTeamDestroyed,
    LadderlogWriteTeamPlayerAdded,
    LadderlogWriteTeamPlayerRemoved,
    LadderlogWriteTeamRenamed,
    LadderlogWriteWaitForExternalScript,
    LadderGainExtra,
    LadderLoseMinOnLoad,
    LadderLosePercentOnLoad,
    LadderMinBet,
    LadderPercentBet,
    LadderTax,
    LagCredit,
    LagCreditSingle,
    LagCreditTime,
    LagCreditVariance,
    LagFastTime,
    LagFastWeight,
    LagFrequencyThreshold,
    LagMaxSpeedupTimer,
    LagOffsetClient,
    LagOffsetLegacy,
    LagOffsetServer,
    LagOMeter,
    LagOMeterBlend,
    LagOMeterScale,
    LagOMeterThreshold,
    LagOMeterUseOld,
    LagSlowTime,
    LagSlowWeight,
    LagSweetSpot,
    LagThreshold,
    LanguageFirst,
    LanguageSecond,
    LastChatBreakTime,
    LastCheckErrors,
    LastColordepth,
    LastFullscreen,
    LastZdepth,
    LegacyLogNames,
    LimitRounds,
    LimitScore,
    LimitTime,
    LocalTeam,
    LocalUser,
    LowerSky,
    MapFile,
    MapFileOverride,
    MapUri,
    MaxClients,
    MaxClientsSameIpHard,
    MaxClientsSameIpSoft,
    MaxInRate,
    MaxOutRate,
    MaxPlayersSameIp,
    MaxProtocolVersion,
    MaxVotes,
    MaxVotesPerVoter,
    Md5Prefix,
    Md5Suffix,
    MessageOfDay,
    MessageOfDayTimeout,
    MinPlayers,
    MinPlayTimeOnline,
    MinPlayTimeTeam,
    MinPlayTimeTotal,
    MinProtocolVersion,
    MinVoters,
    MouseGrab,
    MoveTo,
    Moviepack,
    MoviepackFloorBlue,
    MoviepackFloorGreen,
    MoviepackFloorRed,
    MoviepackRimWallStretchX,
    MoviepackRimWallStretchY,
    MoviepackWallStretch,
    NameTeamAfterPlayer1,
    NameTeamAfterPlayer2,
    NameTeamAfterPlayer3,
    NameTeamAfterPlayer4,
    NetworkAutobanFactor,
    NetworkAutobanMaxKph,
    NetworkAutobanOffset,
    NetworkMinBan,
    NetworkSpectatorTime,
    NewFeatureDelay,
    NewTeamAllowed,
    NumAis,
    Password,
    PasswordStorage,
    PingCharity,
    PingCharityMax,
    PingCharityMin,
    PingCharityServer,
    PingFloodGlobal,
    PingFloodTime10,
    PingFloodTime100,
    PingFloodTime20,
    PingFloodTime50,
    PingLocx,
    PingLocy,
    PingSize,
    Players,
    Player1,
    Player2,
    Player3,
    Player4,
    PlayerChatWaitFraction,
    PlayerChatWaitMax,
    PlayerChatWaitSingle,
    PlayerChatWaitTeamleader,
    PlayerListHiddenPlayerPrefix,
    PlayerMessage,
    PlayerRandomColor,
    PlayTimeOnline,
    PlayTimeTeam,
    PlayTimeTotal,
    PngScreenshot,
    PredictObjects,
    PrefixSpamEnable,
    PrefixSpamLengthMultiplier,
    PrefixSpamNumberColorCodesMultiplier,
    PrefixSpamNumberKnownPrefixesMultiplier,
    PrefixSpamRequiredScore,
    PrefixSpamStartColorMultiplier,
    PrefixSpamTimeoutMultiplier,
    ProtectSensitiveFiles,
    RealArenaSizeFactor,
    RealCycleSpeedFactor,
    RecordingDebuglevel,
    RecordTurtleMode,
    RemoveHelpTopic,
    Rename,
    ReserveScreenName,
    ResourceRepositoryClient,
    ResourceRepositoryServer,
    RimWallStretchX,
    RimWallStretchY,
    RimWallWrapY,
    Rinclude,
    RoundCenterMessage,
    RoundConsoleMessage,
    RubberGaugeLocx,
    RubberGaugeLocy,
    RubberGaugeSize,
    SavedInVersion,
    Say,
    ScoreDeathzone,
    ScoreDie,
    ScoreHole,
    ScoreKill,
    ScoreLocx,
    ScoreLocy,
    ScoreSize,
    ScoreSuicide,
    ScoreSurvive,
    ScoreWin,
    ServerDns,
    ServerIp,
    ServerName,
    ServerPort,
    SettingLegacyBehaviorAnnoying,
    SettingLegacyBehaviorBreaking,
    SettingLegacyBehaviorBumpy,
    SettingLegacyBehaviorCheating,
    SettingLegacyBehaviorVisual,
    ShowAlive,
    ShowBrake,
    ShowFastest,
    ShowFps,
    ShowHud,
    ShowOwnIp,
    ShowOwnName,
    ShowPing,
    ShowRecordingTime,
    ShowRubber,
    ShowScore,
    ShowSpeed,
    ShowTime,
    ShowTime24,
    ShuffleSpamMessagesPerRound,
    Silence,
    SilenceDefault,
    SimpleTrail,
    Sinclude,
    SizeFactor,
    SkyWobble,
    Slap,
    SmartGlanceCustom1,
    SmartGlanceCustom2,
    SmartGlanceCustom3,
    SmartGlanceCustom4,
    SmoothShading,
    SoftwareRenderer,
    SoundBufferShift,
    SoundQuality,
    SoundSources,
    SpamAutokick,
    SpamAutokickCount,
    SpamMaxlen,
    SpamMaxlenOverride,
    SpamPenalty,
    SpamProtection,
    SpamProtectionChat,
    SpamProtectionRepeat,
    SpamProtectionVote,
    Sparks,
    SpawnWingmenBack,
    SpawnWingmenSide,
    SpectatorMode1,
    SpectatorMode2,
    SpectatorMode3,
    SpectatorMode4,
    SpeedFactor,
    SpeedGaugeLocx,
    SpeedGaugeLocy,
    SpeedGaugeSize,
    SpAiIq,
    SpAutoAis,
    SpAutoIq,
    SpExplosionRadius,
    SpFinishType,
    SpGameType,
    SpLimitRounds,
    SpLimitScore,
    SpLimitTime,
    SpMinPlayers,
    SpNumAis,
    SpScoreWin,
    SpSizeFactor,
    SpSpeedFactor,
    SpTeamsMax,
    SpTeamsMin,
    SpTeamBalanceOnQuit,
    SpTeamBalanceWithAis,
    SpTeamMaxImbalance,
    SpTeamMaxPlayers,
    SpTeamMinPlayers,
    SpWallsLength,
    SpWallsStayUpDelay,
    SpWinZoneMinLastDeath,
    SpWinZoneMinRoundTime,
    StartCam1,
    StartCam2,
    StartCam3,
    StartCam4,
    StartFov1,
    StartFov2,
    StartFov3,
    StartFov4,
    StartNewMatch,
    StopRecording,
    Suspend,
    SuspendDefaultRounds,
    SwapMode,
    SwitchViewTooltip,
    TalkToMaster,
    Teams,
    TeamsMax,
    TeamsMin,
    TeamBalanceOnQuit,
    TeamBalanceWithAis,
    TeamBlue1,
    TeamBlue2,
    TeamBlue3,
    TeamBlue4,
    TeamBlue5,
    TeamBlue6,
    TeamBlue7,
    TeamBlue8,
    TeamCenterIsBoss,
    TeamEliminationMode,
    TeamGreen1,
    TeamGreen2,
    TeamGreen3,
    TeamGreen4,
    TeamGreen5,
    TeamGreen6,
    TeamGreen7,
    TeamGreen8,
    TeamMaxImbalance,
    TeamMaxPlayers,
    TeamMinPlayers,
    TeamName1,
    TeamName2,
    TeamName3,
    TeamName4,
    TeamName5,
    TeamName6,
    TeamName7,
    TeamName8,
    TeamRed1,
    TeamRed2,
    TeamRed3,
    TeamRed4,
    TeamRed5,
    TeamRed6,
    TeamRed7,
    TeamRed8,
    TexturesHi,
    TextureMode0,
    TextureMode1,
    TextureMode2,
    TextureMode3,
    TextOut,
    TimebotActionHigh,
    TimebotActionMax,
    TimebotActionMedium,
    TimebotKickSeverity,
    TimebotSensitivity,
    TitleOfDay,
    ToggleSpectatorTooltip,
    TopologyPolice,
    TopologyPoliceParallel,
    TrustLan,
    UnbanIp,
    UnbanUser,
    UnlockAllTeams,
    Unsilence,
    Unsuspend,
    UpperSky,
    Url,
    User1,
    User2,
    User3,
    User4,
    UserAlias,
    UserLevel,
    UserRemove,
    UseDisplaylists,
    ViewportConf,
    ViewportToPlayer1,
    ViewportToPlayer2,
    ViewportToPlayer3,
    ViewportToPlayer4,
    Voice,
    VotesCancel,
    VotesSuspend,
    VotesSuspendDefault,
    VotesUnsuspend,
    VoteKickReason,
    VoteKickToPort,
    VoteKickToServer,
    VoteUseServerControlledKick,
    VotingBias,
    VotingBiasCommand,
    VotingBiasInclude,
    VotingBiasKick,
    VotingBiasSilence,
    VotingBiasSuspend,
    VotingBiasVoice,
    VotingDecay,
    VotingHarmTime,
    VotingKickMinharm,
    VotingKickTime,
    VotingMaturity,
    VotingPrivacy,
    VotingSpamIssue,
    VotingSpamReject,
    VotingStartDecay,
    VotingSuspendRounds,
    VotingTimeout,
    VotingTimeoutPerVoter,
    WaitForExternalScript,
    WaitForExternalScriptTimeout,
    WallsLength,
    WallsStayUpDelay,
    WhitelistEnemiesIp,
    WhitelistEnemiesUsername,
    WhiteSparks,
    WinZoneDeaths,
    WinZoneExpansion,
    WinZoneInitialSize,
    WinZoneMinLastDeath,
    WinZoneMinRoundTime,
    WinZoneRandomness,
    WordDelimiters,
    WrapMenu,
    Zdepth,
    ZoneAlpha,
    ZoneAlphaServer,
    ZoneAlphaToggle,
    ZoneBottom,
    ZoneHeight,
    ZoneSegments,
    ZoneSegLength,
}

impl Display for Command {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let word = match self {
            Command::AccessLevel => "ACCESS_LEVEL",
            Command::AccessLevelAnnounceLogin => "ACCESS_LEVEL_ANNOUNCE_LOGIN",
            Command::AccessLevelAutokickImmunity => "ACCESS_LEVEL_AUTOKICK_IMMUNITY",
            Command::AccessLevelChat => "ACCESS_LEVEL_CHAT",
            Command::AccessLevelChatTimeout => "ACCESS_LEVEL_CHAT_TIMEOUT",
            Command::AccessLevelHideOf => "ACCESS_LEVEL_HIDE_OF",
            Command::AccessLevelHideTo => "ACCESS_LEVEL_HIDE_TO",
            Command::AccessLevelIps => "ACCESS_LEVEL_IPS",
            Command::AccessLevelListAdmins => "ACCESS_LEVEL_LIST_ADMINS",
            Command::AccessLevelListAdminsSeeEveryone => "ACCESS_LEVEL_LIST_ADMINS_SEE_EVERYONE",
            Command::AccessLevelNver => "ACCESS_LEVEL_NVER",
            Command::AccessLevelPlay => "ACCESS_LEVEL_PLAY",
            Command::AccessLevelPlaySliders => "ACCESS_LEVEL_PLAY_SLIDERS",
            Command::AccessLevelPlaySliding => "ACCESS_LEVEL_PLAY_SLIDING",
            Command::AccessLevelRtfm => "ACCESS_LEVEL_RTFM",
            Command::AccessLevelShout => "ACCESS_LEVEL_SHOUT",
            Command::AccessLevelShuffleUp => "ACCESS_LEVEL_SHUFFLE_UP",
            Command::AccessLevelSpyMsg => "ACCESS_LEVEL_SPY_MSG",
            Command::AccessLevelSpyTeam => "ACCESS_LEVEL_SPY_TEAM",
            Command::AccessLevelVoteCommand => "ACCESS_LEVEL_VOTE_COMMAND",
            Command::AccessLevelVoteCommandExecute => "ACCESS_LEVEL_VOTE_COMMAND_EXECUTE",
            Command::AccessLevelVoteInclude => "ACCESS_LEVEL_VOTE_INCLUDE",
            Command::AccessLevelVoteIncludeExecute => "ACCESS_LEVEL_VOTE_INCLUDE_EXECUTE",
            Command::AccessLevelVoteKick => "ACCESS_LEVEL_VOTE_KICK",
            Command::AccessLevelVoteSilence => "ACCESS_LEVEL_VOTE_SILENCE",
            Command::AccessLevelVoteSuspend => "ACCESS_LEVEL_VOTE_SUSPEND",
            Command::AddHelpTopic => "ADD_HELP_TOPIC",
            Command::AddMasterServer => "ADD_MASTER_SERVER",
            Command::Admins => "ADMINS",
            Command::AdminListColorsBestBlue => "ADMIN_LIST_COLORS_BEST_BLUE",
            Command::AdminListColorsBestGreen => "ADMIN_LIST_COLORS_BEST_GREEN",
            Command::AdminListColorsBestRed => "ADMIN_LIST_COLORS_BEST_RED",
            Command::AdminListColorsWorstBlue => "ADMIN_LIST_COLORS_WORST_BLUE",
            Command::AdminListColorsWorstGreen => "ADMIN_LIST_COLORS_WORST_GREEN",
            Command::AdminListColorsWorstRed => "ADMIN_LIST_COLORS_WORST_RED",
            Command::AdminListMinAccessLevel => "ADMIN_LIST_MIN_ACCESS_LEVEL",
            Command::AiIq => "AI_IQ",
            Command::AliveLocx => "ALIVE_LOCX",
            Command::AliveLocy => "ALIVE_LOCY",
            Command::AliveSize => "ALIVE_SIZE",
            Command::AllowCam1_0 => "ALLOW_CAM_1_0",
            Command::AllowCam1_1 => "ALLOW_CAM_1_1",
            Command::AllowCam1_2 => "ALLOW_CAM_1_2",
            Command::AllowCam1_3 => "ALLOW_CAM_1_3",
            Command::AllowCam1_4 => "ALLOW_CAM_1_4",
            Command::AllowCam1_5 => "ALLOW_CAM_1_5",
            Command::AllowCam1_6 => "ALLOW_CAM_1_6",
            Command::AllowCam2_0 => "ALLOW_CAM_2_0",
            Command::AllowCam2_1 => "ALLOW_CAM_2_1",
            Command::AllowCam2_2 => "ALLOW_CAM_2_2",
            Command::AllowCam2_3 => "ALLOW_CAM_2_3",
            Command::AllowCam2_4 => "ALLOW_CAM_2_4",
            Command::AllowCam2_5 => "ALLOW_CAM_2_5",
            Command::AllowCam2_6 => "ALLOW_CAM_2_6",
            Command::AllowCam3_0 => "ALLOW_CAM_3_0",
            Command::AllowCam3_1 => "ALLOW_CAM_3_1",
            Command::AllowCam3_2 => "ALLOW_CAM_3_2",
            Command::AllowCam3_3 => "ALLOW_CAM_3_3",
            Command::AllowCam3_4 => "ALLOW_CAM_3_4",
            Command::AllowCam3_5 => "ALLOW_CAM_3_5",
            Command::AllowCam3_6 => "ALLOW_CAM_3_6",
            Command::AllowCam4_0 => "ALLOW_CAM_4_0",
            Command::AllowCam4_1 => "ALLOW_CAM_4_1",
            Command::AllowCam4_2 => "ALLOW_CAM_4_2",
            Command::AllowCam4_3 => "ALLOW_CAM_4_3",
            Command::AllowCam4_4 => "ALLOW_CAM_4_4",
            Command::AllowCam4_5 => "ALLOW_CAM_4_5",
            Command::AllowCam4_6 => "ALLOW_CAM_4_6",
            Command::AllowControlDuringChat => "ALLOW_CONTROL_DURING_CHAT",
            Command::AllowEnemiesSameClient => "ALLOW_ENEMIES_SAME_CLIENT",
            Command::AllowEnemiesSameIp => "ALLOW_ENEMIES_SAME_IP",
            Command::AllowImposters => "ALLOW_IMPOSTERS",
            Command::AllowImpostors => "ALLOW_IMPOSTORS",
            Command::AllowRenamePlayer => "ALLOW_RENAME_PLAYER",
            Command::AllowTeamChange => "ALLOW_TEAM_CHANGE",
            Command::AllowTeamChangePlayer => "ALLOW_TEAM_CHANGE_PLAYER",
            Command::AllowTeamNameColor => "ALLOW_TEAM_NAME_COLOR",
            Command::AllowTeamNamePlayer => "ALLOW_TEAM_NAME_PLAYER",
            Command::AllowVoting => "ALLOW_VOTING",
            Command::AllowVotingSpectator => "ALLOW_VOTING_SPECTATOR",
            Command::AlphaBlend => "ALPHA_BLEND",
            Command::AntiSpoof => "ANTI_SPOOF",
            Command::ArenaAxes => "ARENA_AXES",
            Command::ArenaAxesOverride => "ARENA_AXES_OVERRIDE",
            Command::ArmagetronLastScreenmode => "ARMAGETRON_LAST_SCREENMODE",
            Command::ArmagetronLastWindowsize => "ARMAGETRON_LAST_WINDOWSIZE",
            Command::ArmagetronScreenmode => "ARMAGETRON_SCREENMODE",
            Command::ArmagetronVsync => "ARMAGETRON_VSYNC",
            Command::ArmagetronVsyncLast => "ARMAGETRON_VSYNC_LAST",
            Command::ArmagetronWindowsize => "ARMAGETRON_WINDOWSIZE",
            Command::AuthorityBlacklist => "AUTHORITY_BLACKLIST",
            Command::AuthorityLevel => "AUTHORITY_LEVEL",
            Command::AuthorityWhitelist => "AUTHORITY_WHITELIST",
            Command::AutoAis => "AUTO_AIS",
            Command::AutoIncam1 => "AUTO_INCAM_1",
            Command::AutoIncam2 => "AUTO_INCAM_2",
            Command::AutoIncam3 => "AUTO_INCAM_3",
            Command::AutoIncam4 => "AUTO_INCAM_4",
            Command::AutoIq => "AUTO_IQ",
            Command::AutoLogin1 => "AUTO_LOGIN_1",
            Command::AutoLogin2 => "AUTO_LOGIN_2",
            Command::AutoLogin3 => "AUTO_LOGIN_3",
            Command::AutoLogin4 => "AUTO_LOGIN_4",
            Command::AutoTeam => "AUTO_TEAM",
            Command::AutoTeamSpecSpam => "AUTO_TEAM_SPEC_SPAM",
            Command::AxesIndicator => "AXES_INDICATOR",
            Command::BackwardCompatibility => "BACKWARD_COMPATIBILITY",
            Command::Ban => "BAN",
            Command::BanIp => "BAN_IP",
            Command::BanList => "BAN_LIST",
            Command::BanUser => "BAN_USER",
            Command::BanUserList => "BAN_USER_LIST",
            Command::BigBrother => "BIG_BROTHER",
            Command::Bookmark0Address => "BOOKMARK_0_ADDRESS",
            Command::Bookmark0Name => "BOOKMARK_0_NAME",
            Command::Bookmark0Port => "BOOKMARK_0_PORT",
            Command::Bookmark10Address => "BOOKMARK_10_ADDRESS",
            Command::Bookmark10Name => "BOOKMARK_10_NAME",
            Command::Bookmark10Port => "BOOKMARK_10_PORT",
            Command::Bookmark1Address => "BOOKMARK_1_ADDRESS",
            Command::Bookmark1Name => "BOOKMARK_1_NAME",
            Command::Bookmark1Port => "BOOKMARK_1_PORT",
            Command::Bookmark2Address => "BOOKMARK_2_ADDRESS",
            Command::Bookmark2Name => "BOOKMARK_2_NAME",
            Command::Bookmark2Port => "BOOKMARK_2_PORT",
            Command::Bookmark3Address => "BOOKMARK_3_ADDRESS",
            Command::Bookmark3Name => "BOOKMARK_3_NAME",
            Command::Bookmark3Port => "BOOKMARK_3_PORT",
            Command::Bookmark4Address => "BOOKMARK_4_ADDRESS",
            Command::Bookmark4Name => "BOOKMARK_4_NAME",
            Command::Bookmark4Port => "BOOKMARK_4_PORT",
            Command::Bookmark5Address => "BOOKMARK_5_ADDRESS",
            Command::Bookmark5Name => "BOOKMARK_5_NAME",
            Command::Bookmark5Port => "BOOKMARK_5_PORT",
            Command::Bookmark6Address => "BOOKMARK_6_ADDRESS",
            Command::Bookmark6Name => "BOOKMARK_6_NAME",
            Command::Bookmark6Port => "BOOKMARK_6_PORT",
            Command::Bookmark7Address => "BOOKMARK_7_ADDRESS",
            Command::Bookmark7Name => "BOOKMARK_7_NAME",
            Command::Bookmark7Port => "BOOKMARK_7_PORT",
            Command::Bookmark8Address => "BOOKMARK_8_ADDRESS",
            Command::Bookmark8Name => "BOOKMARK_8_NAME",
            Command::Bookmark8Port => "BOOKMARK_8_PORT",
            Command::Bookmark9Address => "BOOKMARK_9_ADDRESS",
            Command::Bookmark9Name => "BOOKMARK_9_NAME",
            Command::Bookmark9Port => "BOOKMARK_9_PORT",
            Command::BookmarkMaster0Address => "BOOKMARK__MASTER0_ADDRESS",
            Command::BookmarkMaster0Name => "BOOKMARK__MASTER0_NAME",
            Command::BookmarkMaster0Port => "BOOKMARK__MASTER0_PORT",
            Command::BookmarkMaster10Address => "BOOKMARK__MASTER10_ADDRESS",
            Command::BookmarkMaster10Name => "BOOKMARK__MASTER10_NAME",
            Command::BookmarkMaster10Port => "BOOKMARK__MASTER10_PORT",
            Command::BookmarkMaster1Address => "BOOKMARK__MASTER1_ADDRESS",
            Command::BookmarkMaster1Name => "BOOKMARK__MASTER1_NAME",
            Command::BookmarkMaster1Port => "BOOKMARK__MASTER1_PORT",
            Command::BookmarkMaster2Address => "BOOKMARK__MASTER2_ADDRESS",
            Command::BookmarkMaster2Name => "BOOKMARK__MASTER2_NAME",
            Command::BookmarkMaster2Port => "BOOKMARK__MASTER2_PORT",
            Command::BookmarkMaster3Address => "BOOKMARK__MASTER3_ADDRESS",
            Command::BookmarkMaster3Name => "BOOKMARK__MASTER3_NAME",
            Command::BookmarkMaster3Port => "BOOKMARK__MASTER3_PORT",
            Command::BookmarkMaster4Address => "BOOKMARK__MASTER4_ADDRESS",
            Command::BookmarkMaster4Name => "BOOKMARK__MASTER4_NAME",
            Command::BookmarkMaster4Port => "BOOKMARK__MASTER4_PORT",
            Command::BookmarkMaster5Address => "BOOKMARK__MASTER5_ADDRESS",
            Command::BookmarkMaster5Name => "BOOKMARK__MASTER5_NAME",
            Command::BookmarkMaster5Port => "BOOKMARK__MASTER5_PORT",
            Command::BookmarkMaster6Address => "BOOKMARK__MASTER6_ADDRESS",
            Command::BookmarkMaster6Name => "BOOKMARK__MASTER6_NAME",
            Command::BookmarkMaster6Port => "BOOKMARK__MASTER6_PORT",
            Command::BookmarkMaster7Address => "BOOKMARK__MASTER7_ADDRESS",
            Command::BookmarkMaster7Name => "BOOKMARK__MASTER7_NAME",
            Command::BookmarkMaster7Port => "BOOKMARK__MASTER7_PORT",
            Command::BookmarkMaster8Address => "BOOKMARK__MASTER8_ADDRESS",
            Command::BookmarkMaster8Name => "BOOKMARK__MASTER8_NAME",
            Command::BookmarkMaster8Port => "BOOKMARK__MASTER8_PORT",
            Command::BookmarkMaster9Address => "BOOKMARK__MASTER9_ADDRESS",
            Command::BookmarkMaster9Name => "BOOKMARK__MASTER9_NAME",
            Command::BookmarkMaster9Port => "BOOKMARK__MASTER9_PORT",
            Command::BrakeGaugeLocx => "BRAKE_GAUGE_LOCX",
            Command::BrakeGaugeLocy => "BRAKE_GAUGE_LOCY",
            Command::BrakeGaugeSize => "BRAKE_GAUGE_SIZE",
            Command::BugColorOverflow => "BUG_COLOR_OVERFLOW",
            Command::BugRip => "BUG_RIP",
            Command::BugTransparency => "BUG_TRANSPARENCY",
            Command::BugTransparencyDemand => "BUG_TRANSPARENCY_DEMAND",
            Command::BugTunnel => "BUG_TUNNEL",
            Command::Camcenter1 => "CAMCENTER_1",
            Command::Camcenter2 => "CAMCENTER_2",
            Command::Camcenter3 => "CAMCENTER_3",
            Command::Camcenter4 => "CAMCENTER_4",
            Command::CameraCustomBack => "CAMERA_CUSTOM_BACK",
            Command::CameraCustomBackFromspeed => "CAMERA_CUSTOM_BACK_FROMSPEED",
            Command::CameraCustomPitch => "CAMERA_CUSTOM_PITCH",
            Command::CameraCustomRise => "CAMERA_CUSTOM_RISE",
            Command::CameraCustomRiseFromspeed => "CAMERA_CUSTOM_RISE_FROMSPEED",
            Command::CameraCustomTurnSpeed => "CAMERA_CUSTOM_TURN_SPEED",
            Command::CameraCustomTurnSpeed180 => "CAMERA_CUSTOM_TURN_SPEED_180",
            Command::CameraCustomZoom => "CAMERA_CUSTOM_ZOOM",
            Command::CameraFollowStartX => "CAMERA_FOLLOW_START_X",
            Command::CameraFollowStartY => "CAMERA_FOLLOW_START_Y",
            Command::CameraFollowStartZ => "CAMERA_FOLLOW_START_Z",
            Command::CameraForbidCustom => "CAMERA_FORBID_CUSTOM",
            Command::CameraForbidCustomGlance => "CAMERA_FORBID_CUSTOM_GLANCE",
            Command::CameraForbidFollow => "CAMERA_FORBID_FOLLOW",
            Command::CameraForbidFree => "CAMERA_FORBID_FREE",
            Command::CameraForbidIn => "CAMERA_FORBID_IN",
            Command::CameraForbidServerCustom => "CAMERA_FORBID_SERVER_CUSTOM",
            Command::CameraForbidSmart => "CAMERA_FORBID_SMART",
            Command::CameraFreeStartX => "CAMERA_FREE_START_X",
            Command::CameraFreeStartY => "CAMERA_FREE_START_Y",
            Command::CameraFreeStartZ => "CAMERA_FREE_START_Z",
            Command::CameraGlanceBack => "CAMERA_GLANCE_BACK",
            Command::CameraGlanceBackFromspeed => "CAMERA_GLANCE_BACK_FROMSPEED",
            Command::CameraGlancePitch => "CAMERA_GLANCE_PITCH",
            Command::CameraGlanceRise => "CAMERA_GLANCE_RISE",
            Command::CameraGlanceRiseFromspeed => "CAMERA_GLANCE_RISE_FROMSPEED",
            Command::CameraInTurnSpeed => "CAMERA_IN_TURN_SPEED",
            Command::CameraOverrideCustomGlance => "CAMERA_OVERRIDE_CUSTOM_GLANCE",
            Command::CameraOverrideCustomGlanceServerCustom => {
                "CAMERA_OVERRIDE_CUSTOM_GLANCE_SERVER_CUSTOM"
            }
            Command::CameraServerCustomBack => "CAMERA_SERVER_CUSTOM_BACK",
            Command::CameraServerCustomBackFromspeed => "CAMERA_SERVER_CUSTOM_BACK_FROMSPEED",
            Command::CameraServerCustomPitch => "CAMERA_SERVER_CUSTOM_PITCH",
            Command::CameraServerCustomRise => "CAMERA_SERVER_CUSTOM_RISE",
            Command::CameraServerCustomRiseFromspeed => "CAMERA_SERVER_CUSTOM_RISE_FROMSPEED",
            Command::CameraServerCustomTurnSpeed => "CAMERA_SERVER_CUSTOM_TURN_SPEED",
            Command::CameraServerCustomTurnSpeed180 => "CAMERA_SERVER_CUSTOM_TURN_SPEED_180",
            Command::CameraServerGlanceBack => "CAMERA_SERVER_GLANCE_BACK",
            Command::CameraServerGlanceBackFromspeed => "CAMERA_SERVER_GLANCE_BACK_FROMSPEED",
            Command::CameraServerGlancePitch => "CAMERA_SERVER_GLANCE_PITCH",
            Command::CameraServerGlanceRise => "CAMERA_SERVER_GLANCE_RISE",
            Command::CameraServerGlanceRiseFromspeed => "CAMERA_SERVER_GLANCE_RISE_FROMSPEED",
            Command::CameraSmartStartX => "CAMERA_SMART_START_X",
            Command::CameraSmartStartY => "CAMERA_SMART_START_Y",
            Command::CameraSmartStartZ => "CAMERA_SMART_START_Z",
            Command::CameraVisibilityClipSpeed => "CAMERA_VISIBILITY_CLIP_SPEED",
            Command::CameraVisibilityExtension => "CAMERA_VISIBILITY_EXTENSION",
            Command::CameraVisibilityLowerWall => "CAMERA_VISIBILITY_LOWER_WALL",
            Command::CameraVisibilityLowerWallSmart => "CAMERA_VISIBILITY_LOWER_WALL_SMART",
            Command::CameraVisibilityRecoverySpeed => "CAMERA_VISIBILITY_RECOVERY_SPEED",
            Command::CameraVisibilitySideskew => "CAMERA_VISIBILITY_SIDESKEW",
            Command::CameraVisibilityWallDistance => "CAMERA_VISIBILITY_WALL_DISTANCE",
            Command::Camwobble1 => "CAMWOBBLE_1",
            Command::Camwobble2 => "CAMWOBBLE_2",
            Command::Camwobble3 => "CAMWOBBLE_3",
            Command::Camwobble4 => "CAMWOBBLE_4",
            Command::Casacl => "CASACL",
            Command::CenterMessage => "CENTER_MESSAGE",
            Command::ChatbotAlwaysActive => "CHATBOT_ALWAYS_ACTIVE",
            Command::ChatbotDecay => "CHATBOT_DECAY",
            Command::ChatbotDelay => "CHATBOT_DELAY",
            Command::ChatbotMinTimestep => "CHATBOT_MIN_TIMESTEP",
            Command::ChatbotNewWallBlindness => "CHATBOT_NEW_WALL_BLINDNESS",
            Command::ChatbotRange => "CHATBOT_RANGE",
            Command::ChatterRemoveTime => "CHATTER_REMOVE_TIME",
            Command::ChatLog => "CHAT_LOG",
            Command::ChatTooltip => "CHAT_TOOLTIP",
            Command::CheckErrors => "CHECK_ERRORS",
            Command::ClientPort => "CLIENT_PORT",
            Command::CmLocy => "CM_LOCY",
            Command::Colordepth => "COLORDEPTH",
            Command::ColorB1 => "COLOR_B_1",
            Command::ColorB2 => "COLOR_B_2",
            Command::ColorB3 => "COLOR_B_3",
            Command::ColorB4 => "COLOR_B_4",
            Command::ColorG1 => "COLOR_G_1",
            Command::ColorG2 => "COLOR_G_2",
            Command::ColorG3 => "COLOR_G_3",
            Command::ColorG4 => "COLOR_G_4",
            Command::ColorR1 => "COLOR_R_1",
            Command::ColorR2 => "COLOR_R_2",
            Command::ColorR3 => "COLOR_R_3",
            Command::ColorR4 => "COLOR_R_4",
            Command::ColorStrings => "COLOR_STRINGS",
            Command::ConnectionFloodSensitivity => "CONNECTION_FLOOD_SENSITIVITY",
            Command::ConnectionLimit => "CONNECTION_LIMIT",
            Command::ConsoleColumns => "CONSOLE_COLUMNS",
            Command::ConsoleIndent => "CONSOLE_INDENT",
            Command::ConsoleLadderLog => "CONSOLE_LADDER_LOG",
            Command::ConsoleLog => "CONSOLE_LOG",
            Command::ConsoleMessage => "CONSOLE_MESSAGE",
            Command::ConsoleRows => "CONSOLE_ROWS",
            Command::ConsoleRowsMax => "CONSOLE_ROWS_MAX",
            Command::CustomScreenAspect => "CUSTOM_SCREEN_ASPECT",
            Command::CustomScreenHeight => "CUSTOM_SCREEN_HEIGHT",
            Command::CustomScreenWidth => "CUSTOM_SCREEN_WIDTH",
            Command::CustomServerName => "CUSTOM_SERVER_NAME",
            Command::CycleAccel => "CYCLE_ACCEL",
            Command::CycleAccelEnemy => "CYCLE_ACCEL_ENEMY",
            Command::CycleAccelEnemyOverride => "CYCLE_ACCEL_ENEMY_OVERRIDE",
            Command::CycleAccelOffset => "CYCLE_ACCEL_OFFSET",
            Command::CycleAccelRim => "CYCLE_ACCEL_RIM",
            Command::CycleAccelRimOverride => "CYCLE_ACCEL_RIM_OVERRIDE",
            Command::CycleAccelSelf => "CYCLE_ACCEL_SELF",
            Command::CycleAccelSelfOverride => "CYCLE_ACCEL_SELF_OVERRIDE",
            Command::CycleAccelSlingshot => "CYCLE_ACCEL_SLINGSHOT",
            Command::CycleAccelSlingshotOverride => "CYCLE_ACCEL_SLINGSHOT_OVERRIDE",
            Command::CycleAccelTeam => "CYCLE_ACCEL_TEAM",
            Command::CycleAccelTeamOverride => "CYCLE_ACCEL_TEAM_OVERRIDE",
            Command::CycleAccelTunnel => "CYCLE_ACCEL_TUNNEL",
            Command::CycleAccelTunnelOverride => "CYCLE_ACCEL_TUNNEL_OVERRIDE",
            Command::CycleAvoidOldclientBadSync => "CYCLE_AVOID_OLDCLIENT_BAD_SYNC",
            Command::CycleBlinkFrequency => "CYCLE_BLINK_FREQUENCY",
            Command::CycleBoostfactorEnemy => "CYCLE_BOOSTFACTOR_ENEMY",
            Command::CycleBoostfactorEnemyOverride => "CYCLE_BOOSTFACTOR_ENEMY_OVERRIDE",
            Command::CycleBoostfactorRim => "CYCLE_BOOSTFACTOR_RIM",
            Command::CycleBoostfactorRimOverride => "CYCLE_BOOSTFACTOR_RIM_OVERRIDE",
            Command::CycleBoostfactorSelf => "CYCLE_BOOSTFACTOR_SELF",
            Command::CycleBoostfactorSelfOverride => "CYCLE_BOOSTFACTOR_SELF_OVERRIDE",
            Command::CycleBoostfactorTeam => "CYCLE_BOOSTFACTOR_TEAM",
            Command::CycleBoostfactorTeamOverride => "CYCLE_BOOSTFACTOR_TEAM_OVERRIDE",
            Command::CycleBoostEnemy => "CYCLE_BOOST_ENEMY",
            Command::CycleBoostEnemyOverride => "CYCLE_BOOST_ENEMY_OVERRIDE",
            Command::CycleBoostRim => "CYCLE_BOOST_RIM",
            Command::CycleBoostRimOverride => "CYCLE_BOOST_RIM_OVERRIDE",
            Command::CycleBoostSelf => "CYCLE_BOOST_SELF",
            Command::CycleBoostSelfOverride => "CYCLE_BOOST_SELF_OVERRIDE",
            Command::CycleBoostTeam => "CYCLE_BOOST_TEAM",
            Command::CycleBoostTeamOverride => "CYCLE_BOOST_TEAM_OVERRIDE",
            Command::CycleBrake => "CYCLE_BRAKE",
            Command::CycleBrakeDeplete => "CYCLE_BRAKE_DEPLETE",
            Command::CycleBrakeDepleteOverride => "CYCLE_BRAKE_DEPLETE_OVERRIDE",
            Command::CycleBrakeRefill => "CYCLE_BRAKE_REFILL",
            Command::CycleBrakeRefillOverride => "CYCLE_BRAKE_REFILL_OVERRIDE",
            Command::CycleBrakeTooltip => "CYCLE_BRAKE_TOOLTIP",
            Command::CycleDelay => "CYCLE_DELAY",
            Command::CycleDelayDoublebindBonus => "CYCLE_DELAY_DOUBLEBIND_BONUS",
            Command::CycleDelayDoublebindBonusOverride => "CYCLE_DELAY_DOUBLEBIND_BONUS_OVERRIDE",
            Command::CycleDelayTimebased => "CYCLE_DELAY_TIMEBASED",
            Command::CycleDelayTimebasedOverride => "CYCLE_DELAY_TIMEBASED_OVERRIDE",
            Command::CycleDistWallShrink => "CYCLE_DIST_WALL_SHRINK",
            Command::CycleDistWallShrinkOffset => "CYCLE_DIST_WALL_SHRINK_OFFSET",
            Command::CycleFairAntilag => "CYCLE_FAIR_ANTILAG",
            Command::CycleFirstSpawnProtection => "CYCLE_FIRST_SPAWN_PROTECTION",
            Command::CycleInvulnerableTime => "CYCLE_INVULNERABLE_TIME",
            Command::CycleMaxRefcount => "CYCLE_MAX_REFCOUNT",
            Command::CyclePacketlossTolerance => "CYCLE_PACKETLOSS_TOLERANCE",
            Command::CyclePingRubber => "CYCLE_PING_RUBBER",
            Command::CycleRubber => "CYCLE_RUBBER",
            Command::CycleRubberDelay => "CYCLE_RUBBER_DELAY",
            Command::CycleRubberDelayBonus => "CYCLE_RUBBER_DELAY_BONUS",
            Command::CycleRubberDelayBonusOverride => "CYCLE_RUBBER_DELAY_BONUS_OVERRIDE",
            Command::CycleRubberDelayOverride => "CYCLE_RUBBER_DELAY_OVERRIDE",
            Command::CycleRubberLegacy => "CYCLE_RUBBER_LEGACY",
            Command::CycleRubberMalusTurnOverride => "CYCLE_RUBBER_MALUS_TURN_OVERRIDE",
            Command::CycleRubberMinadjust => "CYCLE_RUBBER_MINADJUST",
            Command::CycleRubberMinadjustOverride => "CYCLE_RUBBER_MINADJUST_OVERRIDE",
            Command::CycleRubberMindistance => "CYCLE_RUBBER_MINDISTANCE",
            Command::CycleRubberMindistanceGap => "CYCLE_RUBBER_MINDISTANCE_GAP",
            Command::CycleRubberMindistanceGapBackdoor => "CYCLE_RUBBER_MINDISTANCE_GAP_BACKDOOR",
            Command::CycleRubberMindistanceGapBackdoorOverride => {
                "CYCLE_RUBBER_MINDISTANCE_GAP_BACKDOOR_OVERRIDE"
            }
            Command::CycleRubberMindistanceGapOverride => "CYCLE_RUBBER_MINDISTANCE_GAP_OVERRIDE",
            Command::CycleRubberMindistanceGapSide => "CYCLE_RUBBER_MINDISTANCE_GAP_SIDE",
            Command::CycleRubberMindistanceLegacy => "CYCLE_RUBBER_MINDISTANCE_LEGACY",
            Command::CycleRubberMindistanceOverride => "CYCLE_RUBBER_MINDISTANCE_OVERRIDE",
            Command::CycleRubberMindistancePreparation => "CYCLE_RUBBER_MINDISTANCE_PREPARATION",
            Command::CycleRubberMindistancePreparationOverride => {
                "CYCLE_RUBBER_MINDISTANCE_PREPARATION_OVERRIDE"
            }
            Command::CycleRubberMindistanceRatio => "CYCLE_RUBBER_MINDISTANCE_RATIO",
            Command::CycleRubberMindistanceRatioOverride => {
                "CYCLE_RUBBER_MINDISTANCE_RATIO_OVERRIDE"
            }
            Command::CycleRubberMindistanceReservoir => "CYCLE_RUBBER_MINDISTANCE_RESERVOIR",
            Command::CycleRubberMindistanceReservoirOverride => {
                "CYCLE_RUBBER_MINDISTANCE_RESERVOIR_OVERRIDE"
            }
            Command::CycleRubberMindistanceUnprepared => "CYCLE_RUBBER_MINDISTANCE_UNPREPARED",
            Command::CycleRubberMindistanceUnpreparedOverride => {
                "CYCLE_RUBBER_MINDISTANCE_UNPREPARED_OVERRIDE"
            }
            Command::CycleRubberSpeed => "CYCLE_RUBBER_SPEED",
            Command::CycleRubberSpeedOverride => "CYCLE_RUBBER_SPEED_OVERRIDE",
            Command::CycleRubberTime => "CYCLE_RUBBER_TIME",
            Command::CycleRubberTimebased => "CYCLE_RUBBER_TIMEBASED",
            Command::CycleRubberTimebasedOverride => "CYCLE_RUBBER_TIMEBASED_OVERRIDE",
            Command::CycleRubberTimeOverride => "CYCLE_RUBBER_TIME_OVERRIDE",
            Command::CycleRubberWallShrink => "CYCLE_RUBBER_WALL_SHRINK",
            Command::CycleRubberWallShrinkOverride => "CYCLE_RUBBER_WALL_SHRINK_OVERRIDE",
            Command::CycleSmoothMinSpeed => "CYCLE_SMOOTH_MIN_SPEED",
            Command::CycleSmoothThreshold => "CYCLE_SMOOTH_THRESHOLD",
            Command::CycleSmoothTime => "CYCLE_SMOOTH_TIME",
            Command::CycleSoundSpeed => "CYCLE_SOUND_SPEED",
            Command::CycleSpeed => "CYCLE_SPEED",
            Command::CycleSpeedDecayAbove => "CYCLE_SPEED_DECAY_ABOVE",
            Command::CycleSpeedDecayAboveOverride => "CYCLE_SPEED_DECAY_ABOVE_OVERRIDE",
            Command::CycleSpeedDecayBelow => "CYCLE_SPEED_DECAY_BELOW",
            Command::CycleSpeedDecayBelowOverride => "CYCLE_SPEED_DECAY_BELOW_OVERRIDE",
            Command::CycleSpeedMax => "CYCLE_SPEED_MAX",
            Command::CycleSpeedMaxOverride => "CYCLE_SPEED_MAX_OVERRIDE",
            Command::CycleSpeedMin => "CYCLE_SPEED_MIN",
            Command::CycleSpeedMinOverride => "CYCLE_SPEED_MIN_OVERRIDE",
            Command::CycleStartSpeed => "CYCLE_START_SPEED",
            Command::CycleSyncFf => "CYCLE_SYNC_FF",
            Command::CycleSyncFfSteps => "CYCLE_SYNC_FF_STEPS",
            Command::CycleSyncIntervalEnemy => "CYCLE_SYNC_INTERVAL_ENEMY",
            Command::CycleSyncIntervalSelf => "CYCLE_SYNC_INTERVAL_SELF",
            Command::CycleTimeTolerance => "CYCLE_TIME_TOLERANCE",
            Command::CycleTimeToleranceOverride => "CYCLE_TIME_TOLERANCE_OVERRIDE",
            Command::CycleTurnLeftTooltip => "CYCLE_TURN_LEFT_TOOLTIP",
            Command::CycleTurnMemory => "CYCLE_TURN_MEMORY",
            Command::CycleTurnRightTooltip => "CYCLE_TURN_RIGHT_TOOLTIP",
            Command::CycleTurnSpeedFactor => "CYCLE_TURN_SPEED_FACTOR",
            Command::CycleTurnSpeedFactorOverride => "CYCLE_TURN_SPEED_FACTOR_OVERRIDE",
            Command::CycleWallNear => "CYCLE_WALL_NEAR",
            Command::CycleWallTime => "CYCLE_WALL_TIME",
            Command::CycleWidth => "CYCLE_WIDTH",
            Command::CycleWidthOverride => "CYCLE_WIDTH_OVERRIDE",
            Command::CycleWidthRubberMax => "CYCLE_WIDTH_RUBBER_MAX",
            Command::CycleWidthRubberMaxOverride => "CYCLE_WIDTH_RUBBER_MAX_OVERRIDE",
            Command::CycleWidthRubberMin => "CYCLE_WIDTH_RUBBER_MIN",
            Command::CycleWidthRubberMinOverride => "CYCLE_WIDTH_RUBBER_MIN_OVERRIDE",
            Command::CycleWidthSide => "CYCLE_WIDTH_SIDE",
            Command::CycleWidthSideOverride => "CYCLE_WIDTH_SIDE_OVERRIDE",
            Command::DeclareRoundWinner => "DECLARE_ROUND_WINNER",
            Command::DedicatedIdle => "DEDICATED_IDLE",
            Command::DefaultKickReason => "DEFAULT_KICK_REASON",
            Command::DefaultKickToPort => "DEFAULT_KICK_TO_PORT",
            Command::DefaultKickToReason => "DEFAULT_KICK_TO_REASON",
            Command::DefaultKickToServer => "DEFAULT_KICK_TO_SERVER",
            Command::DefaultShoutPlayer => "DEFAULT_SHOUT_PLAYER",
            Command::DefaultShoutSpectator => "DEFAULT_SHOUT_SPECTATOR",
            Command::DisallowRenamePlayer => "DISALLOW_RENAME_PLAYER",
            Command::DisallowTeamChangePlayer => "DISALLOW_TEAM_CHANGE_PLAYER",
            Command::Dither => "DITHER",
            Command::DoublebindTime => "DOUBLEBIND_TIME",
            Command::DoublebindTimeOverride => "DOUBLEBIND_TIME_OVERRIDE",
            Command::EnableChat => "ENABLE_CHAT",
            Command::EnableFriends => "ENABLE_FRIENDS",
            Command::EnemyChatbotPenalty => "ENEMY_CHATBOT_PENALTY",
            Command::EnemyCurrenttimeInfluence => "ENEMY_CURRENTTIME_INFLUENCE",
            Command::EnemyDeadPenalty => "ENEMY_DEAD_PENALTY",
            Command::EnemySuicideTimeout => "ENEMY_SUICIDE_TIMEOUT",
            Command::EnemyTeammatePenalty => "ENEMY_TEAMMATE_PENALTY",
            Command::ExpectAckOnClientPlayback => "EXPECT_ACK_ON_CLIENT_PLAYBACK",
            Command::Explosion => "EXPLOSION",
            Command::ExplosionRadius => "EXPLOSION_RADIUS",
            Command::ExtraRoundTime => "EXTRA_ROUND_TIME",
            Command::FadeoutNameDelay => "FADEOUT_NAME_DELAY",
            Command::FailedAttempts => "FAILED_ATTEMPTS",
            Command::FastestLocx => "FASTEST_LOCX",
            Command::FastestLocy => "FASTEST_LOCY",
            Command::FastestSize => "FASTEST_SIZE",
            Command::FastForwardMaxstep => "FAST_FORWARD_MAXSTEP",
            Command::FastForwardMaxstepReal => "FAST_FORWARD_MAXSTEP_REAL",
            Command::FastForwardMaxstepRel => "FAST_FORWARD_MAXSTEP_REL",
            Command::FavNumPerTeamPlayer1 => "FAV_NUM_PER_TEAM_PLAYER_1",
            Command::FavNumPerTeamPlayer2 => "FAV_NUM_PER_TEAM_PLAYER_2",
            Command::FavNumPerTeamPlayer3 => "FAV_NUM_PER_TEAM_PLAYER_3",
            Command::FavNumPerTeamPlayer4 => "FAV_NUM_PER_TEAM_PLAYER_4",
            Command::FilterColorNames => "FILTER_COLOR_NAMES",
            Command::FilterColorServerNames => "FILTER_COLOR_SERVER_NAMES",
            Command::FilterColorStrings => "FILTER_COLOR_STRINGS",
            Command::FilterColorTeam => "FILTER_COLOR_TEAM",
            Command::FilterDarkColorNames => "FILTER_DARK_COLOR_NAMES",
            Command::FilterDarkColorServerNames => "FILTER_DARK_COLOR_SERVER_NAMES",
            Command::FilterDarkColorStrings => "FILTER_DARK_COLOR_STRINGS",
            Command::FilterDarkColorTeam => "FILTER_DARK_COLOR_TEAM",
            Command::FilterNameEnds => "FILTER_NAME_ENDS",
            Command::FilterNameMiddle => "FILTER_NAME_MIDDLE",
            Command::FinishType => "FINISH_TYPE",
            Command::FirstUse => "FIRST_USE",
            Command::FloorBlue => "FLOOR_BLUE",
            Command::FloorDetail => "FLOOR_DETAIL",
            Command::FloorGreen => "FLOOR_GREEN",
            Command::FloorMirror => "FLOOR_MIRROR",
            Command::FloorMirrorInt => "FLOOR_MIRROR_INT",
            Command::FloorRed => "FLOOR_RED",
            Command::FontSmallThresholdHeight => "FONT_SMALL_THRESHOLD_HEIGHT",
            Command::FontSmallThresholdWidth => "FONT_SMALL_THRESHOLD_WIDTH",
            Command::ForceTurtleMode => "FORCE_TURTLE_MODE",
            Command::FortressCollapseSpeed => "FORTRESS_COLLAPSE_SPEED",
            Command::FortressConquestDecayRate => "FORTRESS_CONQUEST_DECAY_RATE",
            Command::FortressConquestRate => "FORTRESS_CONQUEST_RATE",
            Command::FortressConquestTimeout => "FORTRESS_CONQUEST_TIMEOUT",
            Command::FortressDefendRate => "FORTRESS_DEFEND_RATE",
            Command::FortressHeldScore => "FORTRESS_HELD_SCORE",
            Command::Friend1 => "FRIEND_1",
            Command::Friend10 => "FRIEND_10",
            Command::Friend2 => "FRIEND_2",
            Command::Friend3 => "FRIEND_3",
            Command::Friend4 => "FRIEND_4",
            Command::Friend5 => "FRIEND_5",
            Command::Friend6 => "FRIEND_6",
            Command::Friend7 => "FRIEND_7",
            Command::Friend8 => "FRIEND_8",
            Command::Friend9 => "FRIEND_9",
            Command::Fullscreen => "FULLSCREEN",
            Command::FullscreenMessage => "FULLSCREEN_MESSAGE",
            Command::GameTimeout => "GAME_TIMEOUT",
            Command::GameType => "GAME_TYPE",
            Command::GlanceBackTooltip => "GLANCE_BACK_TOOLTIP",
            Command::GlanceLeftTooltip => "GLANCE_LEFT_TOOLTIP",
            Command::GlanceRightTooltip => "GLANCE_RIGHT_TOOLTIP",
            Command::GlobalId => "GLOBAL_ID",
            Command::GlExtensions => "GL_EXTENSIONS",
            Command::GlRenderer => "GL_RENDERER",
            Command::GlVendor => "GL_VENDOR",
            Command::GlVersion => "GL_VERSION",
            Command::GridSize => "GRID_SIZE",
            Command::GridSizeMoviepack => "GRID_SIZE_MOVIEPACK",
            Command::HashMethodBlacklist => "HASH_METHOD_BLACKLIST",
            Command::HelpIntroductoryBlurb => "HELP_INTRODUCTORY_BLURB",
            Command::HideIdentity1 => "HIDE_IDENTITY_1",
            Command::HideIdentity2 => "HIDE_IDENTITY_2",
            Command::HideIdentity3 => "HIDE_IDENTITY_3",
            Command::HideIdentity4 => "HIDE_IDENTITY_4",
            Command::HighRim => "HIGH_RIM",
            Command::HistorySizeChat => "HISTORY_SIZE_CHAT",
            Command::HistorySizeConsole => "HISTORY_SIZE_CONSOLE",
            Command::HudCacheThreshold => "HUD_CACHE_THRESHOLD",
            Command::HudMaxWidth => "HUD_MAX_WIDTH",
            Command::IdleKickTime => "IDLE_KICK_TIME",
            Command::IdleRemoveTime => "IDLE_REMOVE_TIME",
            Command::Include => "INCLUDE",
            Command::InfinityPlane => "INFINITY_PLANE",
            Command::IngameMenuTooltip => "INGAME_MENU_TOOLTIP",
            Command::InstantChatString1_1 => "INSTANT_CHAT_STRING_1_1",
            Command::InstantChatString1_10 => "INSTANT_CHAT_STRING_1_10",
            Command::InstantChatString1_11 => "INSTANT_CHAT_STRING_1_11",
            Command::InstantChatString1_12 => "INSTANT_CHAT_STRING_1_12",
            Command::InstantChatString1_13 => "INSTANT_CHAT_STRING_1_13",
            Command::InstantChatString1_14 => "INSTANT_CHAT_STRING_1_14",
            Command::InstantChatString1_15 => "INSTANT_CHAT_STRING_1_15",
            Command::InstantChatString1_16 => "INSTANT_CHAT_STRING_1_16",
            Command::InstantChatString1_17 => "INSTANT_CHAT_STRING_1_17",
            Command::InstantChatString1_18 => "INSTANT_CHAT_STRING_1_18",
            Command::InstantChatString1_19 => "INSTANT_CHAT_STRING_1_19",
            Command::InstantChatString1_2 => "INSTANT_CHAT_STRING_1_2",
            Command::InstantChatString1_20 => "INSTANT_CHAT_STRING_1_20",
            Command::InstantChatString1_21 => "INSTANT_CHAT_STRING_1_21",
            Command::InstantChatString1_22 => "INSTANT_CHAT_STRING_1_22",
            Command::InstantChatString1_23 => "INSTANT_CHAT_STRING_1_23",
            Command::InstantChatString1_24 => "INSTANT_CHAT_STRING_1_24",
            Command::InstantChatString1_25 => "INSTANT_CHAT_STRING_1_25",
            Command::InstantChatString1_3 => "INSTANT_CHAT_STRING_1_3",
            Command::InstantChatString1_4 => "INSTANT_CHAT_STRING_1_4",
            Command::InstantChatString1_5 => "INSTANT_CHAT_STRING_1_5",
            Command::InstantChatString1_6 => "INSTANT_CHAT_STRING_1_6",
            Command::InstantChatString1_7 => "INSTANT_CHAT_STRING_1_7",
            Command::InstantChatString1_8 => "INSTANT_CHAT_STRING_1_8",
            Command::InstantChatString1_9 => "INSTANT_CHAT_STRING_1_9",
            Command::InstantChatString2_1 => "INSTANT_CHAT_STRING_2_1",
            Command::InstantChatString2_10 => "INSTANT_CHAT_STRING_2_10",
            Command::InstantChatString2_11 => "INSTANT_CHAT_STRING_2_11",
            Command::InstantChatString2_12 => "INSTANT_CHAT_STRING_2_12",
            Command::InstantChatString2_13 => "INSTANT_CHAT_STRING_2_13",
            Command::InstantChatString2_14 => "INSTANT_CHAT_STRING_2_14",
            Command::InstantChatString2_15 => "INSTANT_CHAT_STRING_2_15",
            Command::InstantChatString2_16 => "INSTANT_CHAT_STRING_2_16",
            Command::InstantChatString2_17 => "INSTANT_CHAT_STRING_2_17",
            Command::InstantChatString2_18 => "INSTANT_CHAT_STRING_2_18",
            Command::InstantChatString2_19 => "INSTANT_CHAT_STRING_2_19",
            Command::InstantChatString2_2 => "INSTANT_CHAT_STRING_2_2",
            Command::InstantChatString2_20 => "INSTANT_CHAT_STRING_2_20",
            Command::InstantChatString2_21 => "INSTANT_CHAT_STRING_2_21",
            Command::InstantChatString2_22 => "INSTANT_CHAT_STRING_2_22",
            Command::InstantChatString2_23 => "INSTANT_CHAT_STRING_2_23",
            Command::InstantChatString2_24 => "INSTANT_CHAT_STRING_2_24",
            Command::InstantChatString2_25 => "INSTANT_CHAT_STRING_2_25",
            Command::InstantChatString2_3 => "INSTANT_CHAT_STRING_2_3",
            Command::InstantChatString2_4 => "INSTANT_CHAT_STRING_2_4",
            Command::InstantChatString2_5 => "INSTANT_CHAT_STRING_2_5",
            Command::InstantChatString2_6 => "INSTANT_CHAT_STRING_2_6",
            Command::InstantChatString2_7 => "INSTANT_CHAT_STRING_2_7",
            Command::InstantChatString2_8 => "INSTANT_CHAT_STRING_2_8",
            Command::InstantChatString2_9 => "INSTANT_CHAT_STRING_2_9",
            Command::InstantChatString3_1 => "INSTANT_CHAT_STRING_3_1",
            Command::InstantChatString3_10 => "INSTANT_CHAT_STRING_3_10",
            Command::InstantChatString3_11 => "INSTANT_CHAT_STRING_3_11",
            Command::InstantChatString3_12 => "INSTANT_CHAT_STRING_3_12",
            Command::InstantChatString3_13 => "INSTANT_CHAT_STRING_3_13",
            Command::InstantChatString3_14 => "INSTANT_CHAT_STRING_3_14",
            Command::InstantChatString3_15 => "INSTANT_CHAT_STRING_3_15",
            Command::InstantChatString3_16 => "INSTANT_CHAT_STRING_3_16",
            Command::InstantChatString3_17 => "INSTANT_CHAT_STRING_3_17",
            Command::InstantChatString3_18 => "INSTANT_CHAT_STRING_3_18",
            Command::InstantChatString3_19 => "INSTANT_CHAT_STRING_3_19",
            Command::InstantChatString3_2 => "INSTANT_CHAT_STRING_3_2",
            Command::InstantChatString3_20 => "INSTANT_CHAT_STRING_3_20",
            Command::InstantChatString3_21 => "INSTANT_CHAT_STRING_3_21",
            Command::InstantChatString3_22 => "INSTANT_CHAT_STRING_3_22",
            Command::InstantChatString3_23 => "INSTANT_CHAT_STRING_3_23",
            Command::InstantChatString3_24 => "INSTANT_CHAT_STRING_3_24",
            Command::InstantChatString3_25 => "INSTANT_CHAT_STRING_3_25",
            Command::InstantChatString3_3 => "INSTANT_CHAT_STRING_3_3",
            Command::InstantChatString3_4 => "INSTANT_CHAT_STRING_3_4",
            Command::InstantChatString3_5 => "INSTANT_CHAT_STRING_3_5",
            Command::InstantChatString3_6 => "INSTANT_CHAT_STRING_3_6",
            Command::InstantChatString3_7 => "INSTANT_CHAT_STRING_3_7",
            Command::InstantChatString3_8 => "INSTANT_CHAT_STRING_3_8",
            Command::InstantChatString3_9 => "INSTANT_CHAT_STRING_3_9",
            Command::InstantChatString4_1 => "INSTANT_CHAT_STRING_4_1",
            Command::InstantChatString4_10 => "INSTANT_CHAT_STRING_4_10",
            Command::InstantChatString4_11 => "INSTANT_CHAT_STRING_4_11",
            Command::InstantChatString4_12 => "INSTANT_CHAT_STRING_4_12",
            Command::InstantChatString4_13 => "INSTANT_CHAT_STRING_4_13",
            Command::InstantChatString4_14 => "INSTANT_CHAT_STRING_4_14",
            Command::InstantChatString4_15 => "INSTANT_CHAT_STRING_4_15",
            Command::InstantChatString4_16 => "INSTANT_CHAT_STRING_4_16",
            Command::InstantChatString4_17 => "INSTANT_CHAT_STRING_4_17",
            Command::InstantChatString4_18 => "INSTANT_CHAT_STRING_4_18",
            Command::InstantChatString4_19 => "INSTANT_CHAT_STRING_4_19",
            Command::InstantChatString4_2 => "INSTANT_CHAT_STRING_4_2",
            Command::InstantChatString4_20 => "INSTANT_CHAT_STRING_4_20",
            Command::InstantChatString4_21 => "INSTANT_CHAT_STRING_4_21",
            Command::InstantChatString4_22 => "INSTANT_CHAT_STRING_4_22",
            Command::InstantChatString4_23 => "INSTANT_CHAT_STRING_4_23",
            Command::InstantChatString4_24 => "INSTANT_CHAT_STRING_4_24",
            Command::InstantChatString4_25 => "INSTANT_CHAT_STRING_4_25",
            Command::InstantChatString4_3 => "INSTANT_CHAT_STRING_4_3",
            Command::InstantChatString4_4 => "INSTANT_CHAT_STRING_4_4",
            Command::InstantChatString4_5 => "INSTANT_CHAT_STRING_4_5",
            Command::InstantChatString4_6 => "INSTANT_CHAT_STRING_4_6",
            Command::InstantChatString4_7 => "INSTANT_CHAT_STRING_4_7",
            Command::InstantChatString4_8 => "INSTANT_CHAT_STRING_4_8",
            Command::InstantChatString4_9 => "INSTANT_CHAT_STRING_4_9",
            Command::KeepPlayerSlot => "KEEP_PLAYER_SLOT",
            Command::KeepWindowActive => "KEEP_WINDOW_ACTIVE",
            Command::Keyboard => "KEYBOARD",
            Command::Kick => "KICK",
            Command::KickTo => "KICK_TO",
            Command::Kill => "KILL",
            Command::LadderlogDecorateTimestamp => "LADDERLOG_DECORATE_TIMESTAMP",
            Command::LadderlogGameTimeInterval => "LADDERLOG_GAME_TIME_INTERVAL",
            Command::LadderlogWriteAll => "LADDERLOG_WRITE_ALL",
            Command::LadderlogWriteAuthorityBlurb => "LADDERLOG_WRITE_AUTHORITY_BLURB",
            Command::LadderlogWriteBasezoneConquered => "LADDERLOG_WRITE_BASEZONE_CONQUERED",
            Command::LadderlogWriteBasezoneConquerer => "LADDERLOG_WRITE_BASEZONE_CONQUERER",
            Command::LadderlogWriteChat => "LADDERLOG_WRITE_CHAT",
            Command::LadderlogWriteDeathFrag => "LADDERLOG_WRITE_DEATH_FRAG",
            Command::LadderlogWriteDeathSuicide => "LADDERLOG_WRITE_DEATH_SUICIDE",
            Command::LadderlogWriteDeathTeamkill => "LADDERLOG_WRITE_DEATH_TEAMKILL",
            Command::LadderlogWriteEncoding => "LADDERLOG_WRITE_ENCODING",
            Command::LadderlogWriteGameEnd => "LADDERLOG_WRITE_GAME_END",
            Command::LadderlogWriteGameTime => "LADDERLOG_WRITE_GAME_TIME",
            Command::LadderlogWriteMatchWinner => "LADDERLOG_WRITE_MATCH_WINNER",
            Command::LadderlogWriteNewMatch => "LADDERLOG_WRITE_NEW_MATCH",
            Command::LadderlogWriteNewRound => "LADDERLOG_WRITE_NEW_ROUND",
            Command::LadderlogWriteNumHumans => "LADDERLOG_WRITE_NUM_HUMANS",
            Command::LadderlogWriteOnlinePlayer => "LADDERLOG_WRITE_ONLINE_PLAYER",
            Command::LadderlogWritePlayerEntered => "LADDERLOG_WRITE_PLAYER_ENTERED",
            Command::LadderlogWritePlayerLeft => "LADDERLOG_WRITE_PLAYER_LEFT",
            Command::LadderlogWritePlayerRenamed => "LADDERLOG_WRITE_PLAYER_RENAMED",
            Command::LadderlogWritePositions => "LADDERLOG_WRITE_POSITIONS",
            Command::LadderlogWriteRoundScore => "LADDERLOG_WRITE_ROUND_SCORE",
            Command::LadderlogWriteRoundScoreTeam => "LADDERLOG_WRITE_ROUND_SCORE_TEAM",
            Command::LadderlogWriteRoundWinner => "LADDERLOG_WRITE_ROUND_WINNER",
            Command::LadderlogWriteSacrifice => "LADDERLOG_WRITE_SACRIFICE",
            Command::LadderlogWriteTeamCreated => "LADDERLOG_WRITE_TEAM_CREATED",
            Command::LadderlogWriteTeamDestroyed => "LADDERLOG_WRITE_TEAM_DESTROYED",
            Command::LadderlogWriteTeamPlayerAdded => "LADDERLOG_WRITE_TEAM_PLAYER_ADDED",
            Command::LadderlogWriteTeamPlayerRemoved => "LADDERLOG_WRITE_TEAM_PLAYER_REMOVED",
            Command::LadderlogWriteTeamRenamed => "LADDERLOG_WRITE_TEAM_RENAMED",
            Command::LadderlogWriteWaitForExternalScript => {
                "LADDERLOG_WRITE_WAIT_FOR_EXTERNAL_SCRIPT"
            }
            Command::LadderGainExtra => "LADDER_GAIN_EXTRA",
            Command::LadderLoseMinOnLoad => "LADDER_LOSE_MIN_ON_LOAD",
            Command::LadderLosePercentOnLoad => "LADDER_LOSE_PERCENT_ON_LOAD",
            Command::LadderMinBet => "LADDER_MIN_BET",
            Command::LadderPercentBet => "LADDER_PERCENT_BET",
            Command::LadderTax => "LADDER_TAX",
            Command::LagCredit => "LAG_CREDIT",
            Command::LagCreditSingle => "LAG_CREDIT_SINGLE",
            Command::LagCreditTime => "LAG_CREDIT_TIME",
            Command::LagCreditVariance => "LAG_CREDIT_VARIANCE",
            Command::LagFastTime => "LAG_FAST_TIME",
            Command::LagFastWeight => "LAG_FAST_WEIGHT",
            Command::LagFrequencyThreshold => "LAG_FREQUENCY_THRESHOLD",
            Command::LagMaxSpeedupTimer => "LAG_MAX_SPEEDUP_TIMER",
            Command::LagOffsetClient => "LAG_OFFSET_CLIENT",
            Command::LagOffsetLegacy => "LAG_OFFSET_LEGACY",
            Command::LagOffsetServer => "LAG_OFFSET_SERVER",
            Command::LagOMeter => "LAG_O_METER",
            Command::LagOMeterBlend => "LAG_O_METER_BLEND",
            Command::LagOMeterScale => "LAG_O_METER_SCALE",
            Command::LagOMeterThreshold => "LAG_O_METER_THRESHOLD",
            Command::LagOMeterUseOld => "LAG_O_METER_USE_OLD",
            Command::LagSlowTime => "LAG_SLOW_TIME",
            Command::LagSlowWeight => "LAG_SLOW_WEIGHT",
            Command::LagSweetSpot => "LAG_SWEET_SPOT",
            Command::LagThreshold => "LAG_THRESHOLD",
            Command::LanguageFirst => "LANGUAGE_FIRST",
            Command::LanguageSecond => "LANGUAGE_SECOND",
            Command::LastChatBreakTime => "LAST_CHAT_BREAK_TIME",
            Command::LastCheckErrors => "LAST_CHECK_ERRORS",
            Command::LastColordepth => "LAST_COLORDEPTH",
            Command::LastFullscreen => "LAST_FULLSCREEN",
            Command::LastZdepth => "LAST_ZDEPTH",
            Command::LegacyLogNames => "LEGACY_LOG_NAMES",
            Command::LimitRounds => "LIMIT_ROUNDS",
            Command::LimitScore => "LIMIT_SCORE",
            Command::LimitTime => "LIMIT_TIME",
            Command::LocalTeam => "LOCAL_TEAM",
            Command::LocalUser => "LOCAL_USER",
            Command::LowerSky => "LOWER_SKY",
            Command::MapFile => "MAP_FILE",
            Command::MapFileOverride => "MAP_FILE_OVERRIDE",
            Command::MapUri => "MAP_URI",
            Command::MaxClients => "MAX_CLIENTS",
            Command::MaxClientsSameIpHard => "MAX_CLIENTS_SAME_IP_HARD",
            Command::MaxClientsSameIpSoft => "MAX_CLIENTS_SAME_IP_SOFT",
            Command::MaxInRate => "MAX_IN_RATE",
            Command::MaxOutRate => "MAX_OUT_RATE",
            Command::MaxPlayersSameIp => "MAX_PLAYERS_SAME_IP",
            Command::MaxProtocolVersion => "MAX_PROTOCOL_VERSION",
            Command::MaxVotes => "MAX_VOTES",
            Command::MaxVotesPerVoter => "MAX_VOTES_PER_VOTER",
            Command::Md5Prefix => "MD5_PREFIX",
            Command::Md5Suffix => "MD5_SUFFIX",
            Command::MessageOfDay => "MESSAGE_OF_DAY",
            Command::MessageOfDayTimeout => "MESSAGE_OF_DAY_TIMEOUT",
            Command::MinPlayers => "MIN_PLAYERS",
            Command::MinPlayTimeOnline => "MIN_PLAY_TIME_ONLINE",
            Command::MinPlayTimeTeam => "MIN_PLAY_TIME_TEAM",
            Command::MinPlayTimeTotal => "MIN_PLAY_TIME_TOTAL",
            Command::MinProtocolVersion => "MIN_PROTOCOL_VERSION",
            Command::MinVoters => "MIN_VOTERS",
            Command::MouseGrab => "MOUSE_GRAB",
            Command::MoveTo => "MOVE_TO",
            Command::Moviepack => "MOVIEPACK",
            Command::MoviepackFloorBlue => "MOVIEPACK_FLOOR_BLUE",
            Command::MoviepackFloorGreen => "MOVIEPACK_FLOOR_GREEN",
            Command::MoviepackFloorRed => "MOVIEPACK_FLOOR_RED",
            Command::MoviepackRimWallStretchX => "MOVIEPACK_RIM_WALL_STRETCH_X",
            Command::MoviepackRimWallStretchY => "MOVIEPACK_RIM_WALL_STRETCH_Y",
            Command::MoviepackWallStretch => "MOVIEPACK_WALL_STRETCH",
            Command::NameTeamAfterPlayer1 => "NAME_TEAM_AFTER_PLAYER_1",
            Command::NameTeamAfterPlayer2 => "NAME_TEAM_AFTER_PLAYER_2",
            Command::NameTeamAfterPlayer3 => "NAME_TEAM_AFTER_PLAYER_3",
            Command::NameTeamAfterPlayer4 => "NAME_TEAM_AFTER_PLAYER_4",
            Command::NetworkAutobanFactor => "NETWORK_AUTOBAN_FACTOR",
            Command::NetworkAutobanMaxKph => "NETWORK_AUTOBAN_MAX_KPH",
            Command::NetworkAutobanOffset => "NETWORK_AUTOBAN_OFFSET",
            Command::NetworkMinBan => "NETWORK_MIN_BAN",
            Command::NetworkSpectatorTime => "NETWORK_SPECTATOR_TIME",
            Command::NewFeatureDelay => "NEW_FEATURE_DELAY",
            Command::NewTeamAllowed => "NEW_TEAM_ALLOWED",
            Command::NumAis => "NUM_AIS",
            Command::Password => "PASSWORD",
            Command::PasswordStorage => "PASSWORD_STORAGE",
            Command::PingCharity => "PING_CHARITY",
            Command::PingCharityMax => "PING_CHARITY_MAX",
            Command::PingCharityMin => "PING_CHARITY_MIN",
            Command::PingCharityServer => "PING_CHARITY_SERVER",
            Command::PingFloodGlobal => "PING_FLOOD_GLOBAL",
            Command::PingFloodTime10 => "PING_FLOOD_TIME_10",
            Command::PingFloodTime100 => "PING_FLOOD_TIME_100",
            Command::PingFloodTime20 => "PING_FLOOD_TIME_20",
            Command::PingFloodTime50 => "PING_FLOOD_TIME_50",
            Command::PingLocx => "PING_LOCX",
            Command::PingLocy => "PING_LOCY",
            Command::PingSize => "PING_SIZE",
            Command::Players => "PLAYERS",
            Command::Player1 => "PLAYER_1",
            Command::Player2 => "PLAYER_2",
            Command::Player3 => "PLAYER_3",
            Command::Player4 => "PLAYER_4",
            Command::PlayerChatWaitFraction => "PLAYER_CHAT_WAIT_FRACTION",
            Command::PlayerChatWaitMax => "PLAYER_CHAT_WAIT_MAX",
            Command::PlayerChatWaitSingle => "PLAYER_CHAT_WAIT_SINGLE",
            Command::PlayerChatWaitTeamleader => "PLAYER_CHAT_WAIT_TEAMLEADER",
            Command::PlayerListHiddenPlayerPrefix => "PLAYER_LIST_HIDDEN_PLAYER_PREFIX",
            Command::PlayerMessage => "PLAYER_MESSAGE",
            Command::PlayerRandomColor => "PLAYER_RANDOM_COLOR",
            Command::PlayTimeOnline => "PLAY_TIME_ONLINE",
            Command::PlayTimeTeam => "PLAY_TIME_TEAM",
            Command::PlayTimeTotal => "PLAY_TIME_TOTAL",
            Command::PngScreenshot => "PNG_SCREENSHOT",
            Command::PredictObjects => "PREDICT_OBJECTS",
            Command::PrefixSpamEnable => "PREFIX_SPAM_ENABLE",
            Command::PrefixSpamLengthMultiplier => "PREFIX_SPAM_LENGTH_MULTIPLIER",
            Command::PrefixSpamNumberColorCodesMultiplier => {
                "PREFIX_SPAM_NUMBER_COLOR_CODES_MULTIPLIER"
            }
            Command::PrefixSpamNumberKnownPrefixesMultiplier => {
                "PREFIX_SPAM_NUMBER_KNOWN_PREFIXES_MULTIPLIER"
            }
            Command::PrefixSpamRequiredScore => "PREFIX_SPAM_REQUIRED_SCORE",
            Command::PrefixSpamStartColorMultiplier => "PREFIX_SPAM_START_COLOR_MULTIPLIER",
            Command::PrefixSpamTimeoutMultiplier => "PREFIX_SPAM_TIMEOUT_MULTIPLIER",
            Command::ProtectSensitiveFiles => "PROTECT_SENSITIVE_FILES",
            Command::RealArenaSizeFactor => "REAL_ARENA_SIZE_FACTOR",
            Command::RealCycleSpeedFactor => "REAL_CYCLE_SPEED_FACTOR",
            Command::RecordingDebuglevel => "RECORDING_DEBUGLEVEL",
            Command::RecordTurtleMode => "RECORD_TURTLE_MODE",
            Command::RemoveHelpTopic => "REMOVE_HELP_TOPIC",
            Command::Rename => "RENAME",
            Command::ReserveScreenName => "RESERVE_SCREEN_NAME",
            Command::ResourceRepositoryClient => "RESOURCE_REPOSITORY_CLIENT",
            Command::ResourceRepositoryServer => "RESOURCE_REPOSITORY_SERVER",
            Command::RimWallStretchX => "RIM_WALL_STRETCH_X",
            Command::RimWallStretchY => "RIM_WALL_STRETCH_Y",
            Command::RimWallWrapY => "RIM_WALL_WRAP_Y",
            Command::Rinclude => "RINCLUDE",
            Command::RoundCenterMessage => "ROUND_CENTER_MESSAGE",
            Command::RoundConsoleMessage => "ROUND_CONSOLE_MESSAGE",
            Command::RubberGaugeLocx => "RUBBER_GAUGE_LOCX",
            Command::RubberGaugeLocy => "RUBBER_GAUGE_LOCY",
            Command::RubberGaugeSize => "RUBBER_GAUGE_SIZE",
            Command::SavedInVersion => "SAVED_IN_VERSION",
            Command::Say => "SAY",
            Command::ScoreDeathzone => "SCORE_DEATHZONE",
            Command::ScoreDie => "SCORE_DIE",
            Command::ScoreHole => "SCORE_HOLE",
            Command::ScoreKill => "SCORE_KILL",
            Command::ScoreLocx => "SCORE_LOCX",
            Command::ScoreLocy => "SCORE_LOCY",
            Command::ScoreSize => "SCORE_SIZE",
            Command::ScoreSuicide => "SCORE_SUICIDE",
            Command::ScoreSurvive => "SCORE_SURVIVE",
            Command::ScoreWin => "SCORE_WIN",
            Command::ServerDns => "SERVER_DNS",
            Command::ServerIp => "SERVER_IP",
            Command::ServerName => "SERVER_NAME",
            Command::ServerPort => "SERVER_PORT",
            Command::SettingLegacyBehaviorAnnoying => "SETTING_LEGACY_BEHAVIOR_ANNOYING",
            Command::SettingLegacyBehaviorBreaking => "SETTING_LEGACY_BEHAVIOR_BREAKING",
            Command::SettingLegacyBehaviorBumpy => "SETTING_LEGACY_BEHAVIOR_BUMPY",
            Command::SettingLegacyBehaviorCheating => "SETTING_LEGACY_BEHAVIOR_CHEATING",
            Command::SettingLegacyBehaviorVisual => "SETTING_LEGACY_BEHAVIOR_VISUAL",
            Command::ShowAlive => "SHOW_ALIVE",
            Command::ShowBrake => "SHOW_BRAKE",
            Command::ShowFastest => "SHOW_FASTEST",
            Command::ShowFps => "SHOW_FPS",
            Command::ShowHud => "SHOW_HUD",
            Command::ShowOwnIp => "SHOW_OWN_IP",
            Command::ShowOwnName => "SHOW_OWN_NAME",
            Command::ShowPing => "SHOW_PING",
            Command::ShowRecordingTime => "SHOW_RECORDING_TIME",
            Command::ShowRubber => "SHOW_RUBBER",
            Command::ShowScore => "SHOW_SCORE",
            Command::ShowSpeed => "SHOW_SPEED",
            Command::ShowTime => "SHOW_TIME",
            Command::ShowTime24 => "SHOW_TIME_24",
            Command::ShuffleSpamMessagesPerRound => "SHUFFLE_SPAM_MESSAGES_PER_ROUND",
            Command::Silence => "SILENCE",
            Command::SilenceDefault => "SILENCE_DEFAULT",
            Command::SimpleTrail => "SIMPLE_TRAIL",
            Command::Sinclude => "SINCLUDE",
            Command::SizeFactor => "SIZE_FACTOR",
            Command::SkyWobble => "SKY_WOBBLE",
            Command::Slap => "SLAP",
            Command::SmartGlanceCustom1 => "SMART_GLANCE_CUSTOM_1",
            Command::SmartGlanceCustom2 => "SMART_GLANCE_CUSTOM_2",
            Command::SmartGlanceCustom3 => "SMART_GLANCE_CUSTOM_3",
            Command::SmartGlanceCustom4 => "SMART_GLANCE_CUSTOM_4",
            Command::SmoothShading => "SMOOTH_SHADING",
            Command::SoftwareRenderer => "SOFTWARE_RENDERER",
            Command::SoundBufferShift => "SOUND_BUFFER_SHIFT",
            Command::SoundQuality => "SOUND_QUALITY",
            Command::SoundSources => "SOUND_SOURCES",
            Command::SpamAutokick => "SPAM_AUTOKICK",
            Command::SpamAutokickCount => "SPAM_AUTOKICK_COUNT",
            Command::SpamMaxlen => "SPAM_MAXLEN",
            Command::SpamMaxlenOverride => "SPAM_MAXLEN_OVERRIDE",
            Command::SpamPenalty => "SPAM_PENALTY",
            Command::SpamProtection => "SPAM_PROTECTION",
            Command::SpamProtectionChat => "SPAM_PROTECTION_CHAT",
            Command::SpamProtectionRepeat => "SPAM_PROTECTION_REPEAT",
            Command::SpamProtectionVote => "SPAM_PROTECTION_VOTE",
            Command::Sparks => "SPARKS",
            Command::SpawnWingmenBack => "SPAWN_WINGMEN_BACK",
            Command::SpawnWingmenSide => "SPAWN_WINGMEN_SIDE",
            Command::SpectatorMode1 => "SPECTATOR_MODE_1",
            Command::SpectatorMode2 => "SPECTATOR_MODE_2",
            Command::SpectatorMode3 => "SPECTATOR_MODE_3",
            Command::SpectatorMode4 => "SPECTATOR_MODE_4",
            Command::SpeedFactor => "SPEED_FACTOR",
            Command::SpeedGaugeLocx => "SPEED_GAUGE_LOCX",
            Command::SpeedGaugeLocy => "SPEED_GAUGE_LOCY",
            Command::SpeedGaugeSize => "SPEED_GAUGE_SIZE",
            Command::SpAiIq => "SP_AI_IQ",
            Command::SpAutoAis => "SP_AUTO_AIS",
            Command::SpAutoIq => "SP_AUTO_IQ",
            Command::SpExplosionRadius => "SP_EXPLOSION_RADIUS",
            Command::SpFinishType => "SP_FINISH_TYPE",
            Command::SpGameType => "SP_GAME_TYPE",
            Command::SpLimitRounds => "SP_LIMIT_ROUNDS",
            Command::SpLimitScore => "SP_LIMIT_SCORE",
            Command::SpLimitTime => "SP_LIMIT_TIME",
            Command::SpMinPlayers => "SP_MIN_PLAYERS",
            Command::SpNumAis => "SP_NUM_AIS",
            Command::SpScoreWin => "SP_SCORE_WIN",
            Command::SpSizeFactor => "SP_SIZE_FACTOR",
            Command::SpSpeedFactor => "SP_SPEED_FACTOR",
            Command::SpTeamsMax => "SP_TEAMS_MAX",
            Command::SpTeamsMin => "SP_TEAMS_MIN",
            Command::SpTeamBalanceOnQuit => "SP_TEAM_BALANCE_ON_QUIT",
            Command::SpTeamBalanceWithAis => "SP_TEAM_BALANCE_WITH_AIS",
            Command::SpTeamMaxImbalance => "SP_TEAM_MAX_IMBALANCE",
            Command::SpTeamMaxPlayers => "SP_TEAM_MAX_PLAYERS",
            Command::SpTeamMinPlayers => "SP_TEAM_MIN_PLAYERS",
            Command::SpWallsLength => "SP_WALLS_LENGTH",
            Command::SpWallsStayUpDelay => "SP_WALLS_STAY_UP_DELAY",
            Command::SpWinZoneMinLastDeath => "SP_WIN_ZONE_MIN_LAST_DEATH",
            Command::SpWinZoneMinRoundTime => "SP_WIN_ZONE_MIN_ROUND_TIME",
            Command::StartCam1 => "START_CAM_1",
            Command::StartCam2 => "START_CAM_2",
            Command::StartCam3 => "START_CAM_3",
            Command::StartCam4 => "START_CAM_4",
            Command::StartFov1 => "START_FOV_1",
            Command::StartFov2 => "START_FOV_2",
            Command::StartFov3 => "START_FOV_3",
            Command::StartFov4 => "START_FOV_4",
            Command::StartNewMatch => "START_NEW_MATCH",
            Command::StopRecording => "STOP_RECORDING",
            Command::Suspend => "SUSPEND",
            Command::SuspendDefaultRounds => "SUSPEND_DEFAULT_ROUNDS",
            Command::SwapMode => "SWAP_MODE",
            Command::SwitchViewTooltip => "SWITCH_VIEW_TOOLTIP",
            Command::TalkToMaster => "TALK_TO_MASTER",
            Command::Teams => "TEAMS",
            Command::TeamsMax => "TEAMS_MAX",
            Command::TeamsMin => "TEAMS_MIN",
            Command::TeamBalanceOnQuit => "TEAM_BALANCE_ON_QUIT",
            Command::TeamBalanceWithAis => "TEAM_BALANCE_WITH_AIS",
            Command::TeamBlue1 => "TEAM_BLUE_1",
            Command::TeamBlue2 => "TEAM_BLUE_2",
            Command::TeamBlue3 => "TEAM_BLUE_3",
            Command::TeamBlue4 => "TEAM_BLUE_4",
            Command::TeamBlue5 => "TEAM_BLUE_5",
            Command::TeamBlue6 => "TEAM_BLUE_6",
            Command::TeamBlue7 => "TEAM_BLUE_7",
            Command::TeamBlue8 => "TEAM_BLUE_8",
            Command::TeamCenterIsBoss => "TEAM_CENTER_IS_BOSS",
            Command::TeamEliminationMode => "TEAM_ELIMINATION_MODE",
            Command::TeamGreen1 => "TEAM_GREEN_1",
            Command::TeamGreen2 => "TEAM_GREEN_2",
            Command::TeamGreen3 => "TEAM_GREEN_3",
            Command::TeamGreen4 => "TEAM_GREEN_4",
            Command::TeamGreen5 => "TEAM_GREEN_5",
            Command::TeamGreen6 => "TEAM_GREEN_6",
            Command::TeamGreen7 => "TEAM_GREEN_7",
            Command::TeamGreen8 => "TEAM_GREEN_8",
            Command::TeamMaxImbalance => "TEAM_MAX_IMBALANCE",
            Command::TeamMaxPlayers => "TEAM_MAX_PLAYERS",
            Command::TeamMinPlayers => "TEAM_MIN_PLAYERS",
            Command::TeamName1 => "TEAM_NAME_1",
            Command::TeamName2 => "TEAM_NAME_2",
            Command::TeamName3 => "TEAM_NAME_3",
            Command::TeamName4 => "TEAM_NAME_4",
            Command::TeamName5 => "TEAM_NAME_5",
            Command::TeamName6 => "TEAM_NAME_6",
            Command::TeamName7 => "TEAM_NAME_7",
            Command::TeamName8 => "TEAM_NAME_8",
            Command::TeamRed1 => "TEAM_RED_1",
            Command::TeamRed2 => "TEAM_RED_2",
            Command::TeamRed3 => "TEAM_RED_3",
            Command::TeamRed4 => "TEAM_RED_4",
            Command::TeamRed5 => "TEAM_RED_5",
            Command::TeamRed6 => "TEAM_RED_6",
            Command::TeamRed7 => "TEAM_RED_7",
            Command::TeamRed8 => "TEAM_RED_8",
            Command::TexturesHi => "TEXTURES_HI",
            Command::TextureMode0 => "TEXTURE_MODE_0",
            Command::TextureMode1 => "TEXTURE_MODE_1",
            Command::TextureMode2 => "TEXTURE_MODE_2",
            Command::TextureMode3 => "TEXTURE_MODE_3",
            Command::TextOut => "TEXT_OUT",
            Command::TimebotActionHigh => "TIMEBOT_ACTION_HIGH",
            Command::TimebotActionMax => "TIMEBOT_ACTION_MAX",
            Command::TimebotActionMedium => "TIMEBOT_ACTION_MEDIUM",
            Command::TimebotKickSeverity => "TIMEBOT_KICK_SEVERITY",
            Command::TimebotSensitivity => "TIMEBOT_SENSITIVITY",
            Command::TitleOfDay => "TITLE_OF_DAY",
            Command::ToggleSpectatorTooltip => "TOGGLE_SPECTATOR_TOOLTIP",
            Command::TopologyPolice => "TOPOLOGY_POLICE",
            Command::TopologyPoliceParallel => "TOPOLOGY_POLICE_PARALLEL",
            Command::TrustLan => "TRUST_LAN",
            Command::UnbanIp => "UNBAN_IP",
            Command::UnbanUser => "UNBAN_USER",
            Command::UnlockAllTeams => "UNLOCK_ALL_TEAMS",
            Command::Unsilence => "UNSILENCE",
            Command::Unsuspend => "UNSUSPEND",
            Command::UpperSky => "UPPER_SKY",
            Command::Url => "URL",
            Command::User1 => "USER_1",
            Command::User2 => "USER_2",
            Command::User3 => "USER_3",
            Command::User4 => "USER_4",
            Command::UserAlias => "USER_ALIAS",
            Command::UserLevel => "USER_LEVEL",
            Command::UserRemove => "USER_REMOVE",
            Command::UseDisplaylists => "USE_DISPLAYLISTS",
            Command::ViewportConf => "VIEWPORT_CONF",
            Command::ViewportToPlayer1 => "VIEWPORT_TO_PLAYER_1",
            Command::ViewportToPlayer2 => "VIEWPORT_TO_PLAYER_2",
            Command::ViewportToPlayer3 => "VIEWPORT_TO_PLAYER_3",
            Command::ViewportToPlayer4 => "VIEWPORT_TO_PLAYER_4",
            Command::Voice => "VOICE",
            Command::VotesCancel => "VOTES_CANCEL",
            Command::VotesSuspend => "VOTES_SUSPEND",
            Command::VotesSuspendDefault => "VOTES_SUSPEND_DEFAULT",
            Command::VotesUnsuspend => "VOTES_UNSUSPEND",
            Command::VoteKickReason => "VOTE_KICK_REASON",
            Command::VoteKickToPort => "VOTE_KICK_TO_PORT",
            Command::VoteKickToServer => "VOTE_KICK_TO_SERVER",
            Command::VoteUseServerControlledKick => "VOTE_USE_SERVER_CONTROLLED_KICK",
            Command::VotingBias => "VOTING_BIAS",
            Command::VotingBiasCommand => "VOTING_BIAS_COMMAND",
            Command::VotingBiasInclude => "VOTING_BIAS_INCLUDE",
            Command::VotingBiasKick => "VOTING_BIAS_KICK",
            Command::VotingBiasSilence => "VOTING_BIAS_SILENCE",
            Command::VotingBiasSuspend => "VOTING_BIAS_SUSPEND",
            Command::VotingBiasVoice => "VOTING_BIAS_VOICE",
            Command::VotingDecay => "VOTING_DECAY",
            Command::VotingHarmTime => "VOTING_HARM_TIME",
            Command::VotingKickMinharm => "VOTING_KICK_MINHARM",
            Command::VotingKickTime => "VOTING_KICK_TIME",
            Command::VotingMaturity => "VOTING_MATURITY",
            Command::VotingPrivacy => "VOTING_PRIVACY",
            Command::VotingSpamIssue => "VOTING_SPAM_ISSUE",
            Command::VotingSpamReject => "VOTING_SPAM_REJECT",
            Command::VotingStartDecay => "VOTING_START_DECAY",
            Command::VotingSuspendRounds => "VOTING_SUSPEND_ROUNDS",
            Command::VotingTimeout => "VOTING_TIMEOUT",
            Command::VotingTimeoutPerVoter => "VOTING_TIMEOUT_PER_VOTER",
            Command::WaitForExternalScript => "WAIT_FOR_EXTERNAL_SCRIPT",
            Command::WaitForExternalScriptTimeout => "WAIT_FOR_EXTERNAL_SCRIPT_TIMEOUT",
            Command::WallsLength => "WALLS_LENGTH",
            Command::WallsStayUpDelay => "WALLS_STAY_UP_DELAY",
            Command::WhitelistEnemiesIp => "WHITELIST_ENEMIES_IP",
            Command::WhitelistEnemiesUsername => "WHITELIST_ENEMIES_USERNAME",
            Command::WhiteSparks => "WHITE_SPARKS",
            Command::WinZoneDeaths => "WIN_ZONE_DEATHS",
            Command::WinZoneExpansion => "WIN_ZONE_EXPANSION",
            Command::WinZoneInitialSize => "WIN_ZONE_INITIAL_SIZE",
            Command::WinZoneMinLastDeath => "WIN_ZONE_MIN_LAST_DEATH",
            Command::WinZoneMinRoundTime => "WIN_ZONE_MIN_ROUND_TIME",
            Command::WinZoneRandomness => "WIN_ZONE_RANDOMNESS",
            Command::WordDelimiters => "WORD_DELIMITERS",
            Command::WrapMenu => "WRAP_MENU",
            Command::Zdepth => "ZDEPTH",
            Command::ZoneAlpha => "ZONE_ALPHA",
            Command::ZoneAlphaServer => "ZONE_ALPHA_SERVER",
            Command::ZoneAlphaToggle => "ZONE_ALPHA_TOGGLE",
            Command::ZoneBottom => "ZONE_BOTTOM",
            Command::ZoneHeight => "ZONE_HEIGHT",
            Command::ZoneSegments => "ZONE_SEGMENTS",
            Command::ZoneSegLength => "ZONE_SEG_LENGTH",
        };
        write!(f, "{}", word)
    }
}
