use std::fmt::Display;

pub enum Commands {
    AccessLevel,
    AccessLevelAnnounceLogin,
    AccessLevelAutokickImmunity,
    AccessLevelChat,
    AccessLevelChatTimeout,
    AccessLevelHideOf,
    AccessLevelHideTo,
    AccessLevelIps,
    AccessLevelListAdmins,
    AccessLevelListAdminsSeeEveryone,
    AccessLevelNver,
    AccessLevelPlay,
    AccessLevelPlaySliders,
    AccessLevelPlaySliding,
    AccessLevelRtfm,
    AccessLevelShout,
    AccessLevelShuffleUp,
    AccessLevelSpyMsg,
    AccessLevelSpyTeam,
    AccessLevelVoteCommand,
    AccessLevelVoteCommandExecute,
    AccessLevelVoteInclude,
    AccessLevelVoteIncludeExecute,
    AccessLevelVoteKick,
    AccessLevelVoteSilence,
    AccessLevelVoteSuspend,
    AddHelpTopic,
    AddMasterServer,
    Admins,
    AdminListColorsBestBlue,
    AdminListColorsBestGreen,
    AdminListColorsBestRed,
    AdminListColorsWorstBlue,
    AdminListColorsWorstGreen,
    AdminListColorsWorstRed,
    AdminListMinAccessLevel,
    AiIq,
    AliveLocx,
    AliveLocy,
    AliveSize,
    AllowCam1_0,
    AllowCam1_1,
    AllowCam1_2,
    AllowCam1_3,
    AllowCam1_4,
    AllowCam1_5,
    AllowCam1_6,
    AllowCam2_0,
    AllowCam2_1,
    AllowCam2_2,
    AllowCam2_3,
    AllowCam2_4,
    AllowCam2_5,
    AllowCam2_6,
    AllowCam3_0,
    AllowCam3_1,
    AllowCam3_2,
    AllowCam3_3,
    AllowCam3_4,
    AllowCam3_5,
    AllowCam3_6,
    AllowCam4_0,
    AllowCam4_1,
    AllowCam4_2,
    AllowCam4_3,
    AllowCam4_4,
    AllowCam4_5,
    AllowCam4_6,
    AllowControlDuringChat,
    AllowEnemiesSameClient,
    AllowEnemiesSameIp,
    AllowImposters,
    AllowImpostors,
    AllowRenamePlayer,
    AllowTeamChange,
    AllowTeamChangePlayer,
    AllowTeamNameColor,
    AllowTeamNamePlayer,
    AllowVoting,
    AllowVotingSpectator,
    AlphaBlend,
    AntiSpoof,
    ArenaAxes,
    ArenaAxesOverride,
    ArmagetronLastScreenmode,
    ArmagetronLastWindowsize,
    ArmagetronScreenmode,
    ArmagetronVsync,
    ArmagetronVsyncLast,
    ArmagetronWindowsize,
    AuthorityBlacklist,
    AuthorityLevel,
    AuthorityWhitelist,
    AutoAis,
    AutoIncam1,
    AutoIncam2,
    AutoIncam3,
    AutoIncam4,
    AutoIq,
    AutoLogin1,
    AutoLogin2,
    AutoLogin3,
    AutoLogin4,
    AutoTeam,
    AutoTeamSpecSpam,
    AxesIndicator,
    BackwardCompatibility,
    Ban,
    BanIp,
    BanList,
    BanUser,
    BanUserList,
    BigBrother,
    Bookmark0Address,
    Bookmark0Name,
    Bookmark0Port,
    Bookmark10Address,
    Bookmark10Name,
    Bookmark10Port,
    Bookmark1Address,
    Bookmark1Name,
    Bookmark1Port,
    Bookmark2Address,
    Bookmark2Name,
    Bookmark2Port,
    Bookmark3Address,
    Bookmark3Name,
    Bookmark3Port,
    Bookmark4Address,
    Bookmark4Name,
    Bookmark4Port,
    Bookmark5Address,
    Bookmark5Name,
    Bookmark5Port,
    Bookmark6Address,
    Bookmark6Name,
    Bookmark6Port,
    Bookmark7Address,
    Bookmark7Name,
    Bookmark7Port,
    Bookmark8Address,
    Bookmark8Name,
    Bookmark8Port,
    Bookmark9Address,
    Bookmark9Name,
    Bookmark9Port,
    BookmarkMaster0Address,
    BookmarkMaster0Name,
    BookmarkMaster0Port,
    BookmarkMaster10Address,
    BookmarkMaster10Name,
    BookmarkMaster10Port,
    BookmarkMaster1Address,
    BookmarkMaster1Name,
    BookmarkMaster1Port,
    BookmarkMaster2Address,
    BookmarkMaster2Name,
    BookmarkMaster2Port,
    BookmarkMaster3Address,
    BookmarkMaster3Name,
    BookmarkMaster3Port,
    BookmarkMaster4Address,
    BookmarkMaster4Name,
    BookmarkMaster4Port,
    BookmarkMaster5Address,
    BookmarkMaster5Name,
    BookmarkMaster5Port,
    BookmarkMaster6Address,
    BookmarkMaster6Name,
    BookmarkMaster6Port,
    BookmarkMaster7Address,
    BookmarkMaster7Name,
    BookmarkMaster7Port,
    BookmarkMaster8Address,
    BookmarkMaster8Name,
    BookmarkMaster8Port,
    BookmarkMaster9Address,
    BookmarkMaster9Name,
    BookmarkMaster9Port,
    BrakeGaugeLocx,
    BrakeGaugeLocy,
    BrakeGaugeSize,
    BugColorOverflow,
    BugRip,
    BugTransparency,
    BugTransparencyDemand,
    BugTunnel,
    Camcenter1,
    Camcenter2,
    Camcenter3,
    Camcenter4,
    CameraCustomBack,
    CameraCustomBackFromspeed,
    CameraCustomPitch,
    CameraCustomRise,
    CameraCustomRiseFromspeed,
    CameraCustomTurnSpeed,
    CameraCustomTurnSpeed180,
    CameraCustomZoom,
    CameraFollowStartX,
    CameraFollowStartY,
    CameraFollowStartZ,
    CameraForbidCustom,
    CameraForbidCustomGlance,
    CameraForbidFollow,
    CameraForbidFree,
    CameraForbidIn,
    CameraForbidServerCustom,
    CameraForbidSmart,
    CameraFreeStartX,
    CameraFreeStartY,
    CameraFreeStartZ,
    CameraGlanceBack,
    CameraGlanceBackFromspeed,
    CameraGlancePitch,
    CameraGlanceRise,
    CameraGlanceRiseFromspeed,
    CameraInTurnSpeed,
    CameraOverrideCustomGlance,
    CameraOverrideCustomGlanceServerCustom,
    CameraServerCustomBack,
    CameraServerCustomBackFromspeed,
    CameraServerCustomPitch,
    CameraServerCustomRise,
    CameraServerCustomRiseFromspeed,
    CameraServerCustomTurnSpeed,
    CameraServerCustomTurnSpeed180,
    CameraServerGlanceBack,
    CameraServerGlanceBackFromspeed,
    CameraServerGlancePitch,
    CameraServerGlanceRise,
    CameraServerGlanceRiseFromspeed,
    CameraSmartStartX,
    CameraSmartStartY,
    CameraSmartStartZ,
    CameraVisibilityClipSpeed,
    CameraVisibilityExtension,
    CameraVisibilityLowerWall,
    CameraVisibilityLowerWallSmart,
    CameraVisibilityRecoverySpeed,
    CameraVisibilitySideskew,
    CameraVisibilityWallDistance,
    Camwobble1,
    Camwobble2,
    Camwobble3,
    Camwobble4,
    Casacl,
    CenterMessage,
    ChatbotAlwaysActive,
    ChatbotDecay,
    ChatbotDelay,
    ChatbotMinTimestep,
    ChatbotNewWallBlindness,
    ChatbotRange,
    ChatterRemoveTime,
    ChatLog,
    ChatTooltip,
    CheckErrors,
    ClientPort,
    CmLocy,
    Colordepth,
    ColorB1,
    ColorB2,
    ColorB3,
    ColorB4,
    ColorG1,
    ColorG2,
    ColorG3,
    ColorG4,
    ColorR1,
    ColorR2,
    ColorR3,
    ColorR4,
    ColorStrings,
    ConnectionFloodSensitivity,
    ConnectionLimit,
    ConsoleColumns,
    ConsoleIndent,
    ConsoleLadderLog,
    ConsoleLog,
    ConsoleMessage,
    ConsoleRows,
    ConsoleRowsMax,
    CustomScreenAspect,
    CustomScreenHeight,
    CustomScreenWidth,
    CustomServerName,
    CycleAccel,
    CycleAccelEnemy,
    CycleAccelEnemyOverride,
    CycleAccelOffset,
    CycleAccelRim,
    CycleAccelRimOverride,
    CycleAccelSelf,
    CycleAccelSelfOverride,
    CycleAccelSlingshot,
    CycleAccelSlingshotOverride,
    CycleAccelTeam,
    CycleAccelTeamOverride,
    CycleAccelTunnel,
    CycleAccelTunnelOverride,
    CycleAvoidOldclientBadSync,
    CycleBlinkFrequency,
    CycleBoostfactorEnemy,
    CycleBoostfactorEnemyOverride,
    CycleBoostfactorRim,
    CycleBoostfactorRimOverride,
    CycleBoostfactorSelf,
    CycleBoostfactorSelfOverride,
    CycleBoostfactorTeam,
    CycleBoostfactorTeamOverride,
    CycleBoostEnemy,
    CycleBoostEnemyOverride,
    CycleBoostRim,
    CycleBoostRimOverride,
    CycleBoostSelf,
    CycleBoostSelfOverride,
    CycleBoostTeam,
    CycleBoostTeamOverride,
    CycleBrake,
    CycleBrakeDeplete,
    CycleBrakeDepleteOverride,
    CycleBrakeRefill,
    CycleBrakeRefillOverride,
    CycleBrakeTooltip,
    CycleDelay,
    CycleDelayDoublebindBonus,
    CycleDelayDoublebindBonusOverride,
    CycleDelayTimebased,
    CycleDelayTimebasedOverride,
    CycleDistWallShrink,
    CycleDistWallShrinkOffset,
    CycleFairAntilag,
    CycleFirstSpawnProtection,
    CycleInvulnerableTime,
    CycleMaxRefcount,
    CyclePacketlossTolerance,
    CyclePingRubber,
    CycleRubber,
    CycleRubberDelay,
    CycleRubberDelayBonus,
    CycleRubberDelayBonusOverride,
    CycleRubberDelayOverride,
    CycleRubberLegacy,
    CycleRubberMalusTurnOverride,
    CycleRubberMinadjust,
    CycleRubberMinadjustOverride,
    CycleRubberMindistance,
    CycleRubberMindistanceGap,
    CycleRubberMindistanceGapBackdoor,
    CycleRubberMindistanceGapBackdoorOverride,
    CycleRubberMindistanceGapOverride,
    CycleRubberMindistanceGapSide,
    CycleRubberMindistanceLegacy,
    CycleRubberMindistanceOverride,
    CycleRubberMindistancePreparation,
    CycleRubberMindistancePreparationOverride,
    CycleRubberMindistanceRatio,
    CycleRubberMindistanceRatioOverride,
    CycleRubberMindistanceReservoir,
    CycleRubberMindistanceReservoirOverride,
    CycleRubberMindistanceUnprepared,
    CycleRubberMindistanceUnpreparedOverride,
    CycleRubberSpeed,
    CycleRubberSpeedOverride,
    CycleRubberTime,
    CycleRubberTimebased,
    CycleRubberTimebasedOverride,
    CycleRubberTimeOverride,
    CycleRubberWallShrink,
    CycleRubberWallShrinkOverride,
    CycleSmoothMinSpeed,
    CycleSmoothThreshold,
    CycleSmoothTime,
    CycleSoundSpeed,
    CycleSpeed,
    CycleSpeedDecayAbove,
    CycleSpeedDecayAboveOverride,
    CycleSpeedDecayBelow,
    CycleSpeedDecayBelowOverride,
    CycleSpeedMax,
    CycleSpeedMaxOverride,
    CycleSpeedMin,
    CycleSpeedMinOverride,
    CycleStartSpeed,
    CycleSyncFf,
    CycleSyncFfSteps,
    CycleSyncIntervalEnemy,
    CycleSyncIntervalSelf,
    CycleTimeTolerance,
    CycleTimeToleranceOverride,
    CycleTurnLeftTooltip,
    CycleTurnMemory,
    CycleTurnRightTooltip,
    CycleTurnSpeedFactor,
    CycleTurnSpeedFactorOverride,
    CycleWallNear,
    CycleWallTime,
    CycleWidth,
    CycleWidthOverride,
    CycleWidthRubberMax,
    CycleWidthRubberMaxOverride,
    CycleWidthRubberMin,
    CycleWidthRubberMinOverride,
    CycleWidthSide,
    CycleWidthSideOverride,
    DeclareRoundWinner,
    DedicatedIdle,
    DefaultKickReason,
    DefaultKickToPort,
    DefaultKickToReason,
    DefaultKickToServer,
    DefaultShoutPlayer,
    DefaultShoutSpectator,
    DisallowRenamePlayer,
    DisallowTeamChangePlayer,
    Dither,
    DoublebindTime,
    DoublebindTimeOverride,
    EnableChat,
    EnableFriends,
    EnemyChatbotPenalty,
    EnemyCurrenttimeInfluence,
    EnemyDeadPenalty,
    EnemySuicideTimeout,
    EnemyTeammatePenalty,
    ExpectAckOnClientPlayback,
    Explosion,
    ExplosionRadius,
    ExtraRoundTime,
    FadeoutNameDelay,
    FailedAttempts,
    FastestLocx,
    FastestLocy,
    FastestSize,
    FastForwardMaxstep,
    FastForwardMaxstepReal,
    FastForwardMaxstepRel,
    FavNumPerTeamPlayer1,
    FavNumPerTeamPlayer2,
    FavNumPerTeamPlayer3,
    FavNumPerTeamPlayer4,
    FilterColorNames,
    FilterColorServerNames,
    FilterColorStrings,
    FilterColorTeam,
    FilterDarkColorNames,
    FilterDarkColorServerNames,
    FilterDarkColorStrings,
    FilterDarkColorTeam,
    FilterNameEnds,
    FilterNameMiddle,
    FinishType,
    FirstUse,
    FloorBlue,
    FloorDetail,
    FloorGreen,
    FloorMirror,
    FloorMirrorInt,
    FloorRed,
    FontSmallThresholdHeight,
    FontSmallThresholdWidth,
    ForceTurtleMode,
    FortressCollapseSpeed,
    FortressConquestDecayRate,
    FortressConquestRate,
    FortressConquestTimeout,
    FortressDefendRate,
    FortressHeldScore,
    Friend1,
    Friend10,
    Friend2,
    Friend3,
    Friend4,
    Friend5,
    Friend6,
    Friend7,
    Friend8,
    Friend9,
    Fullscreen,
    FullscreenMessage,
    GameTimeout,
    GameType,
    GlanceBackTooltip,
    GlanceLeftTooltip,
    GlanceRightTooltip,
    GlobalId,
    GlExtensions,
    GlRenderer,
    GlVendor,
    GlVersion,
    GridSize,
    GridSizeMoviepack,
    HashMethodBlacklist,
    HelpIntroductoryBlurb,
    HideIdentity1,
    HideIdentity2,
    HideIdentity3,
    HideIdentity4,
    HighRim,
    HistorySizeChat,
    HistorySizeConsole,
    HudCacheThreshold,
    HudMaxWidth,
    IdleKickTime,
    IdleRemoveTime,
    Include,
    InfinityPlane,
    IngameMenuTooltip,
    InstantChatString1_1,
    InstantChatString1_10,
    InstantChatString1_11,
    InstantChatString1_12,
    InstantChatString1_13,
    InstantChatString1_14,
    InstantChatString1_15,
    InstantChatString1_16,
    InstantChatString1_17,
    InstantChatString1_18,
    InstantChatString1_19,
    InstantChatString1_2,
    InstantChatString1_20,
    InstantChatString1_21,
    InstantChatString1_22,
    InstantChatString1_23,
    InstantChatString1_24,
    InstantChatString1_25,
    InstantChatString1_3,
    InstantChatString1_4,
    InstantChatString1_5,
    InstantChatString1_6,
    InstantChatString1_7,
    InstantChatString1_8,
    InstantChatString1_9,
    InstantChatString2_1,
    InstantChatString2_10,
    InstantChatString2_11,
    InstantChatString2_12,
    InstantChatString2_13,
    InstantChatString2_14,
    InstantChatString2_15,
    InstantChatString2_16,
    InstantChatString2_17,
    InstantChatString2_18,
    InstantChatString2_19,
    InstantChatString2_2,
    InstantChatString2_20,
    InstantChatString2_21,
    InstantChatString2_22,
    InstantChatString2_23,
    InstantChatString2_24,
    InstantChatString2_25,
    InstantChatString2_3,
    InstantChatString2_4,
    InstantChatString2_5,
    InstantChatString2_6,
    InstantChatString2_7,
    InstantChatString2_8,
    InstantChatString2_9,
    InstantChatString3_1,
    InstantChatString3_10,
    InstantChatString3_11,
    InstantChatString3_12,
    InstantChatString3_13,
    InstantChatString3_14,
    InstantChatString3_15,
    InstantChatString3_16,
    InstantChatString3_17,
    InstantChatString3_18,
    InstantChatString3_19,
    InstantChatString3_2,
    InstantChatString3_20,
    InstantChatString3_21,
    InstantChatString3_22,
    InstantChatString3_23,
    InstantChatString3_24,
    InstantChatString3_25,
    InstantChatString3_3,
    InstantChatString3_4,
    InstantChatString3_5,
    InstantChatString3_6,
    InstantChatString3_7,
    InstantChatString3_8,
    InstantChatString3_9,
    InstantChatString4_1,
    InstantChatString4_10,
    InstantChatString4_11,
    InstantChatString4_12,
    InstantChatString4_13,
    InstantChatString4_14,
    InstantChatString4_15,
    InstantChatString4_16,
    InstantChatString4_17,
    InstantChatString4_18,
    InstantChatString4_19,
    InstantChatString4_2,
    InstantChatString4_20,
    InstantChatString4_21,
    InstantChatString4_22,
    InstantChatString4_23,
    InstantChatString4_24,
    InstantChatString4_25,
    InstantChatString4_3,
    InstantChatString4_4,
    InstantChatString4_5,
    InstantChatString4_6,
    InstantChatString4_7,
    InstantChatString4_8,
    InstantChatString4_9,
    KeepPlayerSlot,
    KeepWindowActive,
    Keyboard,
    Kick,
    KickTo,
    Kill,
    LadderlogDecorateTimestamp,
    LadderlogGameTimeInterval,
    LadderlogWriteAll,
    LadderlogWriteAuthorityBlurb,
    LadderlogWriteBasezoneConquered,
    LadderlogWriteBasezoneConquerer,
    LadderlogWriteChat,
    LadderlogWriteDeathFrag,
    LadderlogWriteDeathSuicide,
    LadderlogWriteDeathTeamkill,
    LadderlogWriteEncoding,
    LadderlogWriteGameEnd,
    LadderlogWriteGameTime,
    LadderlogWriteMatchWinner,
    LadderlogWriteNewMatch,
    LadderlogWriteNewRound,
    LadderlogWriteNumHumans,
    LadderlogWriteOnlinePlayer,
    LadderlogWritePlayerEntered,
    LadderlogWritePlayerLeft,
    LadderlogWritePlayerRenamed,
    LadderlogWritePositions,
    LadderlogWriteRoundScore,
    LadderlogWriteRoundScoreTeam,
    LadderlogWriteRoundWinner,
    LadderlogWriteSacrifice,
    LadderlogWriteTeamCreated,
    LadderlogWriteTeamDestroyed,
    LadderlogWriteTeamPlayerAdded,
    LadderlogWriteTeamPlayerRemoved,
    LadderlogWriteTeamRenamed,
    LadderlogWriteWaitForExternalScript,
    LadderGainExtra,
    LadderLoseMinOnLoad,
    LadderLosePercentOnLoad,
    LadderMinBet,
    LadderPercentBet,
    LadderTax,
    LagCredit,
    LagCreditSingle,
    LagCreditTime,
    LagCreditVariance,
    LagFastTime,
    LagFastWeight,
    LagFrequencyThreshold,
    LagMaxSpeedupTimer,
    LagOffsetClient,
    LagOffsetLegacy,
    LagOffsetServer,
    LagOMeter,
    LagOMeterBlend,
    LagOMeterScale,
    LagOMeterThreshold,
    LagOMeterUseOld,
    LagSlowTime,
    LagSlowWeight,
    LagSweetSpot,
    LagThreshold,
    LanguageFirst,
    LanguageSecond,
    LastChatBreakTime,
    LastCheckErrors,
    LastColordepth,
    LastFullscreen,
    LastZdepth,
    LegacyLogNames,
    LimitRounds,
    LimitScore,
    LimitTime,
    LocalTeam,
    LocalUser,
    LowerSky,
    MapFile,
    MapFileOverride,
    MapUri,
    MaxClients,
    MaxClientsSameIpHard,
    MaxClientsSameIpSoft,
    MaxInRate,
    MaxOutRate,
    MaxPlayersSameIp,
    MaxProtocolVersion,
    MaxVotes,
    MaxVotesPerVoter,
    Md5Prefix,
    Md5Suffix,
    MessageOfDay,
    MessageOfDayTimeout,
    MinPlayers,
    MinPlayTimeOnline,
    MinPlayTimeTeam,
    MinPlayTimeTotal,
    MinProtocolVersion,
    MinVoters,
    MouseGrab,
    MoveTo,
    Moviepack,
    MoviepackFloorBlue,
    MoviepackFloorGreen,
    MoviepackFloorRed,
    MoviepackRimWallStretchX,
    MoviepackRimWallStretchY,
    MoviepackWallStretch,
    NameTeamAfterPlayer1,
    NameTeamAfterPlayer2,
    NameTeamAfterPlayer3,
    NameTeamAfterPlayer4,
    NetworkAutobanFactor,
    NetworkAutobanMaxKph,
    NetworkAutobanOffset,
    NetworkMinBan,
    NetworkSpectatorTime,
    NewFeatureDelay,
    NewTeamAllowed,
    NumAis,
    Password,
    PasswordStorage,
    PingCharity,
    PingCharityMax,
    PingCharityMin,
    PingCharityServer,
    PingFloodGlobal,
    PingFloodTime10,
    PingFloodTime100,
    PingFloodTime20,
    PingFloodTime50,
    PingLocx,
    PingLocy,
    PingSize,
    Players,
    Player1,
    Player2,
    Player3,
    Player4,
    PlayerChatWaitFraction,
    PlayerChatWaitMax,
    PlayerChatWaitSingle,
    PlayerChatWaitTeamleader,
    PlayerListHiddenPlayerPrefix,
    PlayerMessage,
    PlayerRandomColor,
    PlayTimeOnline,
    PlayTimeTeam,
    PlayTimeTotal,
    PngScreenshot,
    PredictObjects,
    PrefixSpamEnable,
    PrefixSpamLengthMultiplier,
    PrefixSpamNumberColorCodesMultiplier,
    PrefixSpamNumberKnownPrefixesMultiplier,
    PrefixSpamRequiredScore,
    PrefixSpamStartColorMultiplier,
    PrefixSpamTimeoutMultiplier,
    ProtectSensitiveFiles,
    RealArenaSizeFactor,
    RealCycleSpeedFactor,
    RecordingDebuglevel,
    RecordTurtleMode,
    RemoveHelpTopic,
    Rename,
    ReserveScreenName,
    ResourceRepositoryClient,
    ResourceRepositoryServer,
    RimWallStretchX,
    RimWallStretchY,
    RimWallWrapY,
    Rinclude,
    RoundCenterMessage,
    RoundConsoleMessage,
    RubberGaugeLocx,
    RubberGaugeLocy,
    RubberGaugeSize,
    SavedInVersion,
    Say,
    ScoreDeathzone,
    ScoreDie,
    ScoreHole,
    ScoreKill,
    ScoreLocx,
    ScoreLocy,
    ScoreSize,
    ScoreSuicide,
    ScoreSurvive,
    ScoreWin,
    ServerDns,
    ServerIp,
    ServerName,
    ServerPort,
    SettingLegacyBehaviorAnnoying,
    SettingLegacyBehaviorBreaking,
    SettingLegacyBehaviorBumpy,
    SettingLegacyBehaviorCheating,
    SettingLegacyBehaviorVisual,
    ShowAlive,
    ShowBrake,
    ShowFastest,
    ShowFps,
    ShowHud,
    ShowOwnIp,
    ShowOwnName,
    ShowPing,
    ShowRecordingTime,
    ShowRubber,
    ShowScore,
    ShowSpeed,
    ShowTime,
    ShowTime24,
    ShuffleSpamMessagesPerRound,
    Silence,
    SilenceDefault,
    SimpleTrail,
    Sinclude,
    SizeFactor,
    SkyWobble,
    Slap,
    SmartGlanceCustom1,
    SmartGlanceCustom2,
    SmartGlanceCustom3,
    SmartGlanceCustom4,
    SmoothShading,
    SoftwareRenderer,
    SoundBufferShift,
    SoundQuality,
    SoundSources,
    SpamAutokick,
    SpamAutokickCount,
    SpamMaxlen,
    SpamMaxlenOverride,
    SpamPenalty,
    SpamProtection,
    SpamProtectionChat,
    SpamProtectionRepeat,
    SpamProtectionVote,
    Sparks,
    SpawnWingmenBack,
    SpawnWingmenSide,
    SpectatorMode1,
    SpectatorMode2,
    SpectatorMode3,
    SpectatorMode4,
    SpeedFactor,
    SpeedGaugeLocx,
    SpeedGaugeLocy,
    SpeedGaugeSize,
    SpAiIq,
    SpAutoAis,
    SpAutoIq,
    SpExplosionRadius,
    SpFinishType,
    SpGameType,
    SpLimitRounds,
    SpLimitScore,
    SpLimitTime,
    SpMinPlayers,
    SpNumAis,
    SpScoreWin,
    SpSizeFactor,
    SpSpeedFactor,
    SpTeamsMax,
    SpTeamsMin,
    SpTeamBalanceOnQuit,
    SpTeamBalanceWithAis,
    SpTeamMaxImbalance,
    SpTeamMaxPlayers,
    SpTeamMinPlayers,
    SpWallsLength,
    SpWallsStayUpDelay,
    SpWinZoneMinLastDeath,
    SpWinZoneMinRoundTime,
    StartCam1,
    StartCam2,
    StartCam3,
    StartCam4,
    StartFov1,
    StartFov2,
    StartFov3,
    StartFov4,
    StartNewMatch,
    StopRecording,
    Suspend,
    SuspendDefaultRounds,
    SwapMode,
    SwitchViewTooltip,
    TalkToMaster,
    Teams,
    TeamsMax,
    TeamsMin,
    TeamBalanceOnQuit,
    TeamBalanceWithAis,
    TeamBlue1,
    TeamBlue2,
    TeamBlue3,
    TeamBlue4,
    TeamBlue5,
    TeamBlue6,
    TeamBlue7,
    TeamBlue8,
    TeamCenterIsBoss,
    TeamEliminationMode,
    TeamGreen1,
    TeamGreen2,
    TeamGreen3,
    TeamGreen4,
    TeamGreen5,
    TeamGreen6,
    TeamGreen7,
    TeamGreen8,
    TeamMaxImbalance,
    TeamMaxPlayers,
    TeamMinPlayers,
    TeamName1,
    TeamName2,
    TeamName3,
    TeamName4,
    TeamName5,
    TeamName6,
    TeamName7,
    TeamName8,
    TeamRed1,
    TeamRed2,
    TeamRed3,
    TeamRed4,
    TeamRed5,
    TeamRed6,
    TeamRed7,
    TeamRed8,
    TexturesHi,
    TextureMode0,
    TextureMode1,
    TextureMode2,
    TextureMode3,
    TextOut,
    TimebotActionHigh,
    TimebotActionMax,
    TimebotActionMedium,
    TimebotKickSeverity,
    TimebotSensitivity,
    TitleOfDay,
    ToggleSpectatorTooltip,
    TopologyPolice,
    TopologyPoliceParallel,
    TrustLan,
    UnbanIp,
    UnbanUser,
    UnlockAllTeams,
    Unsilence,
    Unsuspend,
    UpperSky,
    Url,
    User1,
    User2,
    User3,
    User4,
    UserAlias,
    UserLevel,
    UserRemove,
    UseDisplaylists,
    ViewportConf,
    ViewportToPlayer1,
    ViewportToPlayer2,
    ViewportToPlayer3,
    ViewportToPlayer4,
    Voice,
    VotesCancel,
    VotesSuspend,
    VotesSuspendDefault,
    VotesUnsuspend,
    VoteKickReason,
    VoteKickToPort,
    VoteKickToServer,
    VoteUseServerControlledKick,
    VotingBias,
    VotingBiasCommand,
    VotingBiasInclude,
    VotingBiasKick,
    VotingBiasSilence,
    VotingBiasSuspend,
    VotingBiasVoice,
    VotingDecay,
    VotingHarmTime,
    VotingKickMinharm,
    VotingKickTime,
    VotingMaturity,
    VotingPrivacy,
    VotingSpamIssue,
    VotingSpamReject,
    VotingStartDecay,
    VotingSuspendRounds,
    VotingTimeout,
    VotingTimeoutPerVoter,
    WaitForExternalScript,
    WaitForExternalScriptTimeout,
    WallsLength,
    WallsStayUpDelay,
    WhitelistEnemiesIp,
    WhitelistEnemiesUsername,
    WhiteSparks,
    WinZoneDeaths,
    WinZoneExpansion,
    WinZoneInitialSize,
    WinZoneMinLastDeath,
    WinZoneMinRoundTime,
    WinZoneRandomness,
    WordDelimiters,
    WrapMenu,
    Zdepth,
    ZoneAlpha,
    ZoneAlphaServer,
    ZoneAlphaToggle,
    ZoneBottom,
    ZoneHeight,
    ZoneSegments,
    ZoneSegLength,
}

impl Display for Commands {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let word = match self {
            Commands::AccessLevel => "ACCESS_LEVEL",
            Commands::AccessLevelAnnounceLogin => "ACCESS_LEVEL_ANNOUNCE_LOGIN",
            Commands::AccessLevelAutokickImmunity => "ACCESS_LEVEL_AUTOKICK_IMMUNITY",
            Commands::AccessLevelChat => "ACCESS_LEVEL_CHAT",
            Commands::AccessLevelChatTimeout => "ACCESS_LEVEL_CHAT_TIMEOUT",
            Commands::AccessLevelHideOf => "ACCESS_LEVEL_HIDE_OF",
            Commands::AccessLevelHideTo => "ACCESS_LEVEL_HIDE_TO",
            Commands::AccessLevelIps => "ACCESS_LEVEL_IPS",
            Commands::AccessLevelListAdmins => "ACCESS_LEVEL_LIST_ADMINS",
            Commands::AccessLevelListAdminsSeeEveryone => "ACCESS_LEVEL_LIST_ADMINS_SEE_EVERYONE",
            Commands::AccessLevelNver => "ACCESS_LEVEL_NVER",
            Commands::AccessLevelPlay => "ACCESS_LEVEL_PLAY",
            Commands::AccessLevelPlaySliders => "ACCESS_LEVEL_PLAY_SLIDERS",
            Commands::AccessLevelPlaySliding => "ACCESS_LEVEL_PLAY_SLIDING",
            Commands::AccessLevelRtfm => "ACCESS_LEVEL_RTFM",
            Commands::AccessLevelShout => "ACCESS_LEVEL_SHOUT",
            Commands::AccessLevelShuffleUp => "ACCESS_LEVEL_SHUFFLE_UP",
            Commands::AccessLevelSpyMsg => "ACCESS_LEVEL_SPY_MSG",
            Commands::AccessLevelSpyTeam => "ACCESS_LEVEL_SPY_TEAM",
            Commands::AccessLevelVoteCommand => "ACCESS_LEVEL_VOTE_COMMAND",
            Commands::AccessLevelVoteCommandExecute => "ACCESS_LEVEL_VOTE_COMMAND_EXECUTE",
            Commands::AccessLevelVoteInclude => "ACCESS_LEVEL_VOTE_INCLUDE",
            Commands::AccessLevelVoteIncludeExecute => "ACCESS_LEVEL_VOTE_INCLUDE_EXECUTE",
            Commands::AccessLevelVoteKick => "ACCESS_LEVEL_VOTE_KICK",
            Commands::AccessLevelVoteSilence => "ACCESS_LEVEL_VOTE_SILENCE",
            Commands::AccessLevelVoteSuspend => "ACCESS_LEVEL_VOTE_SUSPEND",
            Commands::AddHelpTopic => "ADD_HELP_TOPIC",
            Commands::AddMasterServer => "ADD_MASTER_SERVER",
            Commands::Admins => "ADMINS",
            Commands::AdminListColorsBestBlue => "ADMIN_LIST_COLORS_BEST_BLUE",
            Commands::AdminListColorsBestGreen => "ADMIN_LIST_COLORS_BEST_GREEN",
            Commands::AdminListColorsBestRed => "ADMIN_LIST_COLORS_BEST_RED",
            Commands::AdminListColorsWorstBlue => "ADMIN_LIST_COLORS_WORST_BLUE",
            Commands::AdminListColorsWorstGreen => "ADMIN_LIST_COLORS_WORST_GREEN",
            Commands::AdminListColorsWorstRed => "ADMIN_LIST_COLORS_WORST_RED",
            Commands::AdminListMinAccessLevel => "ADMIN_LIST_MIN_ACCESS_LEVEL",
            Commands::AiIq => "AI_IQ",
            Commands::AliveLocx => "ALIVE_LOCX",
            Commands::AliveLocy => "ALIVE_LOCY",
            Commands::AliveSize => "ALIVE_SIZE",
            Commands::AllowCam1_0 => "ALLOW_CAM_1_0",
            Commands::AllowCam1_1 => "ALLOW_CAM_1_1",
            Commands::AllowCam1_2 => "ALLOW_CAM_1_2",
            Commands::AllowCam1_3 => "ALLOW_CAM_1_3",
            Commands::AllowCam1_4 => "ALLOW_CAM_1_4",
            Commands::AllowCam1_5 => "ALLOW_CAM_1_5",
            Commands::AllowCam1_6 => "ALLOW_CAM_1_6",
            Commands::AllowCam2_0 => "ALLOW_CAM_2_0",
            Commands::AllowCam2_1 => "ALLOW_CAM_2_1",
            Commands::AllowCam2_2 => "ALLOW_CAM_2_2",
            Commands::AllowCam2_3 => "ALLOW_CAM_2_3",
            Commands::AllowCam2_4 => "ALLOW_CAM_2_4",
            Commands::AllowCam2_5 => "ALLOW_CAM_2_5",
            Commands::AllowCam2_6 => "ALLOW_CAM_2_6",
            Commands::AllowCam3_0 => "ALLOW_CAM_3_0",
            Commands::AllowCam3_1 => "ALLOW_CAM_3_1",
            Commands::AllowCam3_2 => "ALLOW_CAM_3_2",
            Commands::AllowCam3_3 => "ALLOW_CAM_3_3",
            Commands::AllowCam3_4 => "ALLOW_CAM_3_4",
            Commands::AllowCam3_5 => "ALLOW_CAM_3_5",
            Commands::AllowCam3_6 => "ALLOW_CAM_3_6",
            Commands::AllowCam4_0 => "ALLOW_CAM_4_0",
            Commands::AllowCam4_1 => "ALLOW_CAM_4_1",
            Commands::AllowCam4_2 => "ALLOW_CAM_4_2",
            Commands::AllowCam4_3 => "ALLOW_CAM_4_3",
            Commands::AllowCam4_4 => "ALLOW_CAM_4_4",
            Commands::AllowCam4_5 => "ALLOW_CAM_4_5",
            Commands::AllowCam4_6 => "ALLOW_CAM_4_6",
            Commands::AllowControlDuringChat => "ALLOW_CONTROL_DURING_CHAT",
            Commands::AllowEnemiesSameClient => "ALLOW_ENEMIES_SAME_CLIENT",
            Commands::AllowEnemiesSameIp => "ALLOW_ENEMIES_SAME_IP",
            Commands::AllowImposters => "ALLOW_IMPOSTERS",
            Commands::AllowImpostors => "ALLOW_IMPOSTORS",
            Commands::AllowRenamePlayer => "ALLOW_RENAME_PLAYER",
            Commands::AllowTeamChange => "ALLOW_TEAM_CHANGE",
            Commands::AllowTeamChangePlayer => "ALLOW_TEAM_CHANGE_PLAYER",
            Commands::AllowTeamNameColor => "ALLOW_TEAM_NAME_COLOR",
            Commands::AllowTeamNamePlayer => "ALLOW_TEAM_NAME_PLAYER",
            Commands::AllowVoting => "ALLOW_VOTING",
            Commands::AllowVotingSpectator => "ALLOW_VOTING_SPECTATOR",
            Commands::AlphaBlend => "ALPHA_BLEND",
            Commands::AntiSpoof => "ANTI_SPOOF",
            Commands::ArenaAxes => "ARENA_AXES",
            Commands::ArenaAxesOverride => "ARENA_AXES_OVERRIDE",
            Commands::ArmagetronLastScreenmode => "ARMAGETRON_LAST_SCREENMODE",
            Commands::ArmagetronLastWindowsize => "ARMAGETRON_LAST_WINDOWSIZE",
            Commands::ArmagetronScreenmode => "ARMAGETRON_SCREENMODE",
            Commands::ArmagetronVsync => "ARMAGETRON_VSYNC",
            Commands::ArmagetronVsyncLast => "ARMAGETRON_VSYNC_LAST",
            Commands::ArmagetronWindowsize => "ARMAGETRON_WINDOWSIZE",
            Commands::AuthorityBlacklist => "AUTHORITY_BLACKLIST",
            Commands::AuthorityLevel => "AUTHORITY_LEVEL",
            Commands::AuthorityWhitelist => "AUTHORITY_WHITELIST",
            Commands::AutoAis => "AUTO_AIS",
            Commands::AutoIncam1 => "AUTO_INCAM_1",
            Commands::AutoIncam2 => "AUTO_INCAM_2",
            Commands::AutoIncam3 => "AUTO_INCAM_3",
            Commands::AutoIncam4 => "AUTO_INCAM_4",
            Commands::AutoIq => "AUTO_IQ",
            Commands::AutoLogin1 => "AUTO_LOGIN_1",
            Commands::AutoLogin2 => "AUTO_LOGIN_2",
            Commands::AutoLogin3 => "AUTO_LOGIN_3",
            Commands::AutoLogin4 => "AUTO_LOGIN_4",
            Commands::AutoTeam => "AUTO_TEAM",
            Commands::AutoTeamSpecSpam => "AUTO_TEAM_SPEC_SPAM",
            Commands::AxesIndicator => "AXES_INDICATOR",
            Commands::BackwardCompatibility => "BACKWARD_COMPATIBILITY",
            Commands::Ban => "BAN",
            Commands::BanIp => "BAN_IP",
            Commands::BanList => "BAN_LIST",
            Commands::BanUser => "BAN_USER",
            Commands::BanUserList => "BAN_USER_LIST",
            Commands::BigBrother => "BIG_BROTHER",
            Commands::Bookmark0Address => "BOOKMARK_0_ADDRESS",
            Commands::Bookmark0Name => "BOOKMARK_0_NAME",
            Commands::Bookmark0Port => "BOOKMARK_0_PORT",
            Commands::Bookmark10Address => "BOOKMARK_10_ADDRESS",
            Commands::Bookmark10Name => "BOOKMARK_10_NAME",
            Commands::Bookmark10Port => "BOOKMARK_10_PORT",
            Commands::Bookmark1Address => "BOOKMARK_1_ADDRESS",
            Commands::Bookmark1Name => "BOOKMARK_1_NAME",
            Commands::Bookmark1Port => "BOOKMARK_1_PORT",
            Commands::Bookmark2Address => "BOOKMARK_2_ADDRESS",
            Commands::Bookmark2Name => "BOOKMARK_2_NAME",
            Commands::Bookmark2Port => "BOOKMARK_2_PORT",
            Commands::Bookmark3Address => "BOOKMARK_3_ADDRESS",
            Commands::Bookmark3Name => "BOOKMARK_3_NAME",
            Commands::Bookmark3Port => "BOOKMARK_3_PORT",
            Commands::Bookmark4Address => "BOOKMARK_4_ADDRESS",
            Commands::Bookmark4Name => "BOOKMARK_4_NAME",
            Commands::Bookmark4Port => "BOOKMARK_4_PORT",
            Commands::Bookmark5Address => "BOOKMARK_5_ADDRESS",
            Commands::Bookmark5Name => "BOOKMARK_5_NAME",
            Commands::Bookmark5Port => "BOOKMARK_5_PORT",
            Commands::Bookmark6Address => "BOOKMARK_6_ADDRESS",
            Commands::Bookmark6Name => "BOOKMARK_6_NAME",
            Commands::Bookmark6Port => "BOOKMARK_6_PORT",
            Commands::Bookmark7Address => "BOOKMARK_7_ADDRESS",
            Commands::Bookmark7Name => "BOOKMARK_7_NAME",
            Commands::Bookmark7Port => "BOOKMARK_7_PORT",
            Commands::Bookmark8Address => "BOOKMARK_8_ADDRESS",
            Commands::Bookmark8Name => "BOOKMARK_8_NAME",
            Commands::Bookmark8Port => "BOOKMARK_8_PORT",
            Commands::Bookmark9Address => "BOOKMARK_9_ADDRESS",
            Commands::Bookmark9Name => "BOOKMARK_9_NAME",
            Commands::Bookmark9Port => "BOOKMARK_9_PORT",
            Commands::BookmarkMaster0Address => "BOOKMARK__MASTER0_ADDRESS",
            Commands::BookmarkMaster0Name => "BOOKMARK__MASTER0_NAME",
            Commands::BookmarkMaster0Port => "BOOKMARK__MASTER0_PORT",
            Commands::BookmarkMaster10Address => "BOOKMARK__MASTER10_ADDRESS",
            Commands::BookmarkMaster10Name => "BOOKMARK__MASTER10_NAME",
            Commands::BookmarkMaster10Port => "BOOKMARK__MASTER10_PORT",
            Commands::BookmarkMaster1Address => "BOOKMARK__MASTER1_ADDRESS",
            Commands::BookmarkMaster1Name => "BOOKMARK__MASTER1_NAME",
            Commands::BookmarkMaster1Port => "BOOKMARK__MASTER1_PORT",
            Commands::BookmarkMaster2Address => "BOOKMARK__MASTER2_ADDRESS",
            Commands::BookmarkMaster2Name => "BOOKMARK__MASTER2_NAME",
            Commands::BookmarkMaster2Port => "BOOKMARK__MASTER2_PORT",
            Commands::BookmarkMaster3Address => "BOOKMARK__MASTER3_ADDRESS",
            Commands::BookmarkMaster3Name => "BOOKMARK__MASTER3_NAME",
            Commands::BookmarkMaster3Port => "BOOKMARK__MASTER3_PORT",
            Commands::BookmarkMaster4Address => "BOOKMARK__MASTER4_ADDRESS",
            Commands::BookmarkMaster4Name => "BOOKMARK__MASTER4_NAME",
            Commands::BookmarkMaster4Port => "BOOKMARK__MASTER4_PORT",
            Commands::BookmarkMaster5Address => "BOOKMARK__MASTER5_ADDRESS",
            Commands::BookmarkMaster5Name => "BOOKMARK__MASTER5_NAME",
            Commands::BookmarkMaster5Port => "BOOKMARK__MASTER5_PORT",
            Commands::BookmarkMaster6Address => "BOOKMARK__MASTER6_ADDRESS",
            Commands::BookmarkMaster6Name => "BOOKMARK__MASTER6_NAME",
            Commands::BookmarkMaster6Port => "BOOKMARK__MASTER6_PORT",
            Commands::BookmarkMaster7Address => "BOOKMARK__MASTER7_ADDRESS",
            Commands::BookmarkMaster7Name => "BOOKMARK__MASTER7_NAME",
            Commands::BookmarkMaster7Port => "BOOKMARK__MASTER7_PORT",
            Commands::BookmarkMaster8Address => "BOOKMARK__MASTER8_ADDRESS",
            Commands::BookmarkMaster8Name => "BOOKMARK__MASTER8_NAME",
            Commands::BookmarkMaster8Port => "BOOKMARK__MASTER8_PORT",
            Commands::BookmarkMaster9Address => "BOOKMARK__MASTER9_ADDRESS",
            Commands::BookmarkMaster9Name => "BOOKMARK__MASTER9_NAME",
            Commands::BookmarkMaster9Port => "BOOKMARK__MASTER9_PORT",
            Commands::BrakeGaugeLocx => "BRAKE_GAUGE_LOCX",
            Commands::BrakeGaugeLocy => "BRAKE_GAUGE_LOCY",
            Commands::BrakeGaugeSize => "BRAKE_GAUGE_SIZE",
            Commands::BugColorOverflow => "BUG_COLOR_OVERFLOW",
            Commands::BugRip => "BUG_RIP",
            Commands::BugTransparency => "BUG_TRANSPARENCY",
            Commands::BugTransparencyDemand => "BUG_TRANSPARENCY_DEMAND",
            Commands::BugTunnel => "BUG_TUNNEL",
            Commands::Camcenter1 => "CAMCENTER_1",
            Commands::Camcenter2 => "CAMCENTER_2",
            Commands::Camcenter3 => "CAMCENTER_3",
            Commands::Camcenter4 => "CAMCENTER_4",
            Commands::CameraCustomBack => "CAMERA_CUSTOM_BACK",
            Commands::CameraCustomBackFromspeed => "CAMERA_CUSTOM_BACK_FROMSPEED",
            Commands::CameraCustomPitch => "CAMERA_CUSTOM_PITCH",
            Commands::CameraCustomRise => "CAMERA_CUSTOM_RISE",
            Commands::CameraCustomRiseFromspeed => "CAMERA_CUSTOM_RISE_FROMSPEED",
            Commands::CameraCustomTurnSpeed => "CAMERA_CUSTOM_TURN_SPEED",
            Commands::CameraCustomTurnSpeed180 => "CAMERA_CUSTOM_TURN_SPEED_180",
            Commands::CameraCustomZoom => "CAMERA_CUSTOM_ZOOM",
            Commands::CameraFollowStartX => "CAMERA_FOLLOW_START_X",
            Commands::CameraFollowStartY => "CAMERA_FOLLOW_START_Y",
            Commands::CameraFollowStartZ => "CAMERA_FOLLOW_START_Z",
            Commands::CameraForbidCustom => "CAMERA_FORBID_CUSTOM",
            Commands::CameraForbidCustomGlance => "CAMERA_FORBID_CUSTOM_GLANCE",
            Commands::CameraForbidFollow => "CAMERA_FORBID_FOLLOW",
            Commands::CameraForbidFree => "CAMERA_FORBID_FREE",
            Commands::CameraForbidIn => "CAMERA_FORBID_IN",
            Commands::CameraForbidServerCustom => "CAMERA_FORBID_SERVER_CUSTOM",
            Commands::CameraForbidSmart => "CAMERA_FORBID_SMART",
            Commands::CameraFreeStartX => "CAMERA_FREE_START_X",
            Commands::CameraFreeStartY => "CAMERA_FREE_START_Y",
            Commands::CameraFreeStartZ => "CAMERA_FREE_START_Z",
            Commands::CameraGlanceBack => "CAMERA_GLANCE_BACK",
            Commands::CameraGlanceBackFromspeed => "CAMERA_GLANCE_BACK_FROMSPEED",
            Commands::CameraGlancePitch => "CAMERA_GLANCE_PITCH",
            Commands::CameraGlanceRise => "CAMERA_GLANCE_RISE",
            Commands::CameraGlanceRiseFromspeed => "CAMERA_GLANCE_RISE_FROMSPEED",
            Commands::CameraInTurnSpeed => "CAMERA_IN_TURN_SPEED",
            Commands::CameraOverrideCustomGlance => "CAMERA_OVERRIDE_CUSTOM_GLANCE",
            Commands::CameraOverrideCustomGlanceServerCustom => {
                "CAMERA_OVERRIDE_CUSTOM_GLANCE_SERVER_CUSTOM"
            }
            Commands::CameraServerCustomBack => "CAMERA_SERVER_CUSTOM_BACK",
            Commands::CameraServerCustomBackFromspeed => "CAMERA_SERVER_CUSTOM_BACK_FROMSPEED",
            Commands::CameraServerCustomPitch => "CAMERA_SERVER_CUSTOM_PITCH",
            Commands::CameraServerCustomRise => "CAMERA_SERVER_CUSTOM_RISE",
            Commands::CameraServerCustomRiseFromspeed => "CAMERA_SERVER_CUSTOM_RISE_FROMSPEED",
            Commands::CameraServerCustomTurnSpeed => "CAMERA_SERVER_CUSTOM_TURN_SPEED",
            Commands::CameraServerCustomTurnSpeed180 => "CAMERA_SERVER_CUSTOM_TURN_SPEED_180",
            Commands::CameraServerGlanceBack => "CAMERA_SERVER_GLANCE_BACK",
            Commands::CameraServerGlanceBackFromspeed => "CAMERA_SERVER_GLANCE_BACK_FROMSPEED",
            Commands::CameraServerGlancePitch => "CAMERA_SERVER_GLANCE_PITCH",
            Commands::CameraServerGlanceRise => "CAMERA_SERVER_GLANCE_RISE",
            Commands::CameraServerGlanceRiseFromspeed => "CAMERA_SERVER_GLANCE_RISE_FROMSPEED",
            Commands::CameraSmartStartX => "CAMERA_SMART_START_X",
            Commands::CameraSmartStartY => "CAMERA_SMART_START_Y",
            Commands::CameraSmartStartZ => "CAMERA_SMART_START_Z",
            Commands::CameraVisibilityClipSpeed => "CAMERA_VISIBILITY_CLIP_SPEED",
            Commands::CameraVisibilityExtension => "CAMERA_VISIBILITY_EXTENSION",
            Commands::CameraVisibilityLowerWall => "CAMERA_VISIBILITY_LOWER_WALL",
            Commands::CameraVisibilityLowerWallSmart => "CAMERA_VISIBILITY_LOWER_WALL_SMART",
            Commands::CameraVisibilityRecoverySpeed => "CAMERA_VISIBILITY_RECOVERY_SPEED",
            Commands::CameraVisibilitySideskew => "CAMERA_VISIBILITY_SIDESKEW",
            Commands::CameraVisibilityWallDistance => "CAMERA_VISIBILITY_WALL_DISTANCE",
            Commands::Camwobble1 => "CAMWOBBLE_1",
            Commands::Camwobble2 => "CAMWOBBLE_2",
            Commands::Camwobble3 => "CAMWOBBLE_3",
            Commands::Camwobble4 => "CAMWOBBLE_4",
            Commands::Casacl => "CASACL",
            Commands::CenterMessage => "CENTER_MESSAGE",
            Commands::ChatbotAlwaysActive => "CHATBOT_ALWAYS_ACTIVE",
            Commands::ChatbotDecay => "CHATBOT_DECAY",
            Commands::ChatbotDelay => "CHATBOT_DELAY",
            Commands::ChatbotMinTimestep => "CHATBOT_MIN_TIMESTEP",
            Commands::ChatbotNewWallBlindness => "CHATBOT_NEW_WALL_BLINDNESS",
            Commands::ChatbotRange => "CHATBOT_RANGE",
            Commands::ChatterRemoveTime => "CHATTER_REMOVE_TIME",
            Commands::ChatLog => "CHAT_LOG",
            Commands::ChatTooltip => "CHAT_TOOLTIP",
            Commands::CheckErrors => "CHECK_ERRORS",
            Commands::ClientPort => "CLIENT_PORT",
            Commands::CmLocy => "CM_LOCY",
            Commands::Colordepth => "COLORDEPTH",
            Commands::ColorB1 => "COLOR_B_1",
            Commands::ColorB2 => "COLOR_B_2",
            Commands::ColorB3 => "COLOR_B_3",
            Commands::ColorB4 => "COLOR_B_4",
            Commands::ColorG1 => "COLOR_G_1",
            Commands::ColorG2 => "COLOR_G_2",
            Commands::ColorG3 => "COLOR_G_3",
            Commands::ColorG4 => "COLOR_G_4",
            Commands::ColorR1 => "COLOR_R_1",
            Commands::ColorR2 => "COLOR_R_2",
            Commands::ColorR3 => "COLOR_R_3",
            Commands::ColorR4 => "COLOR_R_4",
            Commands::ColorStrings => "COLOR_STRINGS",
            Commands::ConnectionFloodSensitivity => "CONNECTION_FLOOD_SENSITIVITY",
            Commands::ConnectionLimit => "CONNECTION_LIMIT",
            Commands::ConsoleColumns => "CONSOLE_COLUMNS",
            Commands::ConsoleIndent => "CONSOLE_INDENT",
            Commands::ConsoleLadderLog => "CONSOLE_LADDER_LOG",
            Commands::ConsoleLog => "CONSOLE_LOG",
            Commands::ConsoleMessage => "CONSOLE_MESSAGE",
            Commands::ConsoleRows => "CONSOLE_ROWS",
            Commands::ConsoleRowsMax => "CONSOLE_ROWS_MAX",
            Commands::CustomScreenAspect => "CUSTOM_SCREEN_ASPECT",
            Commands::CustomScreenHeight => "CUSTOM_SCREEN_HEIGHT",
            Commands::CustomScreenWidth => "CUSTOM_SCREEN_WIDTH",
            Commands::CustomServerName => "CUSTOM_SERVER_NAME",
            Commands::CycleAccel => "CYCLE_ACCEL",
            Commands::CycleAccelEnemy => "CYCLE_ACCEL_ENEMY",
            Commands::CycleAccelEnemyOverride => "CYCLE_ACCEL_ENEMY_OVERRIDE",
            Commands::CycleAccelOffset => "CYCLE_ACCEL_OFFSET",
            Commands::CycleAccelRim => "CYCLE_ACCEL_RIM",
            Commands::CycleAccelRimOverride => "CYCLE_ACCEL_RIM_OVERRIDE",
            Commands::CycleAccelSelf => "CYCLE_ACCEL_SELF",
            Commands::CycleAccelSelfOverride => "CYCLE_ACCEL_SELF_OVERRIDE",
            Commands::CycleAccelSlingshot => "CYCLE_ACCEL_SLINGSHOT",
            Commands::CycleAccelSlingshotOverride => "CYCLE_ACCEL_SLINGSHOT_OVERRIDE",
            Commands::CycleAccelTeam => "CYCLE_ACCEL_TEAM",
            Commands::CycleAccelTeamOverride => "CYCLE_ACCEL_TEAM_OVERRIDE",
            Commands::CycleAccelTunnel => "CYCLE_ACCEL_TUNNEL",
            Commands::CycleAccelTunnelOverride => "CYCLE_ACCEL_TUNNEL_OVERRIDE",
            Commands::CycleAvoidOldclientBadSync => "CYCLE_AVOID_OLDCLIENT_BAD_SYNC",
            Commands::CycleBlinkFrequency => "CYCLE_BLINK_FREQUENCY",
            Commands::CycleBoostfactorEnemy => "CYCLE_BOOSTFACTOR_ENEMY",
            Commands::CycleBoostfactorEnemyOverride => "CYCLE_BOOSTFACTOR_ENEMY_OVERRIDE",
            Commands::CycleBoostfactorRim => "CYCLE_BOOSTFACTOR_RIM",
            Commands::CycleBoostfactorRimOverride => "CYCLE_BOOSTFACTOR_RIM_OVERRIDE",
            Commands::CycleBoostfactorSelf => "CYCLE_BOOSTFACTOR_SELF",
            Commands::CycleBoostfactorSelfOverride => "CYCLE_BOOSTFACTOR_SELF_OVERRIDE",
            Commands::CycleBoostfactorTeam => "CYCLE_BOOSTFACTOR_TEAM",
            Commands::CycleBoostfactorTeamOverride => "CYCLE_BOOSTFACTOR_TEAM_OVERRIDE",
            Commands::CycleBoostEnemy => "CYCLE_BOOST_ENEMY",
            Commands::CycleBoostEnemyOverride => "CYCLE_BOOST_ENEMY_OVERRIDE",
            Commands::CycleBoostRim => "CYCLE_BOOST_RIM",
            Commands::CycleBoostRimOverride => "CYCLE_BOOST_RIM_OVERRIDE",
            Commands::CycleBoostSelf => "CYCLE_BOOST_SELF",
            Commands::CycleBoostSelfOverride => "CYCLE_BOOST_SELF_OVERRIDE",
            Commands::CycleBoostTeam => "CYCLE_BOOST_TEAM",
            Commands::CycleBoostTeamOverride => "CYCLE_BOOST_TEAM_OVERRIDE",
            Commands::CycleBrake => "CYCLE_BRAKE",
            Commands::CycleBrakeDeplete => "CYCLE_BRAKE_DEPLETE",
            Commands::CycleBrakeDepleteOverride => "CYCLE_BRAKE_DEPLETE_OVERRIDE",
            Commands::CycleBrakeRefill => "CYCLE_BRAKE_REFILL",
            Commands::CycleBrakeRefillOverride => "CYCLE_BRAKE_REFILL_OVERRIDE",
            Commands::CycleBrakeTooltip => "CYCLE_BRAKE_TOOLTIP",
            Commands::CycleDelay => "CYCLE_DELAY",
            Commands::CycleDelayDoublebindBonus => "CYCLE_DELAY_DOUBLEBIND_BONUS",
            Commands::CycleDelayDoublebindBonusOverride => "CYCLE_DELAY_DOUBLEBIND_BONUS_OVERRIDE",
            Commands::CycleDelayTimebased => "CYCLE_DELAY_TIMEBASED",
            Commands::CycleDelayTimebasedOverride => "CYCLE_DELAY_TIMEBASED_OVERRIDE",
            Commands::CycleDistWallShrink => "CYCLE_DIST_WALL_SHRINK",
            Commands::CycleDistWallShrinkOffset => "CYCLE_DIST_WALL_SHRINK_OFFSET",
            Commands::CycleFairAntilag => "CYCLE_FAIR_ANTILAG",
            Commands::CycleFirstSpawnProtection => "CYCLE_FIRST_SPAWN_PROTECTION",
            Commands::CycleInvulnerableTime => "CYCLE_INVULNERABLE_TIME",
            Commands::CycleMaxRefcount => "CYCLE_MAX_REFCOUNT",
            Commands::CyclePacketlossTolerance => "CYCLE_PACKETLOSS_TOLERANCE",
            Commands::CyclePingRubber => "CYCLE_PING_RUBBER",
            Commands::CycleRubber => "CYCLE_RUBBER",
            Commands::CycleRubberDelay => "CYCLE_RUBBER_DELAY",
            Commands::CycleRubberDelayBonus => "CYCLE_RUBBER_DELAY_BONUS",
            Commands::CycleRubberDelayBonusOverride => "CYCLE_RUBBER_DELAY_BONUS_OVERRIDE",
            Commands::CycleRubberDelayOverride => "CYCLE_RUBBER_DELAY_OVERRIDE",
            Commands::CycleRubberLegacy => "CYCLE_RUBBER_LEGACY",
            Commands::CycleRubberMalusTurnOverride => "CYCLE_RUBBER_MALUS_TURN_OVERRIDE",
            Commands::CycleRubberMinadjust => "CYCLE_RUBBER_MINADJUST",
            Commands::CycleRubberMinadjustOverride => "CYCLE_RUBBER_MINADJUST_OVERRIDE",
            Commands::CycleRubberMindistance => "CYCLE_RUBBER_MINDISTANCE",
            Commands::CycleRubberMindistanceGap => "CYCLE_RUBBER_MINDISTANCE_GAP",
            Commands::CycleRubberMindistanceGapBackdoor => "CYCLE_RUBBER_MINDISTANCE_GAP_BACKDOOR",
            Commands::CycleRubberMindistanceGapBackdoorOverride => {
                "CYCLE_RUBBER_MINDISTANCE_GAP_BACKDOOR_OVERRIDE"
            }
            Commands::CycleRubberMindistanceGapOverride => "CYCLE_RUBBER_MINDISTANCE_GAP_OVERRIDE",
            Commands::CycleRubberMindistanceGapSide => "CYCLE_RUBBER_MINDISTANCE_GAP_SIDE",
            Commands::CycleRubberMindistanceLegacy => "CYCLE_RUBBER_MINDISTANCE_LEGACY",
            Commands::CycleRubberMindistanceOverride => "CYCLE_RUBBER_MINDISTANCE_OVERRIDE",
            Commands::CycleRubberMindistancePreparation => "CYCLE_RUBBER_MINDISTANCE_PREPARATION",
            Commands::CycleRubberMindistancePreparationOverride => {
                "CYCLE_RUBBER_MINDISTANCE_PREPARATION_OVERRIDE"
            }
            Commands::CycleRubberMindistanceRatio => "CYCLE_RUBBER_MINDISTANCE_RATIO",
            Commands::CycleRubberMindistanceRatioOverride => {
                "CYCLE_RUBBER_MINDISTANCE_RATIO_OVERRIDE"
            }
            Commands::CycleRubberMindistanceReservoir => "CYCLE_RUBBER_MINDISTANCE_RESERVOIR",
            Commands::CycleRubberMindistanceReservoirOverride => {
                "CYCLE_RUBBER_MINDISTANCE_RESERVOIR_OVERRIDE"
            }
            Commands::CycleRubberMindistanceUnprepared => "CYCLE_RUBBER_MINDISTANCE_UNPREPARED",
            Commands::CycleRubberMindistanceUnpreparedOverride => {
                "CYCLE_RUBBER_MINDISTANCE_UNPREPARED_OVERRIDE"
            }
            Commands::CycleRubberSpeed => "CYCLE_RUBBER_SPEED",
            Commands::CycleRubberSpeedOverride => "CYCLE_RUBBER_SPEED_OVERRIDE",
            Commands::CycleRubberTime => "CYCLE_RUBBER_TIME",
            Commands::CycleRubberTimebased => "CYCLE_RUBBER_TIMEBASED",
            Commands::CycleRubberTimebasedOverride => "CYCLE_RUBBER_TIMEBASED_OVERRIDE",
            Commands::CycleRubberTimeOverride => "CYCLE_RUBBER_TIME_OVERRIDE",
            Commands::CycleRubberWallShrink => "CYCLE_RUBBER_WALL_SHRINK",
            Commands::CycleRubberWallShrinkOverride => "CYCLE_RUBBER_WALL_SHRINK_OVERRIDE",
            Commands::CycleSmoothMinSpeed => "CYCLE_SMOOTH_MIN_SPEED",
            Commands::CycleSmoothThreshold => "CYCLE_SMOOTH_THRESHOLD",
            Commands::CycleSmoothTime => "CYCLE_SMOOTH_TIME",
            Commands::CycleSoundSpeed => "CYCLE_SOUND_SPEED",
            Commands::CycleSpeed => "CYCLE_SPEED",
            Commands::CycleSpeedDecayAbove => "CYCLE_SPEED_DECAY_ABOVE",
            Commands::CycleSpeedDecayAboveOverride => "CYCLE_SPEED_DECAY_ABOVE_OVERRIDE",
            Commands::CycleSpeedDecayBelow => "CYCLE_SPEED_DECAY_BELOW",
            Commands::CycleSpeedDecayBelowOverride => "CYCLE_SPEED_DECAY_BELOW_OVERRIDE",
            Commands::CycleSpeedMax => "CYCLE_SPEED_MAX",
            Commands::CycleSpeedMaxOverride => "CYCLE_SPEED_MAX_OVERRIDE",
            Commands::CycleSpeedMin => "CYCLE_SPEED_MIN",
            Commands::CycleSpeedMinOverride => "CYCLE_SPEED_MIN_OVERRIDE",
            Commands::CycleStartSpeed => "CYCLE_START_SPEED",
            Commands::CycleSyncFf => "CYCLE_SYNC_FF",
            Commands::CycleSyncFfSteps => "CYCLE_SYNC_FF_STEPS",
            Commands::CycleSyncIntervalEnemy => "CYCLE_SYNC_INTERVAL_ENEMY",
            Commands::CycleSyncIntervalSelf => "CYCLE_SYNC_INTERVAL_SELF",
            Commands::CycleTimeTolerance => "CYCLE_TIME_TOLERANCE",
            Commands::CycleTimeToleranceOverride => "CYCLE_TIME_TOLERANCE_OVERRIDE",
            Commands::CycleTurnLeftTooltip => "CYCLE_TURN_LEFT_TOOLTIP",
            Commands::CycleTurnMemory => "CYCLE_TURN_MEMORY",
            Commands::CycleTurnRightTooltip => "CYCLE_TURN_RIGHT_TOOLTIP",
            Commands::CycleTurnSpeedFactor => "CYCLE_TURN_SPEED_FACTOR",
            Commands::CycleTurnSpeedFactorOverride => "CYCLE_TURN_SPEED_FACTOR_OVERRIDE",
            Commands::CycleWallNear => "CYCLE_WALL_NEAR",
            Commands::CycleWallTime => "CYCLE_WALL_TIME",
            Commands::CycleWidth => "CYCLE_WIDTH",
            Commands::CycleWidthOverride => "CYCLE_WIDTH_OVERRIDE",
            Commands::CycleWidthRubberMax => "CYCLE_WIDTH_RUBBER_MAX",
            Commands::CycleWidthRubberMaxOverride => "CYCLE_WIDTH_RUBBER_MAX_OVERRIDE",
            Commands::CycleWidthRubberMin => "CYCLE_WIDTH_RUBBER_MIN",
            Commands::CycleWidthRubberMinOverride => "CYCLE_WIDTH_RUBBER_MIN_OVERRIDE",
            Commands::CycleWidthSide => "CYCLE_WIDTH_SIDE",
            Commands::CycleWidthSideOverride => "CYCLE_WIDTH_SIDE_OVERRIDE",
            Commands::DeclareRoundWinner => "DECLARE_ROUND_WINNER",
            Commands::DedicatedIdle => "DEDICATED_IDLE",
            Commands::DefaultKickReason => "DEFAULT_KICK_REASON",
            Commands::DefaultKickToPort => "DEFAULT_KICK_TO_PORT",
            Commands::DefaultKickToReason => "DEFAULT_KICK_TO_REASON",
            Commands::DefaultKickToServer => "DEFAULT_KICK_TO_SERVER",
            Commands::DefaultShoutPlayer => "DEFAULT_SHOUT_PLAYER",
            Commands::DefaultShoutSpectator => "DEFAULT_SHOUT_SPECTATOR",
            Commands::DisallowRenamePlayer => "DISALLOW_RENAME_PLAYER",
            Commands::DisallowTeamChangePlayer => "DISALLOW_TEAM_CHANGE_PLAYER",
            Commands::Dither => "DITHER",
            Commands::DoublebindTime => "DOUBLEBIND_TIME",
            Commands::DoublebindTimeOverride => "DOUBLEBIND_TIME_OVERRIDE",
            Commands::EnableChat => "ENABLE_CHAT",
            Commands::EnableFriends => "ENABLE_FRIENDS",
            Commands::EnemyChatbotPenalty => "ENEMY_CHATBOT_PENALTY",
            Commands::EnemyCurrenttimeInfluence => "ENEMY_CURRENTTIME_INFLUENCE",
            Commands::EnemyDeadPenalty => "ENEMY_DEAD_PENALTY",
            Commands::EnemySuicideTimeout => "ENEMY_SUICIDE_TIMEOUT",
            Commands::EnemyTeammatePenalty => "ENEMY_TEAMMATE_PENALTY",
            Commands::ExpectAckOnClientPlayback => "EXPECT_ACK_ON_CLIENT_PLAYBACK",
            Commands::Explosion => "EXPLOSION",
            Commands::ExplosionRadius => "EXPLOSION_RADIUS",
            Commands::ExtraRoundTime => "EXTRA_ROUND_TIME",
            Commands::FadeoutNameDelay => "FADEOUT_NAME_DELAY",
            Commands::FailedAttempts => "FAILED_ATTEMPTS",
            Commands::FastestLocx => "FASTEST_LOCX",
            Commands::FastestLocy => "FASTEST_LOCY",
            Commands::FastestSize => "FASTEST_SIZE",
            Commands::FastForwardMaxstep => "FAST_FORWARD_MAXSTEP",
            Commands::FastForwardMaxstepReal => "FAST_FORWARD_MAXSTEP_REAL",
            Commands::FastForwardMaxstepRel => "FAST_FORWARD_MAXSTEP_REL",
            Commands::FavNumPerTeamPlayer1 => "FAV_NUM_PER_TEAM_PLAYER_1",
            Commands::FavNumPerTeamPlayer2 => "FAV_NUM_PER_TEAM_PLAYER_2",
            Commands::FavNumPerTeamPlayer3 => "FAV_NUM_PER_TEAM_PLAYER_3",
            Commands::FavNumPerTeamPlayer4 => "FAV_NUM_PER_TEAM_PLAYER_4",
            Commands::FilterColorNames => "FILTER_COLOR_NAMES",
            Commands::FilterColorServerNames => "FILTER_COLOR_SERVER_NAMES",
            Commands::FilterColorStrings => "FILTER_COLOR_STRINGS",
            Commands::FilterColorTeam => "FILTER_COLOR_TEAM",
            Commands::FilterDarkColorNames => "FILTER_DARK_COLOR_NAMES",
            Commands::FilterDarkColorServerNames => "FILTER_DARK_COLOR_SERVER_NAMES",
            Commands::FilterDarkColorStrings => "FILTER_DARK_COLOR_STRINGS",
            Commands::FilterDarkColorTeam => "FILTER_DARK_COLOR_TEAM",
            Commands::FilterNameEnds => "FILTER_NAME_ENDS",
            Commands::FilterNameMiddle => "FILTER_NAME_MIDDLE",
            Commands::FinishType => "FINISH_TYPE",
            Commands::FirstUse => "FIRST_USE",
            Commands::FloorBlue => "FLOOR_BLUE",
            Commands::FloorDetail => "FLOOR_DETAIL",
            Commands::FloorGreen => "FLOOR_GREEN",
            Commands::FloorMirror => "FLOOR_MIRROR",
            Commands::FloorMirrorInt => "FLOOR_MIRROR_INT",
            Commands::FloorRed => "FLOOR_RED",
            Commands::FontSmallThresholdHeight => "FONT_SMALL_THRESHOLD_HEIGHT",
            Commands::FontSmallThresholdWidth => "FONT_SMALL_THRESHOLD_WIDTH",
            Commands::ForceTurtleMode => "FORCE_TURTLE_MODE",
            Commands::FortressCollapseSpeed => "FORTRESS_COLLAPSE_SPEED",
            Commands::FortressConquestDecayRate => "FORTRESS_CONQUEST_DECAY_RATE",
            Commands::FortressConquestRate => "FORTRESS_CONQUEST_RATE",
            Commands::FortressConquestTimeout => "FORTRESS_CONQUEST_TIMEOUT",
            Commands::FortressDefendRate => "FORTRESS_DEFEND_RATE",
            Commands::FortressHeldScore => "FORTRESS_HELD_SCORE",
            Commands::Friend1 => "FRIEND_1",
            Commands::Friend10 => "FRIEND_10",
            Commands::Friend2 => "FRIEND_2",
            Commands::Friend3 => "FRIEND_3",
            Commands::Friend4 => "FRIEND_4",
            Commands::Friend5 => "FRIEND_5",
            Commands::Friend6 => "FRIEND_6",
            Commands::Friend7 => "FRIEND_7",
            Commands::Friend8 => "FRIEND_8",
            Commands::Friend9 => "FRIEND_9",
            Commands::Fullscreen => "FULLSCREEN",
            Commands::FullscreenMessage => "FULLSCREEN_MESSAGE",
            Commands::GameTimeout => "GAME_TIMEOUT",
            Commands::GameType => "GAME_TYPE",
            Commands::GlanceBackTooltip => "GLANCE_BACK_TOOLTIP",
            Commands::GlanceLeftTooltip => "GLANCE_LEFT_TOOLTIP",
            Commands::GlanceRightTooltip => "GLANCE_RIGHT_TOOLTIP",
            Commands::GlobalId => "GLOBAL_ID",
            Commands::GlExtensions => "GL_EXTENSIONS",
            Commands::GlRenderer => "GL_RENDERER",
            Commands::GlVendor => "GL_VENDOR",
            Commands::GlVersion => "GL_VERSION",
            Commands::GridSize => "GRID_SIZE",
            Commands::GridSizeMoviepack => "GRID_SIZE_MOVIEPACK",
            Commands::HashMethodBlacklist => "HASH_METHOD_BLACKLIST",
            Commands::HelpIntroductoryBlurb => "HELP_INTRODUCTORY_BLURB",
            Commands::HideIdentity1 => "HIDE_IDENTITY_1",
            Commands::HideIdentity2 => "HIDE_IDENTITY_2",
            Commands::HideIdentity3 => "HIDE_IDENTITY_3",
            Commands::HideIdentity4 => "HIDE_IDENTITY_4",
            Commands::HighRim => "HIGH_RIM",
            Commands::HistorySizeChat => "HISTORY_SIZE_CHAT",
            Commands::HistorySizeConsole => "HISTORY_SIZE_CONSOLE",
            Commands::HudCacheThreshold => "HUD_CACHE_THRESHOLD",
            Commands::HudMaxWidth => "HUD_MAX_WIDTH",
            Commands::IdleKickTime => "IDLE_KICK_TIME",
            Commands::IdleRemoveTime => "IDLE_REMOVE_TIME",
            Commands::Include => "INCLUDE",
            Commands::InfinityPlane => "INFINITY_PLANE",
            Commands::IngameMenuTooltip => "INGAME_MENU_TOOLTIP",
            Commands::InstantChatString1_1 => "INSTANT_CHAT_STRING_1_1",
            Commands::InstantChatString1_10 => "INSTANT_CHAT_STRING_1_10",
            Commands::InstantChatString1_11 => "INSTANT_CHAT_STRING_1_11",
            Commands::InstantChatString1_12 => "INSTANT_CHAT_STRING_1_12",
            Commands::InstantChatString1_13 => "INSTANT_CHAT_STRING_1_13",
            Commands::InstantChatString1_14 => "INSTANT_CHAT_STRING_1_14",
            Commands::InstantChatString1_15 => "INSTANT_CHAT_STRING_1_15",
            Commands::InstantChatString1_16 => "INSTANT_CHAT_STRING_1_16",
            Commands::InstantChatString1_17 => "INSTANT_CHAT_STRING_1_17",
            Commands::InstantChatString1_18 => "INSTANT_CHAT_STRING_1_18",
            Commands::InstantChatString1_19 => "INSTANT_CHAT_STRING_1_19",
            Commands::InstantChatString1_2 => "INSTANT_CHAT_STRING_1_2",
            Commands::InstantChatString1_20 => "INSTANT_CHAT_STRING_1_20",
            Commands::InstantChatString1_21 => "INSTANT_CHAT_STRING_1_21",
            Commands::InstantChatString1_22 => "INSTANT_CHAT_STRING_1_22",
            Commands::InstantChatString1_23 => "INSTANT_CHAT_STRING_1_23",
            Commands::InstantChatString1_24 => "INSTANT_CHAT_STRING_1_24",
            Commands::InstantChatString1_25 => "INSTANT_CHAT_STRING_1_25",
            Commands::InstantChatString1_3 => "INSTANT_CHAT_STRING_1_3",
            Commands::InstantChatString1_4 => "INSTANT_CHAT_STRING_1_4",
            Commands::InstantChatString1_5 => "INSTANT_CHAT_STRING_1_5",
            Commands::InstantChatString1_6 => "INSTANT_CHAT_STRING_1_6",
            Commands::InstantChatString1_7 => "INSTANT_CHAT_STRING_1_7",
            Commands::InstantChatString1_8 => "INSTANT_CHAT_STRING_1_8",
            Commands::InstantChatString1_9 => "INSTANT_CHAT_STRING_1_9",
            Commands::InstantChatString2_1 => "INSTANT_CHAT_STRING_2_1",
            Commands::InstantChatString2_10 => "INSTANT_CHAT_STRING_2_10",
            Commands::InstantChatString2_11 => "INSTANT_CHAT_STRING_2_11",
            Commands::InstantChatString2_12 => "INSTANT_CHAT_STRING_2_12",
            Commands::InstantChatString2_13 => "INSTANT_CHAT_STRING_2_13",
            Commands::InstantChatString2_14 => "INSTANT_CHAT_STRING_2_14",
            Commands::InstantChatString2_15 => "INSTANT_CHAT_STRING_2_15",
            Commands::InstantChatString2_16 => "INSTANT_CHAT_STRING_2_16",
            Commands::InstantChatString2_17 => "INSTANT_CHAT_STRING_2_17",
            Commands::InstantChatString2_18 => "INSTANT_CHAT_STRING_2_18",
            Commands::InstantChatString2_19 => "INSTANT_CHAT_STRING_2_19",
            Commands::InstantChatString2_2 => "INSTANT_CHAT_STRING_2_2",
            Commands::InstantChatString2_20 => "INSTANT_CHAT_STRING_2_20",
            Commands::InstantChatString2_21 => "INSTANT_CHAT_STRING_2_21",
            Commands::InstantChatString2_22 => "INSTANT_CHAT_STRING_2_22",
            Commands::InstantChatString2_23 => "INSTANT_CHAT_STRING_2_23",
            Commands::InstantChatString2_24 => "INSTANT_CHAT_STRING_2_24",
            Commands::InstantChatString2_25 => "INSTANT_CHAT_STRING_2_25",
            Commands::InstantChatString2_3 => "INSTANT_CHAT_STRING_2_3",
            Commands::InstantChatString2_4 => "INSTANT_CHAT_STRING_2_4",
            Commands::InstantChatString2_5 => "INSTANT_CHAT_STRING_2_5",
            Commands::InstantChatString2_6 => "INSTANT_CHAT_STRING_2_6",
            Commands::InstantChatString2_7 => "INSTANT_CHAT_STRING_2_7",
            Commands::InstantChatString2_8 => "INSTANT_CHAT_STRING_2_8",
            Commands::InstantChatString2_9 => "INSTANT_CHAT_STRING_2_9",
            Commands::InstantChatString3_1 => "INSTANT_CHAT_STRING_3_1",
            Commands::InstantChatString3_10 => "INSTANT_CHAT_STRING_3_10",
            Commands::InstantChatString3_11 => "INSTANT_CHAT_STRING_3_11",
            Commands::InstantChatString3_12 => "INSTANT_CHAT_STRING_3_12",
            Commands::InstantChatString3_13 => "INSTANT_CHAT_STRING_3_13",
            Commands::InstantChatString3_14 => "INSTANT_CHAT_STRING_3_14",
            Commands::InstantChatString3_15 => "INSTANT_CHAT_STRING_3_15",
            Commands::InstantChatString3_16 => "INSTANT_CHAT_STRING_3_16",
            Commands::InstantChatString3_17 => "INSTANT_CHAT_STRING_3_17",
            Commands::InstantChatString3_18 => "INSTANT_CHAT_STRING_3_18",
            Commands::InstantChatString3_19 => "INSTANT_CHAT_STRING_3_19",
            Commands::InstantChatString3_2 => "INSTANT_CHAT_STRING_3_2",
            Commands::InstantChatString3_20 => "INSTANT_CHAT_STRING_3_20",
            Commands::InstantChatString3_21 => "INSTANT_CHAT_STRING_3_21",
            Commands::InstantChatString3_22 => "INSTANT_CHAT_STRING_3_22",
            Commands::InstantChatString3_23 => "INSTANT_CHAT_STRING_3_23",
            Commands::InstantChatString3_24 => "INSTANT_CHAT_STRING_3_24",
            Commands::InstantChatString3_25 => "INSTANT_CHAT_STRING_3_25",
            Commands::InstantChatString3_3 => "INSTANT_CHAT_STRING_3_3",
            Commands::InstantChatString3_4 => "INSTANT_CHAT_STRING_3_4",
            Commands::InstantChatString3_5 => "INSTANT_CHAT_STRING_3_5",
            Commands::InstantChatString3_6 => "INSTANT_CHAT_STRING_3_6",
            Commands::InstantChatString3_7 => "INSTANT_CHAT_STRING_3_7",
            Commands::InstantChatString3_8 => "INSTANT_CHAT_STRING_3_8",
            Commands::InstantChatString3_9 => "INSTANT_CHAT_STRING_3_9",
            Commands::InstantChatString4_1 => "INSTANT_CHAT_STRING_4_1",
            Commands::InstantChatString4_10 => "INSTANT_CHAT_STRING_4_10",
            Commands::InstantChatString4_11 => "INSTANT_CHAT_STRING_4_11",
            Commands::InstantChatString4_12 => "INSTANT_CHAT_STRING_4_12",
            Commands::InstantChatString4_13 => "INSTANT_CHAT_STRING_4_13",
            Commands::InstantChatString4_14 => "INSTANT_CHAT_STRING_4_14",
            Commands::InstantChatString4_15 => "INSTANT_CHAT_STRING_4_15",
            Commands::InstantChatString4_16 => "INSTANT_CHAT_STRING_4_16",
            Commands::InstantChatString4_17 => "INSTANT_CHAT_STRING_4_17",
            Commands::InstantChatString4_18 => "INSTANT_CHAT_STRING_4_18",
            Commands::InstantChatString4_19 => "INSTANT_CHAT_STRING_4_19",
            Commands::InstantChatString4_2 => "INSTANT_CHAT_STRING_4_2",
            Commands::InstantChatString4_20 => "INSTANT_CHAT_STRING_4_20",
            Commands::InstantChatString4_21 => "INSTANT_CHAT_STRING_4_21",
            Commands::InstantChatString4_22 => "INSTANT_CHAT_STRING_4_22",
            Commands::InstantChatString4_23 => "INSTANT_CHAT_STRING_4_23",
            Commands::InstantChatString4_24 => "INSTANT_CHAT_STRING_4_24",
            Commands::InstantChatString4_25 => "INSTANT_CHAT_STRING_4_25",
            Commands::InstantChatString4_3 => "INSTANT_CHAT_STRING_4_3",
            Commands::InstantChatString4_4 => "INSTANT_CHAT_STRING_4_4",
            Commands::InstantChatString4_5 => "INSTANT_CHAT_STRING_4_5",
            Commands::InstantChatString4_6 => "INSTANT_CHAT_STRING_4_6",
            Commands::InstantChatString4_7 => "INSTANT_CHAT_STRING_4_7",
            Commands::InstantChatString4_8 => "INSTANT_CHAT_STRING_4_8",
            Commands::InstantChatString4_9 => "INSTANT_CHAT_STRING_4_9",
            Commands::KeepPlayerSlot => "KEEP_PLAYER_SLOT",
            Commands::KeepWindowActive => "KEEP_WINDOW_ACTIVE",
            Commands::Keyboard => "KEYBOARD",
            Commands::Kick => "KICK",
            Commands::KickTo => "KICK_TO",
            Commands::Kill => "KILL",
            Commands::LadderlogDecorateTimestamp => "LADDERLOG_DECORATE_TIMESTAMP",
            Commands::LadderlogGameTimeInterval => "LADDERLOG_GAME_TIME_INTERVAL",
            Commands::LadderlogWriteAll => "LADDERLOG_WRITE_ALL",
            Commands::LadderlogWriteAuthorityBlurb => "LADDERLOG_WRITE_AUTHORITY_BLURB",
            Commands::LadderlogWriteBasezoneConquered => "LADDERLOG_WRITE_BASEZONE_CONQUERED",
            Commands::LadderlogWriteBasezoneConquerer => "LADDERLOG_WRITE_BASEZONE_CONQUERER",
            Commands::LadderlogWriteChat => "LADDERLOG_WRITE_CHAT",
            Commands::LadderlogWriteDeathFrag => "LADDERLOG_WRITE_DEATH_FRAG",
            Commands::LadderlogWriteDeathSuicide => "LADDERLOG_WRITE_DEATH_SUICIDE",
            Commands::LadderlogWriteDeathTeamkill => "LADDERLOG_WRITE_DEATH_TEAMKILL",
            Commands::LadderlogWriteEncoding => "LADDERLOG_WRITE_ENCODING",
            Commands::LadderlogWriteGameEnd => "LADDERLOG_WRITE_GAME_END",
            Commands::LadderlogWriteGameTime => "LADDERLOG_WRITE_GAME_TIME",
            Commands::LadderlogWriteMatchWinner => "LADDERLOG_WRITE_MATCH_WINNER",
            Commands::LadderlogWriteNewMatch => "LADDERLOG_WRITE_NEW_MATCH",
            Commands::LadderlogWriteNewRound => "LADDERLOG_WRITE_NEW_ROUND",
            Commands::LadderlogWriteNumHumans => "LADDERLOG_WRITE_NUM_HUMANS",
            Commands::LadderlogWriteOnlinePlayer => "LADDERLOG_WRITE_ONLINE_PLAYER",
            Commands::LadderlogWritePlayerEntered => "LADDERLOG_WRITE_PLAYER_ENTERED",
            Commands::LadderlogWritePlayerLeft => "LADDERLOG_WRITE_PLAYER_LEFT",
            Commands::LadderlogWritePlayerRenamed => "LADDERLOG_WRITE_PLAYER_RENAMED",
            Commands::LadderlogWritePositions => "LADDERLOG_WRITE_POSITIONS",
            Commands::LadderlogWriteRoundScore => "LADDERLOG_WRITE_ROUND_SCORE",
            Commands::LadderlogWriteRoundScoreTeam => "LADDERLOG_WRITE_ROUND_SCORE_TEAM",
            Commands::LadderlogWriteRoundWinner => "LADDERLOG_WRITE_ROUND_WINNER",
            Commands::LadderlogWriteSacrifice => "LADDERLOG_WRITE_SACRIFICE",
            Commands::LadderlogWriteTeamCreated => "LADDERLOG_WRITE_TEAM_CREATED",
            Commands::LadderlogWriteTeamDestroyed => "LADDERLOG_WRITE_TEAM_DESTROYED",
            Commands::LadderlogWriteTeamPlayerAdded => "LADDERLOG_WRITE_TEAM_PLAYER_ADDED",
            Commands::LadderlogWriteTeamPlayerRemoved => "LADDERLOG_WRITE_TEAM_PLAYER_REMOVED",
            Commands::LadderlogWriteTeamRenamed => "LADDERLOG_WRITE_TEAM_RENAMED",
            Commands::LadderlogWriteWaitForExternalScript => {
                "LADDERLOG_WRITE_WAIT_FOR_EXTERNAL_SCRIPT"
            }
            Commands::LadderGainExtra => "LADDER_GAIN_EXTRA",
            Commands::LadderLoseMinOnLoad => "LADDER_LOSE_MIN_ON_LOAD",
            Commands::LadderLosePercentOnLoad => "LADDER_LOSE_PERCENT_ON_LOAD",
            Commands::LadderMinBet => "LADDER_MIN_BET",
            Commands::LadderPercentBet => "LADDER_PERCENT_BET",
            Commands::LadderTax => "LADDER_TAX",
            Commands::LagCredit => "LAG_CREDIT",
            Commands::LagCreditSingle => "LAG_CREDIT_SINGLE",
            Commands::LagCreditTime => "LAG_CREDIT_TIME",
            Commands::LagCreditVariance => "LAG_CREDIT_VARIANCE",
            Commands::LagFastTime => "LAG_FAST_TIME",
            Commands::LagFastWeight => "LAG_FAST_WEIGHT",
            Commands::LagFrequencyThreshold => "LAG_FREQUENCY_THRESHOLD",
            Commands::LagMaxSpeedupTimer => "LAG_MAX_SPEEDUP_TIMER",
            Commands::LagOffsetClient => "LAG_OFFSET_CLIENT",
            Commands::LagOffsetLegacy => "LAG_OFFSET_LEGACY",
            Commands::LagOffsetServer => "LAG_OFFSET_SERVER",
            Commands::LagOMeter => "LAG_O_METER",
            Commands::LagOMeterBlend => "LAG_O_METER_BLEND",
            Commands::LagOMeterScale => "LAG_O_METER_SCALE",
            Commands::LagOMeterThreshold => "LAG_O_METER_THRESHOLD",
            Commands::LagOMeterUseOld => "LAG_O_METER_USE_OLD",
            Commands::LagSlowTime => "LAG_SLOW_TIME",
            Commands::LagSlowWeight => "LAG_SLOW_WEIGHT",
            Commands::LagSweetSpot => "LAG_SWEET_SPOT",
            Commands::LagThreshold => "LAG_THRESHOLD",
            Commands::LanguageFirst => "LANGUAGE_FIRST",
            Commands::LanguageSecond => "LANGUAGE_SECOND",
            Commands::LastChatBreakTime => "LAST_CHAT_BREAK_TIME",
            Commands::LastCheckErrors => "LAST_CHECK_ERRORS",
            Commands::LastColordepth => "LAST_COLORDEPTH",
            Commands::LastFullscreen => "LAST_FULLSCREEN",
            Commands::LastZdepth => "LAST_ZDEPTH",
            Commands::LegacyLogNames => "LEGACY_LOG_NAMES",
            Commands::LimitRounds => "LIMIT_ROUNDS",
            Commands::LimitScore => "LIMIT_SCORE",
            Commands::LimitTime => "LIMIT_TIME",
            Commands::LocalTeam => "LOCAL_TEAM",
            Commands::LocalUser => "LOCAL_USER",
            Commands::LowerSky => "LOWER_SKY",
            Commands::MapFile => "MAP_FILE",
            Commands::MapFileOverride => "MAP_FILE_OVERRIDE",
            Commands::MapUri => "MAP_URI",
            Commands::MaxClients => "MAX_CLIENTS",
            Commands::MaxClientsSameIpHard => "MAX_CLIENTS_SAME_IP_HARD",
            Commands::MaxClientsSameIpSoft => "MAX_CLIENTS_SAME_IP_SOFT",
            Commands::MaxInRate => "MAX_IN_RATE",
            Commands::MaxOutRate => "MAX_OUT_RATE",
            Commands::MaxPlayersSameIp => "MAX_PLAYERS_SAME_IP",
            Commands::MaxProtocolVersion => "MAX_PROTOCOL_VERSION",
            Commands::MaxVotes => "MAX_VOTES",
            Commands::MaxVotesPerVoter => "MAX_VOTES_PER_VOTER",
            Commands::Md5Prefix => "MD5_PREFIX",
            Commands::Md5Suffix => "MD5_SUFFIX",
            Commands::MessageOfDay => "MESSAGE_OF_DAY",
            Commands::MessageOfDayTimeout => "MESSAGE_OF_DAY_TIMEOUT",
            Commands::MinPlayers => "MIN_PLAYERS",
            Commands::MinPlayTimeOnline => "MIN_PLAY_TIME_ONLINE",
            Commands::MinPlayTimeTeam => "MIN_PLAY_TIME_TEAM",
            Commands::MinPlayTimeTotal => "MIN_PLAY_TIME_TOTAL",
            Commands::MinProtocolVersion => "MIN_PROTOCOL_VERSION",
            Commands::MinVoters => "MIN_VOTERS",
            Commands::MouseGrab => "MOUSE_GRAB",
            Commands::MoveTo => "MOVE_TO",
            Commands::Moviepack => "MOVIEPACK",
            Commands::MoviepackFloorBlue => "MOVIEPACK_FLOOR_BLUE",
            Commands::MoviepackFloorGreen => "MOVIEPACK_FLOOR_GREEN",
            Commands::MoviepackFloorRed => "MOVIEPACK_FLOOR_RED",
            Commands::MoviepackRimWallStretchX => "MOVIEPACK_RIM_WALL_STRETCH_X",
            Commands::MoviepackRimWallStretchY => "MOVIEPACK_RIM_WALL_STRETCH_Y",
            Commands::MoviepackWallStretch => "MOVIEPACK_WALL_STRETCH",
            Commands::NameTeamAfterPlayer1 => "NAME_TEAM_AFTER_PLAYER_1",
            Commands::NameTeamAfterPlayer2 => "NAME_TEAM_AFTER_PLAYER_2",
            Commands::NameTeamAfterPlayer3 => "NAME_TEAM_AFTER_PLAYER_3",
            Commands::NameTeamAfterPlayer4 => "NAME_TEAM_AFTER_PLAYER_4",
            Commands::NetworkAutobanFactor => "NETWORK_AUTOBAN_FACTOR",
            Commands::NetworkAutobanMaxKph => "NETWORK_AUTOBAN_MAX_KPH",
            Commands::NetworkAutobanOffset => "NETWORK_AUTOBAN_OFFSET",
            Commands::NetworkMinBan => "NETWORK_MIN_BAN",
            Commands::NetworkSpectatorTime => "NETWORK_SPECTATOR_TIME",
            Commands::NewFeatureDelay => "NEW_FEATURE_DELAY",
            Commands::NewTeamAllowed => "NEW_TEAM_ALLOWED",
            Commands::NumAis => "NUM_AIS",
            Commands::Password => "PASSWORD",
            Commands::PasswordStorage => "PASSWORD_STORAGE",
            Commands::PingCharity => "PING_CHARITY",
            Commands::PingCharityMax => "PING_CHARITY_MAX",
            Commands::PingCharityMin => "PING_CHARITY_MIN",
            Commands::PingCharityServer => "PING_CHARITY_SERVER",
            Commands::PingFloodGlobal => "PING_FLOOD_GLOBAL",
            Commands::PingFloodTime10 => "PING_FLOOD_TIME_10",
            Commands::PingFloodTime100 => "PING_FLOOD_TIME_100",
            Commands::PingFloodTime20 => "PING_FLOOD_TIME_20",
            Commands::PingFloodTime50 => "PING_FLOOD_TIME_50",
            Commands::PingLocx => "PING_LOCX",
            Commands::PingLocy => "PING_LOCY",
            Commands::PingSize => "PING_SIZE",
            Commands::Players => "PLAYERS",
            Commands::Player1 => "PLAYER_1",
            Commands::Player2 => "PLAYER_2",
            Commands::Player3 => "PLAYER_3",
            Commands::Player4 => "PLAYER_4",
            Commands::PlayerChatWaitFraction => "PLAYER_CHAT_WAIT_FRACTION",
            Commands::PlayerChatWaitMax => "PLAYER_CHAT_WAIT_MAX",
            Commands::PlayerChatWaitSingle => "PLAYER_CHAT_WAIT_SINGLE",
            Commands::PlayerChatWaitTeamleader => "PLAYER_CHAT_WAIT_TEAMLEADER",
            Commands::PlayerListHiddenPlayerPrefix => "PLAYER_LIST_HIDDEN_PLAYER_PREFIX",
            Commands::PlayerMessage => "PLAYER_MESSAGE",
            Commands::PlayerRandomColor => "PLAYER_RANDOM_COLOR",
            Commands::PlayTimeOnline => "PLAY_TIME_ONLINE",
            Commands::PlayTimeTeam => "PLAY_TIME_TEAM",
            Commands::PlayTimeTotal => "PLAY_TIME_TOTAL",
            Commands::PngScreenshot => "PNG_SCREENSHOT",
            Commands::PredictObjects => "PREDICT_OBJECTS",
            Commands::PrefixSpamEnable => "PREFIX_SPAM_ENABLE",
            Commands::PrefixSpamLengthMultiplier => "PREFIX_SPAM_LENGTH_MULTIPLIER",
            Commands::PrefixSpamNumberColorCodesMultiplier => {
                "PREFIX_SPAM_NUMBER_COLOR_CODES_MULTIPLIER"
            }
            Commands::PrefixSpamNumberKnownPrefixesMultiplier => {
                "PREFIX_SPAM_NUMBER_KNOWN_PREFIXES_MULTIPLIER"
            }
            Commands::PrefixSpamRequiredScore => "PREFIX_SPAM_REQUIRED_SCORE",
            Commands::PrefixSpamStartColorMultiplier => "PREFIX_SPAM_START_COLOR_MULTIPLIER",
            Commands::PrefixSpamTimeoutMultiplier => "PREFIX_SPAM_TIMEOUT_MULTIPLIER",
            Commands::ProtectSensitiveFiles => "PROTECT_SENSITIVE_FILES",
            Commands::RealArenaSizeFactor => "REAL_ARENA_SIZE_FACTOR",
            Commands::RealCycleSpeedFactor => "REAL_CYCLE_SPEED_FACTOR",
            Commands::RecordingDebuglevel => "RECORDING_DEBUGLEVEL",
            Commands::RecordTurtleMode => "RECORD_TURTLE_MODE",
            Commands::RemoveHelpTopic => "REMOVE_HELP_TOPIC",
            Commands::Rename => "RENAME",
            Commands::ReserveScreenName => "RESERVE_SCREEN_NAME",
            Commands::ResourceRepositoryClient => "RESOURCE_REPOSITORY_CLIENT",
            Commands::ResourceRepositoryServer => "RESOURCE_REPOSITORY_SERVER",
            Commands::RimWallStretchX => "RIM_WALL_STRETCH_X",
            Commands::RimWallStretchY => "RIM_WALL_STRETCH_Y",
            Commands::RimWallWrapY => "RIM_WALL_WRAP_Y",
            Commands::Rinclude => "RINCLUDE",
            Commands::RoundCenterMessage => "ROUND_CENTER_MESSAGE",
            Commands::RoundConsoleMessage => "ROUND_CONSOLE_MESSAGE",
            Commands::RubberGaugeLocx => "RUBBER_GAUGE_LOCX",
            Commands::RubberGaugeLocy => "RUBBER_GAUGE_LOCY",
            Commands::RubberGaugeSize => "RUBBER_GAUGE_SIZE",
            Commands::SavedInVersion => "SAVED_IN_VERSION",
            Commands::Say => "SAY",
            Commands::ScoreDeathzone => "SCORE_DEATHZONE",
            Commands::ScoreDie => "SCORE_DIE",
            Commands::ScoreHole => "SCORE_HOLE",
            Commands::ScoreKill => "SCORE_KILL",
            Commands::ScoreLocx => "SCORE_LOCX",
            Commands::ScoreLocy => "SCORE_LOCY",
            Commands::ScoreSize => "SCORE_SIZE",
            Commands::ScoreSuicide => "SCORE_SUICIDE",
            Commands::ScoreSurvive => "SCORE_SURVIVE",
            Commands::ScoreWin => "SCORE_WIN",
            Commands::ServerDns => "SERVER_DNS",
            Commands::ServerIp => "SERVER_IP",
            Commands::ServerName => "SERVER_NAME",
            Commands::ServerPort => "SERVER_PORT",
            Commands::SettingLegacyBehaviorAnnoying => "SETTING_LEGACY_BEHAVIOR_ANNOYING",
            Commands::SettingLegacyBehaviorBreaking => "SETTING_LEGACY_BEHAVIOR_BREAKING",
            Commands::SettingLegacyBehaviorBumpy => "SETTING_LEGACY_BEHAVIOR_BUMPY",
            Commands::SettingLegacyBehaviorCheating => "SETTING_LEGACY_BEHAVIOR_CHEATING",
            Commands::SettingLegacyBehaviorVisual => "SETTING_LEGACY_BEHAVIOR_VISUAL",
            Commands::ShowAlive => "SHOW_ALIVE",
            Commands::ShowBrake => "SHOW_BRAKE",
            Commands::ShowFastest => "SHOW_FASTEST",
            Commands::ShowFps => "SHOW_FPS",
            Commands::ShowHud => "SHOW_HUD",
            Commands::ShowOwnIp => "SHOW_OWN_IP",
            Commands::ShowOwnName => "SHOW_OWN_NAME",
            Commands::ShowPing => "SHOW_PING",
            Commands::ShowRecordingTime => "SHOW_RECORDING_TIME",
            Commands::ShowRubber => "SHOW_RUBBER",
            Commands::ShowScore => "SHOW_SCORE",
            Commands::ShowSpeed => "SHOW_SPEED",
            Commands::ShowTime => "SHOW_TIME",
            Commands::ShowTime24 => "SHOW_TIME_24",
            Commands::ShuffleSpamMessagesPerRound => "SHUFFLE_SPAM_MESSAGES_PER_ROUND",
            Commands::Silence => "SILENCE",
            Commands::SilenceDefault => "SILENCE_DEFAULT",
            Commands::SimpleTrail => "SIMPLE_TRAIL",
            Commands::Sinclude => "SINCLUDE",
            Commands::SizeFactor => "SIZE_FACTOR",
            Commands::SkyWobble => "SKY_WOBBLE",
            Commands::Slap => "SLAP",
            Commands::SmartGlanceCustom1 => "SMART_GLANCE_CUSTOM_1",
            Commands::SmartGlanceCustom2 => "SMART_GLANCE_CUSTOM_2",
            Commands::SmartGlanceCustom3 => "SMART_GLANCE_CUSTOM_3",
            Commands::SmartGlanceCustom4 => "SMART_GLANCE_CUSTOM_4",
            Commands::SmoothShading => "SMOOTH_SHADING",
            Commands::SoftwareRenderer => "SOFTWARE_RENDERER",
            Commands::SoundBufferShift => "SOUND_BUFFER_SHIFT",
            Commands::SoundQuality => "SOUND_QUALITY",
            Commands::SoundSources => "SOUND_SOURCES",
            Commands::SpamAutokick => "SPAM_AUTOKICK",
            Commands::SpamAutokickCount => "SPAM_AUTOKICK_COUNT",
            Commands::SpamMaxlen => "SPAM_MAXLEN",
            Commands::SpamMaxlenOverride => "SPAM_MAXLEN_OVERRIDE",
            Commands::SpamPenalty => "SPAM_PENALTY",
            Commands::SpamProtection => "SPAM_PROTECTION",
            Commands::SpamProtectionChat => "SPAM_PROTECTION_CHAT",
            Commands::SpamProtectionRepeat => "SPAM_PROTECTION_REPEAT",
            Commands::SpamProtectionVote => "SPAM_PROTECTION_VOTE",
            Commands::Sparks => "SPARKS",
            Commands::SpawnWingmenBack => "SPAWN_WINGMEN_BACK",
            Commands::SpawnWingmenSide => "SPAWN_WINGMEN_SIDE",
            Commands::SpectatorMode1 => "SPECTATOR_MODE_1",
            Commands::SpectatorMode2 => "SPECTATOR_MODE_2",
            Commands::SpectatorMode3 => "SPECTATOR_MODE_3",
            Commands::SpectatorMode4 => "SPECTATOR_MODE_4",
            Commands::SpeedFactor => "SPEED_FACTOR",
            Commands::SpeedGaugeLocx => "SPEED_GAUGE_LOCX",
            Commands::SpeedGaugeLocy => "SPEED_GAUGE_LOCY",
            Commands::SpeedGaugeSize => "SPEED_GAUGE_SIZE",
            Commands::SpAiIq => "SP_AI_IQ",
            Commands::SpAutoAis => "SP_AUTO_AIS",
            Commands::SpAutoIq => "SP_AUTO_IQ",
            Commands::SpExplosionRadius => "SP_EXPLOSION_RADIUS",
            Commands::SpFinishType => "SP_FINISH_TYPE",
            Commands::SpGameType => "SP_GAME_TYPE",
            Commands::SpLimitRounds => "SP_LIMIT_ROUNDS",
            Commands::SpLimitScore => "SP_LIMIT_SCORE",
            Commands::SpLimitTime => "SP_LIMIT_TIME",
            Commands::SpMinPlayers => "SP_MIN_PLAYERS",
            Commands::SpNumAis => "SP_NUM_AIS",
            Commands::SpScoreWin => "SP_SCORE_WIN",
            Commands::SpSizeFactor => "SP_SIZE_FACTOR",
            Commands::SpSpeedFactor => "SP_SPEED_FACTOR",
            Commands::SpTeamsMax => "SP_TEAMS_MAX",
            Commands::SpTeamsMin => "SP_TEAMS_MIN",
            Commands::SpTeamBalanceOnQuit => "SP_TEAM_BALANCE_ON_QUIT",
            Commands::SpTeamBalanceWithAis => "SP_TEAM_BALANCE_WITH_AIS",
            Commands::SpTeamMaxImbalance => "SP_TEAM_MAX_IMBALANCE",
            Commands::SpTeamMaxPlayers => "SP_TEAM_MAX_PLAYERS",
            Commands::SpTeamMinPlayers => "SP_TEAM_MIN_PLAYERS",
            Commands::SpWallsLength => "SP_WALLS_LENGTH",
            Commands::SpWallsStayUpDelay => "SP_WALLS_STAY_UP_DELAY",
            Commands::SpWinZoneMinLastDeath => "SP_WIN_ZONE_MIN_LAST_DEATH",
            Commands::SpWinZoneMinRoundTime => "SP_WIN_ZONE_MIN_ROUND_TIME",
            Commands::StartCam1 => "START_CAM_1",
            Commands::StartCam2 => "START_CAM_2",
            Commands::StartCam3 => "START_CAM_3",
            Commands::StartCam4 => "START_CAM_4",
            Commands::StartFov1 => "START_FOV_1",
            Commands::StartFov2 => "START_FOV_2",
            Commands::StartFov3 => "START_FOV_3",
            Commands::StartFov4 => "START_FOV_4",
            Commands::StartNewMatch => "START_NEW_MATCH",
            Commands::StopRecording => "STOP_RECORDING",
            Commands::Suspend => "SUSPEND",
            Commands::SuspendDefaultRounds => "SUSPEND_DEFAULT_ROUNDS",
            Commands::SwapMode => "SWAP_MODE",
            Commands::SwitchViewTooltip => "SWITCH_VIEW_TOOLTIP",
            Commands::TalkToMaster => "TALK_TO_MASTER",
            Commands::Teams => "TEAMS",
            Commands::TeamsMax => "TEAMS_MAX",
            Commands::TeamsMin => "TEAMS_MIN",
            Commands::TeamBalanceOnQuit => "TEAM_BALANCE_ON_QUIT",
            Commands::TeamBalanceWithAis => "TEAM_BALANCE_WITH_AIS",
            Commands::TeamBlue1 => "TEAM_BLUE_1",
            Commands::TeamBlue2 => "TEAM_BLUE_2",
            Commands::TeamBlue3 => "TEAM_BLUE_3",
            Commands::TeamBlue4 => "TEAM_BLUE_4",
            Commands::TeamBlue5 => "TEAM_BLUE_5",
            Commands::TeamBlue6 => "TEAM_BLUE_6",
            Commands::TeamBlue7 => "TEAM_BLUE_7",
            Commands::TeamBlue8 => "TEAM_BLUE_8",
            Commands::TeamCenterIsBoss => "TEAM_CENTER_IS_BOSS",
            Commands::TeamEliminationMode => "TEAM_ELIMINATION_MODE",
            Commands::TeamGreen1 => "TEAM_GREEN_1",
            Commands::TeamGreen2 => "TEAM_GREEN_2",
            Commands::TeamGreen3 => "TEAM_GREEN_3",
            Commands::TeamGreen4 => "TEAM_GREEN_4",
            Commands::TeamGreen5 => "TEAM_GREEN_5",
            Commands::TeamGreen6 => "TEAM_GREEN_6",
            Commands::TeamGreen7 => "TEAM_GREEN_7",
            Commands::TeamGreen8 => "TEAM_GREEN_8",
            Commands::TeamMaxImbalance => "TEAM_MAX_IMBALANCE",
            Commands::TeamMaxPlayers => "TEAM_MAX_PLAYERS",
            Commands::TeamMinPlayers => "TEAM_MIN_PLAYERS",
            Commands::TeamName1 => "TEAM_NAME_1",
            Commands::TeamName2 => "TEAM_NAME_2",
            Commands::TeamName3 => "TEAM_NAME_3",
            Commands::TeamName4 => "TEAM_NAME_4",
            Commands::TeamName5 => "TEAM_NAME_5",
            Commands::TeamName6 => "TEAM_NAME_6",
            Commands::TeamName7 => "TEAM_NAME_7",
            Commands::TeamName8 => "TEAM_NAME_8",
            Commands::TeamRed1 => "TEAM_RED_1",
            Commands::TeamRed2 => "TEAM_RED_2",
            Commands::TeamRed3 => "TEAM_RED_3",
            Commands::TeamRed4 => "TEAM_RED_4",
            Commands::TeamRed5 => "TEAM_RED_5",
            Commands::TeamRed6 => "TEAM_RED_6",
            Commands::TeamRed7 => "TEAM_RED_7",
            Commands::TeamRed8 => "TEAM_RED_8",
            Commands::TexturesHi => "TEXTURES_HI",
            Commands::TextureMode0 => "TEXTURE_MODE_0",
            Commands::TextureMode1 => "TEXTURE_MODE_1",
            Commands::TextureMode2 => "TEXTURE_MODE_2",
            Commands::TextureMode3 => "TEXTURE_MODE_3",
            Commands::TextOut => "TEXT_OUT",
            Commands::TimebotActionHigh => "TIMEBOT_ACTION_HIGH",
            Commands::TimebotActionMax => "TIMEBOT_ACTION_MAX",
            Commands::TimebotActionMedium => "TIMEBOT_ACTION_MEDIUM",
            Commands::TimebotKickSeverity => "TIMEBOT_KICK_SEVERITY",
            Commands::TimebotSensitivity => "TIMEBOT_SENSITIVITY",
            Commands::TitleOfDay => "TITLE_OF_DAY",
            Commands::ToggleSpectatorTooltip => "TOGGLE_SPECTATOR_TOOLTIP",
            Commands::TopologyPolice => "TOPOLOGY_POLICE",
            Commands::TopologyPoliceParallel => "TOPOLOGY_POLICE_PARALLEL",
            Commands::TrustLan => "TRUST_LAN",
            Commands::UnbanIp => "UNBAN_IP",
            Commands::UnbanUser => "UNBAN_USER",
            Commands::UnlockAllTeams => "UNLOCK_ALL_TEAMS",
            Commands::Unsilence => "UNSILENCE",
            Commands::Unsuspend => "UNSUSPEND",
            Commands::UpperSky => "UPPER_SKY",
            Commands::Url => "URL",
            Commands::User1 => "USER_1",
            Commands::User2 => "USER_2",
            Commands::User3 => "USER_3",
            Commands::User4 => "USER_4",
            Commands::UserAlias => "USER_ALIAS",
            Commands::UserLevel => "USER_LEVEL",
            Commands::UserRemove => "USER_REMOVE",
            Commands::UseDisplaylists => "USE_DISPLAYLISTS",
            Commands::ViewportConf => "VIEWPORT_CONF",
            Commands::ViewportToPlayer1 => "VIEWPORT_TO_PLAYER_1",
            Commands::ViewportToPlayer2 => "VIEWPORT_TO_PLAYER_2",
            Commands::ViewportToPlayer3 => "VIEWPORT_TO_PLAYER_3",
            Commands::ViewportToPlayer4 => "VIEWPORT_TO_PLAYER_4",
            Commands::Voice => "VOICE",
            Commands::VotesCancel => "VOTES_CANCEL",
            Commands::VotesSuspend => "VOTES_SUSPEND",
            Commands::VotesSuspendDefault => "VOTES_SUSPEND_DEFAULT",
            Commands::VotesUnsuspend => "VOTES_UNSUSPEND",
            Commands::VoteKickReason => "VOTE_KICK_REASON",
            Commands::VoteKickToPort => "VOTE_KICK_TO_PORT",
            Commands::VoteKickToServer => "VOTE_KICK_TO_SERVER",
            Commands::VoteUseServerControlledKick => "VOTE_USE_SERVER_CONTROLLED_KICK",
            Commands::VotingBias => "VOTING_BIAS",
            Commands::VotingBiasCommand => "VOTING_BIAS_COMMAND",
            Commands::VotingBiasInclude => "VOTING_BIAS_INCLUDE",
            Commands::VotingBiasKick => "VOTING_BIAS_KICK",
            Commands::VotingBiasSilence => "VOTING_BIAS_SILENCE",
            Commands::VotingBiasSuspend => "VOTING_BIAS_SUSPEND",
            Commands::VotingBiasVoice => "VOTING_BIAS_VOICE",
            Commands::VotingDecay => "VOTING_DECAY",
            Commands::VotingHarmTime => "VOTING_HARM_TIME",
            Commands::VotingKickMinharm => "VOTING_KICK_MINHARM",
            Commands::VotingKickTime => "VOTING_KICK_TIME",
            Commands::VotingMaturity => "VOTING_MATURITY",
            Commands::VotingPrivacy => "VOTING_PRIVACY",
            Commands::VotingSpamIssue => "VOTING_SPAM_ISSUE",
            Commands::VotingSpamReject => "VOTING_SPAM_REJECT",
            Commands::VotingStartDecay => "VOTING_START_DECAY",
            Commands::VotingSuspendRounds => "VOTING_SUSPEND_ROUNDS",
            Commands::VotingTimeout => "VOTING_TIMEOUT",
            Commands::VotingTimeoutPerVoter => "VOTING_TIMEOUT_PER_VOTER",
            Commands::WaitForExternalScript => "WAIT_FOR_EXTERNAL_SCRIPT",
            Commands::WaitForExternalScriptTimeout => "WAIT_FOR_EXTERNAL_SCRIPT_TIMEOUT",
            Commands::WallsLength => "WALLS_LENGTH",
            Commands::WallsStayUpDelay => "WALLS_STAY_UP_DELAY",
            Commands::WhitelistEnemiesIp => "WHITELIST_ENEMIES_IP",
            Commands::WhitelistEnemiesUsername => "WHITELIST_ENEMIES_USERNAME",
            Commands::WhiteSparks => "WHITE_SPARKS",
            Commands::WinZoneDeaths => "WIN_ZONE_DEATHS",
            Commands::WinZoneExpansion => "WIN_ZONE_EXPANSION",
            Commands::WinZoneInitialSize => "WIN_ZONE_INITIAL_SIZE",
            Commands::WinZoneMinLastDeath => "WIN_ZONE_MIN_LAST_DEATH",
            Commands::WinZoneMinRoundTime => "WIN_ZONE_MIN_ROUND_TIME",
            Commands::WinZoneRandomness => "WIN_ZONE_RANDOMNESS",
            Commands::WordDelimiters => "WORD_DELIMITERS",
            Commands::WrapMenu => "WRAP_MENU",
            Commands::Zdepth => "ZDEPTH",
            Commands::ZoneAlpha => "ZONE_ALPHA",
            Commands::ZoneAlphaServer => "ZONE_ALPHA_SERVER",
            Commands::ZoneAlphaToggle => "ZONE_ALPHA_TOGGLE",
            Commands::ZoneBottom => "ZONE_BOTTOM",
            Commands::ZoneHeight => "ZONE_HEIGHT",
            Commands::ZoneSegments => "ZONE_SEGMENTS",
            Commands::ZoneSegLength => "ZONE_SEG_LENGTH",
        };
        write!(f, "{}", word)
    }
}
